display-name: "1Password CLI"

versions:
  url: https://app-updates.agilebits.com/check/1/0/CLI2/en/2.0.0/N
  match: /[0-9]+\.[0-9]+\.[0-9]+/

warnings:
  - vendored

platforms:
  - darwin

build:
  dependencies:
    info-zip.org/unzip: ^6
    gnupg.org: ^2
    curl.se: '*'
  env:
    aarch64:
      ARCH_ALIAS: arm64
    x86-64:
      ARCH_ALIAS: amd64
  script:
    - curl -sSfo op.zip https://cache.agilebits.com/dist/1P/op2/pkg/v{{version.raw}}/op_{{hw.platform}}_${ARCH_ALIAS}_v{{version.raw}}.zip
    - unzip -od op op.zip && rm op.zip
    - mkdir -p {{prefix}}/bin
    - mv op/op {{prefix}}/bin/

provides:
  - bin/op

# TODO: run the tool to check it works!
test: test "$(op --version)" = {{version.raw}}
