distributable:
  url: https://github.com/awslabs/eks-node-viewer/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: awslabs/eks-node-viewer

build:
  dependencies:
    go.dev: ~1.24.2
  script: go build $ARGS -ldflags="$GO_LDFLAGS" ./cmd/eks-node-viewer
  env:
    ARGS:
      - -trimpath
      - -o={{prefix}}/bin/eks-node-viewer
    GO_LDFLAGS:
      - -s
      - -w
      - -X main.version="{{ version }}"
      - -X main.date="$( date --iso-8601=minutes )"
      - -X main.builtBy="pkgx"
    linux:
      GO_LDFLAGS:
        - -buildmode=pie

provides:
  - bin/eks-node-viewer

test: eks-node-viewer --version | grep "eks-node-viewer version {{version}}"
