distributable:
  url: https://github.com/viaduct-ai/kustomize-sops/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: viaduct-ai/kustomize-sops

build:
  dependencies:
    go.dev: ~1.22
  script:
    - go mod download
    - go build -v -trimpath -ldflags="$GO_LDFLAGS" -o {{prefix}}/bin/ksops
  env:
    GO_LDFLAGS:
      - -s
      - -w
    linux:
      GO_LDFLAGS:
        - -buildmode=pie

provides:
  - bin/ksops

test:
  - run: ksops $FIXTURE >out.yaml
    fixture:
      extname: yaml
      content: |
        apiVersion: viaduct.ai/v1
        kind: ksops
        metadata:
          name: secret-generator
          annotations:
            config.kubernetes.io/function: |
              exec:
                path: ksops
        files: []
