distributable:
  url: https://github.com/tree-sitter/tree-sitter/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

provides:
  - bin/tree-sitter

versions:
  github: tree-sitter/tree-sitter

build:
  dependencies:
    rust-lang.org: ^1.65
  script:
    - run: cargo install --root {{prefix}} --path cli
      if: <0.26
    - run: cargo install --root {{prefix}} --path crates/cli
      if: '>=0.26'

test:
  - tree-sitter init-config
  - tree-sitter dump-languages
