distributable:
  url: https://github.com/phiresky/ripgrep-all/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

provides:
  - bin/rga
  - bin/rga-fzf
  - bin/rga-fzf-open
  - bin/rga-preproc

companions:
  crates.io/ripgrep: '*'
  github.com/junegunn/fzf: '*'

versions:
  github: phiresky/ripgrep-all/tags

build:
  dependencies:
    rust-lang.org: '>=1.75'
    rust-lang.org/cargo: '*'
  script: cargo install --locked --path . --root {{prefix}}

test:
  - run: rga hello $FIXTURE
    fixture: hello, world
