distributable:
  url: https://github.com/ikanago/omekasy/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/omekasy

versions:
  github: ikanago/omekasy

build:
  dependencies:
    rust-lang.org: '>=1.65'
    rust-lang.org/cargo: '*'
  script:
    # missed version bump
    - sed -i '1,20s/^version = ".*"/version = "{{ version }}"/' Cargo.toml
    - cargo install --path . --root {{prefix}}

test:
  - omekasy --font bold-italic "My new gear..."
  - test "$(omekasy --version)" = "omekasy {{version}}"
