distributable:
  url: git+https://github.com/ceph/ceph.git
  ref: v{{version}}

display-name: cephadm

versions:
  github: ceph/ceph/tags

dependencies:
  openssl.org: ^1.1
  python.org: ^3

build:
  dependencies:
    python.org: ^3
    gnu.org/coreutils: '*'
  env:
    linux:
      TMPDIR: $(mktemp -d -p /tmp)
    BUILD_FLAGS:
      - --set-version-var CEPH_GIT_VER="$(git rev-parse HEAD)"
      - --set-version-var CEPH_GIT_NICE_VER="$(git describe)"
      - --set-version-var CEPH_RELEASE="$(sed -n '1p' ./src/ceph_release)"
      - --set-version-var CEPH_RELEASE_NAME="$(sed -n '2p' ./src/ceph_release)"
      - --set-version-var CEPH_RELEASE_TYPE="$(sed -n '3p' ./src/ceph_release)"
  script:
    - mkdir -p {{prefix}}/bin
    - run: ./build.sh $BUILD_FLAGS {{prefix}}/bin/cephadm
      working-directory: src/cephadm
    - run:
        # because this is a packed zip archive, and hardcodes the path to python3
        # we have to change the shebang to /usr/bin/env python3
        # and pad it with space to keep the length the same
        - shebang_length=$(head -n 1 {{prefix}}/bin/cephadm | wc -c)
        - new_shebang="#!/usr/bin/env python3"
        - padding_length=$((shebang_length - ${#new_shebang}))
        - |
          if [ $padding_length -lt 0 ]; then
            echo "Error: New shebang is too long!" >&2
            exit 1
          fi
        - padding=$(printf '%*s' "$padding_length" '')
        - sed -i "1s|^#!.*$|${new_shebang}${padding}|" cephadm
      working-directory: ${{prefix}}/bin

provides:
  - bin/cephadm

test: test "$(cephadm version|cut -d' ' -f3)" = {{version.tag}}
