distributable:
  url: https://github.com/bazelbuild/buildtools/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: bazelbuild/buildtools

build:
  dependencies:
    go.dev: '^1.19'
  script: |
    go mod download
    go build -ldflags "$LDFLAGS" -o {{prefix}}/bin/buildifier ./buildifier
    go build -ldflags "$LDFLAGS" -o {{prefix}}/bin/buildozer ./buildozer
    go build -ldflags "$LDFLAGS" -o {{prefix}}/bin/unused_deps ./unused_deps
  env:
    LDFLAGS:
      - -s
      - -w
      - -X main.buildVersion={{version}}
    linux:
      LDFLAGS:
        - -buildmode=pie

provides:
  - bin/buildifier
  - bin/buildozer
  - bin/unused_deps

test:
  script:
    - buildifier -version | grep {{version}}
    - buildozer -version | grep {{version}}
    - unused_deps -version | grep {{version}}
    # Buildifier: format a sample BUILD file and check output is formatted
    - echo 'cc_library(name = "foo",srcs=["foo.cc"])' > BUILD
    - buildifier BUILD
    - |
      diff -u <(echo 'cc_library(
          name = "foo",
          srcs = ["foo.cc"],
      )' ) BUILD
    # Buildozer: add a dependency to a rule in a sample BUILD file and check the result
    - buildozer 'add deps //base' //:foo
    - |
      diff -u <(echo 'cc_library(
          name = "foo",
          srcs = ["foo.cc"],
          deps = ["//base"],
      )' ) BUILD
