distributable:
  url: https://github.com/danvergara/dblab/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: danvergara/dblab

provides:
  - bin/dblab

build:
  dependencies:
    go.dev: ^1.21
  script:
    - go mod download
    - go build -v -trimpath -ldflags="$GO_LDFLAGS" -o "{{prefix}}/bin/dblab" .
  env:
    CGO_ENABLED: 0
    GO_LDFLAGS:
      - -s
      - -w
      - -X main.version={{version}}
    linux:
      # or segmentation fault
      # fix found here https://github.com/docker-library/golang/issues/402#issuecomment-982204575
      GO_LDFLAGS:
        - -buildmode=pie

test: dblab version | grep '{{version}}'
