import type { PkgxPackage } from '../types'
/**
 * acornioPackage information from pkgx.dev
 * Generated by tools/generatePackageData.ts
 */
export const acornioPackage: PkgxPackage = {
  "name": "acorn.io",
  "domain": "acorn.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx acorn.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}
