import type { PkgxPackage } from '../types'

/**
 * acornioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const acornioPackage: PkgxPackage = {
  name: "acorn.io",
  domain: "acorn.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx acorn.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface AcornioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "acorn.io";
  domain: "acorn.io";
  description: "Package information for acorn.io";
}
