import type { akuityioPackage } from '../types'

/**
 * akuityioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const akuityioPackage: akuityioPackage = {
  "name": "akuity.io",
  "domain": "akuity.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx akuity.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface akuityioPackage {
  name: "akuity.io";
  domain: "akuity.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx akuity.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
