import type { PkgxPackage } from '../types'

/**
 * alembicsqlalchemyorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const alembicsqlalchemyorgPackage: PkgxPackage = {
<<<<<<< Updated upstream
  "name": "alembic",
  "domain": "alembic.sqlalchemy.org",
  "description": "A database migrations tool for SQLAlchemy.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/alembic.sqlalchemy.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) alembic",
  "programs": [
    "alembic"
  ],
  "companions": [],
  "dependencies": [
    "pkgx.sh^1"
  ],
  "versions": [
=======
  name: "alembic",
  domain: "alembic.sqlalchemy.org",
  description: "A database migrations tool for SQLAlchemy.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/alembic.sqlalchemy.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) alembic",
  programs: ["alembic"],
  companions: [],
  dependencies: ["pkgx.sh^1"],
  versions: [
>>>>>>> Stashed changes
    "1.16.1",
    "1.16.0",
    "1.15.2",
    "1.15.1",
    "1.14.1",
    "1.14.0",
    "1.13.3",
    "1.13.2"
  ]
}

export interface AlembicsqlalchemyorgPackage {
  programs: readonly [];
  companions: readonly [];
<<<<<<< Updated upstream
  dependencies: readonly [
    "pkgx.sh^1"
  ];
  versions: readonly [
    "1.16.1",
    "1.16.0",
    "1.15.2",
    "1.15.1",
    "1.14.1",
    "1.14.0",
    "1.13.3",
    "1.13.2"
  ];
}
=======
  dependencies: readonly [];
  versions: readonly [];
  name: "alembicsqlalchemy.org";
  domain: "alembicsqlalchemy.org";
  description: "Package information for alembicsqlalchemy.org";
}
>>>>>>> Stashed changes
