import type { PkgxPackage } from '../types'

/**
 * alsa-projectorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const alsaprojectorgPackage: PkgxPackage = {
  "name": "alsa-project.org",
  "domain": "alsa-project.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx alsa-project.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "alsa-project.org"
}

export interface AlsaprojectorgPackage {
  name: "alsa-project.org";
  domain: "alsa-project.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx alsa-project.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "alsa-project.org";
}
