import type { PkgxPackage } from '../types'

/**
 * amprsPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const amprsPackage: PkgxPackage = {
  name: "amp",
  domain: "amp.rs",
  description: "A complete text editor for your terminal.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/amp.rs/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) amp",
  programs: ["amp"],
  companions: [],
  dependencies: [
    "zlib.net@1",
    "libgit2.org@1",
    "linuxopenssl.org@1.1",
    "openssl.org@1.1"
  ],
  versions: ["0.7.1"]
}

export interface AmprsPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "amprs";
  domain: "amprs";
  description: "Package information for amprs";
}
