import type { PkgxPackage } from '../types'

/**
 * anchorecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const anchorecomPackage: PkgxPackage = {
  name: "anchore.com",
  domain: "anchore.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx anchore.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface AnchorecomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "anchore.com";
  domain: "anchore.com";
  description: "Package information for anchore.com";
}