import type { PkgxPackage } from '../types'

/**
 * androidcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const androidcomPackage: PkgxPackage = {
  name: "android.com",
  domain: "android.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx android.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface AndroidcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "android.com";
  domain: "android.com";
  description: "Package information for android.com";
}
