import type { PkgxPackage } from '../types'

/**
 * ansiblecom-ansiblelintPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ansiblecomansiblelintPackage: PkgxPackage = {
  "name": "ansible-lint",
  "domain": "ansible.com/ansible-lint",
  "description": "ansible-lint checks playbooks for practices and behavior that could potentially be improved and can fix some of the most common ones for you",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/ansible.com/ansible-lint/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) ansible-lint",
  "programs": [
    "ansible-lint"
  ],
  "companions": [],
  "dependencies": [
    "pkgx.sh^1"
  ],
  "versions": [
    "25.4.0",
    "25.2.1",
    "25.2.0",
    "25.1.3",
    "25.1.2",
    "25.1.1",
    "25.1.0",
    "24.9.2",
    "24.9.1",
    "24.9.0",
    "24.7.0",
    "24.6.1",
    "24.6.0",
    "24.5.0",
    "24.2.3",
    "24.2.2",
    "24.12.2",
    "24.12.1",
    "24.12.0",
    "24.10.0"
  ]
}

export interface AnsiblecomansiblelintPackage {
  name: "ansible-lint";
  domain: "ansible.com/ansible-lint";
  description: "ansible-lint checks playbooks for practices and behavior that could potentially be improved and can fix some of the most common ones for you";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/ansible.com/ansible-lint/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) ansible-lint";
  programs: readonly [
    "ansible-lint"
  ];
  companions: readonly [];
  dependencies: readonly [
    "pkgx.sh^1"
  ];
  versions: readonly [
    "25.4.0",
    "25.2.1",
    "25.2.0",
    "25.1.3",
    "25.1.2",
    "25.1.1",
    "25.1.0",
    "24.9.2",
    "24.9.1",
    "24.9.0",
    "24.7.0",
    "24.6.1",
    "24.6.0",
    "24.5.0",
    "24.2.3",
    "24.2.2",
    "24.12.2",
    "24.12.1",
    "24.12.0",
    "24.10.0"
  ];
}
