import type { PkgxPackage } from '../types'

/**
 * aomediagooglesourcecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const aomediagooglesourcecomPackage: PkgxPackage = {
  "name": "aomedia.googlesource.com",
  "domain": "aomedia.googlesource.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx aomedia.googlesource.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "aomedia.googlesource.com"
}

export interface AomediagooglesourcecomPackage {
  name: "aomedia.googlesource.com";
  domain: "aomedia.googlesource.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx aomedia.googlesource.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "aomedia.googlesource.com";
}
