import type { aomediagooglesourcecomaomPackage } from '../types'

/**
 * aomediagooglesourcecomaomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const aomediagooglesourcecomaomPackage: aomediagooglesourcecomaomPackage = {
  "name": "aom",
  "domain": "aomedia.googlesource.com/aom",
  "description": "Codec library for encoding and decoding AV1 video streams",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/aomedia.googlesource.com/aom/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +aomedia.googlesource.com/aom -- $SHELL -i",
  "programs": [
    "aomenc",
    "aomdec"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "3.9.1",
    "3.9.0",
    "3.8.3",
    "3.8.2",
    "3.8.1",
    "3.8.0",
    "3.7.2",
    "3.7.1",
    "3.7.0",
    "3.6.1",
    "3.5.0",
    "3.12.1",
    "3.12.0",
    "3.11.0",
    "3.10.0"
  ]
}

export interface aomediagooglesourcecomaomPackage {
  name: "aom";
  domain: "aomedia.googlesource.com/aom";
  description: "Codec library for encoding and decoding AV1 video streams";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/aomedia.googlesource.com/aom/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +aomedia.googlesource.com/aom -- $SHELL -i";
  programs: readonly [
    "aomenc",
    "aomdec"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "3.9.1",
    "3.9.0",
    "3.8.3",
    "3.8.2",
    "3.8.1",
    "3.8.0",
    "3.7.2",
    "3.7.1",
    "3.7.0",
    "3.6.1",
    "3.5.0",
    "3.12.1",
    "3.12.0",
    "3.11.0",
    "3.10.0"
  ];
}
