import type { PkgxPackage } from '../types'

/**
 * apacheorgsubversionPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const apacheorgsubversionPackage: PkgxPackage = {
  "name": "svn",
  "domain": "apache.org/subversion",
  "description": "Version control system designed to be a better CVS",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/apache.org/subversion/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +apache.org/subversion -- $SHELL -i",
  "programs": [
    "svn",
    "svnadmin",
    "svnbench",
    "svndumpfilter",
    "svnfsfs",
    "svnlook",
    "svnmucc",
    "svnrdump",
    "svnserve",
    "svnsync",
    "svnversion"
  ],
  "companions": [],
  "dependencies": [
    "gnu.org/gettext^0.21",
    "lz4.org^1",
    "openssl.org^1.1",
    "github.com/JuliaStrings/utf8proc^2",
    "libexpat.github.io^2",
    "kerberos.org^1.20",
    "sqlite.org^3",
    "zlib.net^1.2",
    "apache.org/apr^1",
    "apache.org/apr-util^1"
  ],
  "versions": [
    "1.14.5",
    "1.14.4",
    "1.14.3",
    "1.14.2"
  ],
  "fullPath": "apache.org/subversion",
  "aliases": [
    "svn",
    "subversion"
  ]
}

export interface ApacheorgsubversionPackage {
  name: "svn";
  domain: "apache.org/subversion";
  description: "Version control system designed to be a better CVS";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apache.org/subversion/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +apache.org/subversion -- $SHELL -i";
  programs: readonly [
    "svn",
    "svnadmin",
    "svnbench",
    "svndumpfilter",
    "svnfsfs",
    "svnlook",
    "svnmucc",
    "svnrdump",
    "svnserve",
    "svnsync",
    "svnversion"
  ];
  companions: readonly [];
  dependencies: readonly [
    "gnu.org/gettext^0.21",
    "lz4.org^1",
    "openssl.org^1.1",
    "github.com/JuliaStrings/utf8proc^2",
    "libexpat.github.io^2",
    "kerberos.org^1.20",
    "sqlite.org^3",
    "zlib.net^1.2",
    "apache.org/apr^1",
    "apache.org/apr-util^1"
  ];
  versions: readonly [
    "1.14.5",
    "1.14.4",
    "1.14.3",
    "1.14.2"
  ];
  fullPath: "apache.org/subversion";
  aliases: readonly [
    "svn",
    "subversion"
  ];
}
