import type { apacheorgaprutilPackage } from '../types'

/**
 * apacheorgaprutilPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const apacheorgaprutilPackage: apacheorgaprutilPackage = {
  "name": "apu-{{ version.major }}-config",
  "domain": "apache.org/apr-util",
  "description": "Mirror of Apache Portable Runtime util",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/apache.org/apr-util/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) apu-{{ version.major }}-config",
  "programs": [
    "apu-{{ version.major }}-config"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "1.6.3"
  ]
}

export interface apacheorgaprutilPackage {
  name: "apu-{{ version.major }}-config";
  domain: "apache.org/apr-util";
  description: "Mirror of Apache Portable Runtime util";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apache.org/apr-util/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) apu-{{ version.major }}-config";
  programs: readonly [
    "apu-{{ version.major }}-config"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "1.6.3"
  ];
}
