import type { PkgxPackage } from '../types'

/**
 * apacheorgjmeterPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const apacheorgjmeterPackage: PkgxPackage = {
  name: "apache.org/jmeter",
  domain: "apache.org/jmeter",
  description: "",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apache.org/jmeter/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +apache.org/jmeter -- $SHELL -i",
  programs: [
    "jmeter",
    "jmeter-server",
    "mirror-server"
  ],
  companions: [],
  dependencies: ["openjdk.org"],
  versions: [
    "5.6.3",
    "5.6.2",
    "5.6.1"
  ]
}

export interface ApacheorgjmeterPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "apache.org/jmeter";
  domain: "apache.org/jmeter";
  description: "Package information for apache.org/jmeter";
}