import type { apollographqlcomPackage } from '../types'

/**
 * apollographqlcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const apollographqlcomPackage: apollographqlcomPackage = {
  "name": "apollographql.com",
  "domain": "apollographql.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx apollographql.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface apollographqlcomPackage {
  name: "apollographql.com";
  domain: "apollographql.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx apollographql.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
