import type { PkgxPackage } from '../types'

/**
 * appiumioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const appiumioPackage: PkgxPackage = {
  "name": "appium",
  "domain": "appium.io",
  "description": "Cross-platform automation framework for all kinds of apps, built on top of the W3C WebDriver protocol",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/appium.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) appium",
  "programs": [
    "appium"
  ],
  "companions": [],
  "dependencies": [
    "npmjs.com",
    "nodejs.org^10.13.0 || ^12 || ^14 || ^16 || ^18 || ^20",
    "openjdk.org"
  ],
  "versions": [
    "2.9.0",
    "2.8.0",
    "2.7.0",
    "2.6.0",
    "2.5.4",
    "2.5.3",
    "2.5.2",
    "2.5.1",
    "2.5.0",
    "2.4.1",
    "2.4.0",
    "2.3.0",
    "2.2.3",
    "2.18.0",
    "2.17.1",
    "2.17.0",
    "2.16.2",
    "2.16.1",
    "2.16.0",
    "2.15.0",
    "2.14.1",
    "2.14.0",
    "2.13.1",
    "2.13.0",
    "2.12.2",
    "2.12.1",
    "2.12.0",
    "2.11.5",
    "2.11.4",
    "2.11.3",
    "2.11.2",
    "2.11.1",
    "2.11.0",
    "2.10.3",
    "2.10.2",
    "2.10.1"
  ],
  "fullPath": "appium.io"
}
