import type { PkgxPackage } from '../types'

/**
 * applecom-remote_cmdsPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const applecomremote_cmdsPackage: PkgxPackage = {
  "name": "telnet",
  "domain": "apple.com/remote_cmds",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/apple.com/remote_cmds/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) telnet",
  "programs": [
    "telnet"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "306.0.0",
    "303.141.1",
    "303.0.2",
    "302.0.0",
    "294.0.0"
  ]
}

export interface Applecomremote_cmdsPackage {
  name: "telnet";
  domain: "apple.com/remote_cmds";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apple.com/remote_cmds/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) telnet";
  programs: readonly [
    "telnet"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "306.0.0",
    "303.141.1",
    "303.0.2",
    "302.0.0",
    "294.0.0"
  ];
}

export interface Applecomremote_cmdsPackage {
  name: "telnet";
  domain: "apple.com/remote_cmds";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apple.com/remote_cmds/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) telnet";
  programs: readonly [
    "telnet"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "306.0.0",
    "303.141.1",
    "303.0.2",
    "302.0.0",
    "294.0.0"
  ];
}

export interface Applecomremote_cmdsPackage {
  name: "telnet";
  domain: "apple.com/remote_cmds";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apple.com/remote_cmds/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) telnet";
  programs: readonly [
    "telnet"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "306.0.0",
    "303.141.1",
    "303.0.2",
    "302.0.0",
    "294.0.0"
  ];
}

export interface Applecomremote_cmdsPackage {
  name: "telnet";
  domain: "apple.com/remote_cmds";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apple.com/remote_cmds/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) telnet";
  programs: readonly [
    "telnet"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "306.0.0",
    "303.141.1",
    "303.0.2",
    "302.0.0",
    "294.0.0"
  ];
}

export interface Applecomremote_cmdsPackage {
  name: "telnet";
  domain: "apple.com/remote_cmds";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apple.com/remote_cmds/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) telnet";
  programs: readonly [
    "telnet"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "306.0.0",
    "303.141.1",
    "303.0.2",
    "302.0.0",
    "294.0.0"
  ];
}

export interface Applecomremote_cmdsPackage {
  name: "telnet";
  domain: "apple.com/remote_cmds";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/apple.com/remote_cmds/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) telnet";
  programs: readonly ["telnet"];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly ["306.0.0","303.141.1","303.0.2","302.0.0","294.0.0"];
  fullPath: "apple.com/remote_cmds";
}
