import type { arduinogithubioPackage } from '../types'

/**
 * arduinogithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const arduinogithubioPackage: arduinogithubioPackage = {
  "name": "arduino.github.io",
  "domain": "arduino.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx arduino.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface arduinogithubioPackage {
  name: "arduino.github.io";
  domain: "arduino.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx arduino.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
