import type { PkgxPackage } from '../types'

/**
 * arduinogithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const arduinogithubioPackage: PkgxPackage = {
  name: "arduino.github.io",
  domain: "arduino.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx arduino.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface ArduinogithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "arduinogithub.io";
  domain: "arduinogithub.io";
  description: "Package information for arduinogithub.io";
}
