import type { PkgxPackage } from '../types'

/**
 * arduinogithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const arduinogithubioPackage: PkgxPackage = {
  "name": "arduino.github.io",
  "domain": "arduino.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx arduino.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "arduino.github.io"
}
