import type { PkgxPackage } from '../types'

/**
 * asciinemaorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const asciinemaorgPackage: PkgxPackage = {
  "name": "asciinema",
  "domain": "asciinema.org",
  "description": "Record and share terminal sessions",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/asciinema.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) asciinema",
  "programs": [
    "asciinema"
  ],
  "companions": [],
  "dependencies": [
    "python.org^3.12"
  ],
  "versions": [
    "2.4.0"
  ]
}

export interface AsciinemaorgPackage {
  name: "asciinema";
  domain: "asciinema.org";
  description: "Record and share terminal sessions";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/asciinema.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) asciinema";
  programs: readonly [
    "asciinema"
  ];
  companions: readonly [];
  dependencies: readonly [
    "python.org^3.12"
  ];
  versions: readonly [
    "2.4.0"
  ];
}
