import type { PkgxPackage } from '../types'

/**
 * astralshPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const astralshPackage: PkgxPackage = {
  "name": "astral.sh",
  "domain": "astral.sh",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx astral.sh",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface AstralshPackage {
  name: "astral.sh";
  domain: "astral.sh";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx astral.sh";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
