import type { PkgxPackage } from '../types'

/**
 * attrsorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const attrsorgPackage: PkgxPackage = {
  name: "attrs.org",
  domain: "attrs.org",
  description: "Python Classes Without Boilerplate",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/attrs.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +attrs.org -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: ["python.org~3.11"],
  versions: [
    "25.3.0",
    "25.2.0",
    "25.1.0",
    "24.3.0",
    "24.2.0",
    "24.1.0",
    "23.2.0"
  ]
}

export interface AttrsorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "attrs.org";
  domain: "attrs.org";
  description: "Package information for attrs.org";
}
