import type { augeasnetPackage } from '../types'

/**
 * augeasnetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const augeasnetPackage: PkgxPackage = {
  "name": "augeas.net",
  "domain": "augeas.net",
  "description": "A configuration editing tool and API",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/augeas.net/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +augeas.net -- $SHELL -i",
  "programs": [
    "augmatch",
    "augparse",
    "augprint",
    "augtool",
    "fadot"
  ],
  "companions": [],
  "dependencies": [
    "gnu.org/readline",
    "gnome.org/libxml2"
  ],
  "versions": [
    "1.14.1",
    "1.14.0"
  ]
}

export interface AugeasnetPackage {
  name: "augeas.net";
  domain: "augeas.net";
  description: "A configuration editing tool and API";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/augeas.net/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +augeas.net -- $SHELL -i";
  programs: readonly [
    "augmatch",
    "augparse",
    "augprint",
    "augtool",
    "fadot"
  ];
  companions: readonly [];
  dependencies: readonly [
    "gnu.org/readline",
    "gnome.org/libxml2"
  ];
  versions: readonly [
    "1.14.1",
    "1.14.0"
  ];
}
