import type { PkgxPackage } from '../types'

/**
 * authzedcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const authzedcomPackage: PkgxPackage = {
  "name": "authzed.com",
  "domain": "authzed.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx authzed.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface AuthzedcomPackage {
  name: "authzed.com";
  domain: "authzed.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx authzed.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
