import type { PkgxPackage } from '../types'

/**
 * authzedcomspicedbPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const authzedcomspicedbPackage: PkgxPackage = {
  name: "spicedb",
  domain: "authzed.com/spicedb",
  description: "Open Source, Google Zanzibar-inspired database for scalably storing and querying fine-grained authorization data",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/authzed.com/spicedb/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) spicedb",
  programs: ["spicedb"],
  companions: [],
  dependencies: [],
  versions: [
    "1.44.0",
    "1.43.0",
    "1.42.1",
    "1.42.0",
    "1.41.0",
    "1.40.1",
    "1.40.0",
    "1.39.1",
    "1.39.0",
    "1.38.1",
    "1.38.0",
    "1.37.2",
    "1.37.1",
    "1.37.0",
    "1.36.2",
    "1.36.1",
    "1.36.0",
    "1.35.3",
    "1.35.2",
    "1.35.1",
    "1.35.0",
    "1.34.0"
  ]
}

export interface AuthzedcomspicedbPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "authzed.com/spicedb";
  domain: "authzed.com/spicedb";
  description: "Package information for authzed.com/spicedb";
}
