import type { PkgxPackage } from '../types'

/**
 * aux4ioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const aux4ioPackage: PkgxPackage = {
  name: "aux4",
  domain: "aux4.io",
  description: "elevate your imagination",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/aux4.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) aux4",
  programs: ["aux4"],
  companions: [],
  dependencies: [],
  versions: [
    "5.0.14",
    "5.0.11",
    "5.0.10",
    "5.0.9",
    "5.0.8",
    "5.0.3"
  ]
}

export interface Aux4ioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "aux4.io";
  domain: "aux4.io";
  description: "Package information for aux4.io";
}