import type { PkgxPackage } from '../types'

/**
 * beyondgrepcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const beyondgrepcomPackage: PkgxPackage = {
  "name": "ack",
  "domain": "beyondgrep.com",
  "description": "ack is a grep-like search tool optimized for source code.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/beyondgrep.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) ack",
  "programs": [
    "ack"
  ],
  "companions": [],
  "dependencies": [
    "perl.org"
  ],
  "versions": [
    "3.8.1",
    "3.8.0",
    "3.7.0",
    "3.6.0"
  ]
}

export interface BeyondgrepcomPackage {
  name: "ack";
  domain: "beyondgrep.com";
  description: "ack is a grep-like search tool optimized for source code.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/beyondgrep.com/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) ack";
  programs: readonly [
    "ack"
  ];
  companions: readonly [];
  dependencies: readonly [
    "perl.org"
  ];
  versions: readonly [
    "3.8.1",
    "3.8.0",
    "3.7.0",
    "3.6.0"
  ];
}
