import type { biomejsdevPackage } from '../types'

/**
 * biomejsdevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const biomejsdevPackage: biomejsdevPackage = {
  "name": "biome",
  "domain": "biomejs.dev",
  "description": "A toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter, usable via CLI and LSP.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/biomejs.dev/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) biome",
  "programs": [
    "biome"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "1.9.4",
    "1.9.3",
    "1.9.2",
    "1.9.1",
    "1.9.0",
    "1.8.3",
    "1.8.2",
    "1.8.1",
    "1.8.0",
    "1.7.3",
    "1.7.2",
    "1.7.1",
    "1.7.0",
    "1.6.4",
    "1.6.3",
    "1.6.2",
    "1.6.1",
    "1.6.0",
    "1.5.3",
    "1.5.2",
    "1.5.1",
    "1.5.0",
    "1.4.1",
    "1.4.0",
    "1.3.3",
    "1.3.1",
    "1.3.0",
    "1.2.2"
  ]
}

export interface biomejsdevPackage {
  name: "biome";
  domain: "biomejs.dev";
  description: "A toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter, usable via CLI and LSP.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/biomejs.dev/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) biome";
  programs: readonly [
    "biome"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "1.9.4",
    "1.9.3",
    "1.9.2",
    "1.9.1",
    "1.9.0",
    "1.8.3",
    "1.8.2",
    "1.8.1",
    "1.8.0",
    "1.7.3",
    "1.7.2",
    "1.7.1",
    "1.7.0",
    "1.6.4",
    "1.6.3",
    "1.6.2",
    "1.6.1",
    "1.6.0",
    "1.5.3",
    "1.5.2",
    "1.5.1",
    "1.5.0",
    "1.4.1",
    "1.4.0",
    "1.3.3",
    "1.3.1",
    "1.3.0",
    "1.2.2"
  ];
}
