export const biomejsdevPackage = {
  name: 'biome' as const,
  domain: 'biomejs.dev' as const,
  description: 'A toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter, usable via CLI and LSP.' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/biomejs.dev/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) biome' as const,
  programs: [
    'biome',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '1.9.4',
    '1.9.3',
    '1.9.2',
    '1.9.1',
    '1.9.0',
    '1.8.3',
    '1.8.2',
    '1.8.1',
    '1.8.0',
    '1.7.3',
    '1.7.2',
    '1.7.1',
    '1.7.0',
    '1.6.4',
    '1.6.3',
    '1.6.2',
    '1.6.1',
    '1.6.0',
    '1.5.3',
    '1.5.2',
    '1.5.1',
    '1.5.0',
    '1.4.1',
    '1.4.0',
    '1.3.3',
    '1.3.1',
    '1.3.0',
    '1.2.2',
  ] as const,
  fullPath: 'biomejs.dev' as const,
}

export type BiomejsdevPackage = typeof biomejsdevPackage
