import type { bitcoinorgPackage } from '../types'

/**
 * bitcoinorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const bitcoinorgPackage: PkgxPackage = {
  "name": "bitcoin",
  "domain": "bitcoin.org",
  "description": "Decentralized, peer to peer payment network",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/bitcoin.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +bitcoin.org -- $SHELL -i",
  "programs": [
    "bitcoin-cli",
    "bitcoin-tx",
    "bitcoin-util",
    "bitcoin-wallet",
    "bitcoind"
  ],
  "companions": [],
  "dependencies": [
    "oracle.com/berkeley-db^18",
    "boost.org^1",
    "libevent.org^2",
    "zeromq.org^4",
    "sqlite.org^3",
    "linuxgnu.org/gcc/libstdcxx",
    "gnu.org/gcc/libstdcxx"
  ],
  "versions": [
    "29.0.0",
    "28.1.0",
    "28.0.0",
    "27.2.0",
    "27.1.0",
    "27.0.0",
    "26.2.0",
    "26.1.0",
    "26.0.0",
    "25.2.0",
    "25.1.0",
    "25.0.0",
    "24.2.0",
    "24.1.0",
    "24.0.1",
    "23.2.0"
  ]
}

export interface BitcoinorgPackage {
  name: "bitcoin";
  domain: "bitcoin.org";
  description: "Decentralized, peer to peer payment network";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/bitcoin.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +bitcoin.org -- $SHELL -i";
  programs: readonly [
    "bitcoin-cli",
    "bitcoin-tx",
    "bitcoin-util",
    "bitcoin-wallet",
    "bitcoind"
  ];
  companions: readonly [];
  dependencies: readonly [
    "oracle.com/berkeley-db^18",
    "boost.org^1",
    "libevent.org^2",
    "zeromq.org^4",
    "sqlite.org^3",
    "linuxgnu.org/gcc/libstdcxx",
    "gnu.org/gcc/libstdcxx"
  ];
  versions: readonly [
    "29.0.0",
    "28.1.0",
    "28.0.0",
    "27.2.0",
    "27.1.0",
    "27.0.0",
    "26.2.0",
    "26.1.0",
    "26.0.0",
    "25.2.0",
    "25.1.0",
    "25.0.0",
    "24.2.0",
    "24.1.0",
    "24.0.1",
    "23.2.0"
  ];
}
