import type { bitwardencomPackage } from '../types'

/**
 * bitwardencomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const bitwardencomPackage: bitwardencomPackage = {
  "name": "bw",
  "domain": "bitwarden.com",
  "description": "Secure and free password manager for all of your devices",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/bitwarden.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) bw",
  "programs": [
    "bw"
  ],
  "companions": [],
  "dependencies": [
    "nodejs.org^20"
  ],
  "versions": [
    "2025.4.0",
    "2025.3.0",
    "2025.2.0",
    "2025.1.3",
    "2025.1.2",
    "2025.1.1",
    "2025.1.0",
    "2024.9.0",
    "2024.8.2",
    "2024.8.1",
    "2024.7.2",
    "2024.7.1",
    "2024.6.1",
    "2024.6.0",
    "2024.4.1",
    "2024.4.0",
    "2024.3.1",
    "2024.2.1",
    "2024.2.0",
    "2024.12.0",
    "2024.11.1",
    "2024.11.0",
    "2024.10.0",
    "1.22.1"
  ]
}

export interface bitwardencomPackage {
  name: "bw";
  domain: "bitwarden.com";
  description: "Secure and free password manager for all of your devices";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/bitwarden.com/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) bw";
  programs: readonly [
    "bw"
  ];
  companions: readonly [];
  dependencies: readonly [
    "nodejs.org^20"
  ];
  versions: readonly [
    "2025.4.0",
    "2025.3.0",
    "2025.2.0",
    "2025.1.3",
    "2025.1.2",
    "2025.1.1",
    "2025.1.0",
    "2024.9.0",
    "2024.8.2",
    "2024.8.1",
    "2024.7.2",
    "2024.7.1",
    "2024.6.1",
    "2024.6.0",
    "2024.4.1",
    "2024.4.0",
    "2024.3.1",
    "2024.2.1",
    "2024.2.0",
    "2024.12.0",
    "2024.11.1",
    "2024.11.0",
    "2024.10.0",
    "1.22.1"
  ];
}
