import type { blake2netPackage } from '../types'

/**
 * blake2netPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const blake2netPackage: PkgxPackage = {
  "name": "blake2.net",
  "domain": "blake2.net",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx blake2.net",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface Blake2netPackage {
  name: "blake2.net";
  domain: "blake2.net";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx blake2.net";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
