import type { PkgxPackage } from '../types'

/**
 * bloomreachcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const bloomreachcomPackage: PkgxPackage = {
  name: "bloomreach.com",
  domain: "bloomreach.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx bloomreach.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface BloomreachcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "bloomreach.com";
  domain: "bloomreach.com";
  description: "Package information for bloomreach.com";
}
