import type { bloomreachcomPackage } from '../types'

/**
 * bloomreachcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const bloomreachcomPackage: bloomreachcomPackage = {
  "name": "bloomreach.com",
  "domain": "bloomreach.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx bloomreach.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface bloomreachcomPackage {
  name: "bloomreach.com";
  domain: "bloomreach.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx bloomreach.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
