import type { PkgxPackage } from '../types'

/**
 * breakfastquaycomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const breakfastquaycomPackage: PkgxPackage = {
  "name": "breakfastquay.com",
  "domain": "breakfastquay.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx breakfastquay.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "breakfastquay.com"
}

export interface BreakfastquaycomPackage {
  name: "breakfastquay.com";
  domain: "breakfastquay.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx breakfastquay.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "breakfastquay.com";
}
