import type { PkgxPackage } from '../types'

/**
 * brxken128githubiodexiosPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const brxken128githubiodexiosPackage: PkgxPackage = {
  name: "dexios",
  domain: "brxken128.github.io/dexios",
  description: "A secure file encryption utility, written in Rust.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/brxken128.github.io/dexios/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) dexios",
  programs: ["dexios"],
  companions: [],
  dependencies: [],
  versions: ["8.8.1"]
}

export interface Brxken128githubiodexiosPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "brxken128github.io/dexios";
  domain: "brxken128github.io/dexios";
  description: "Package information for brxken128github.io/dexios";
}