import type { PkgxPackage } from '../types'

/**
 * brxken128githubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const brxken128githubioPackage: PkgxPackage = {
  name: "brxken128.github.io",
  domain: "brxken128.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx brxken128.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface Brxken128githubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "brxken128github.io";
  domain: "brxken128github.io";
  description: "Package information for brxken128github.io";
}
