import type { budimanjojogithubioPackage } from '../types'

/**
 * budimanjojogithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const budimanjojogithubioPackage: budimanjojogithubioPackage = {
  "name": "budimanjojo.github.io",
  "domain": "budimanjojo.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx budimanjojo.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface budimanjojogithubioPackage {
  name: "budimanjojo.github.io";
  domain: "budimanjojo.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx budimanjojo.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
