import type { PkgxPackage } from '../types'

/**
 * budimanjojogithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const budimanjojogithubioPackage: PkgxPackage = {
  name: "budimanjojo.github.io",
  domain: "budimanjojo.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx budimanjojo.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface BudimanjojogithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "budimanjojogithub.io";
  domain: "budimanjojogithub.io";
  description: "Package information for budimanjojogithub.io";
}
