import type { PkgxPackage } from '../types'

/**
 * bunshPackage information from pkgx.dev
 * Generated by tools/generatePackageData.ts
 */
export const bunshPackage: PkgxPackage = {
  "name": "bun",
  "domain": "bun.sh",
  "description": "",
  "packageYmlUrl": "https://raw.githubusercontent.com/pkgxdev/pantry/main/projects/bun.sh/package.yml",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx bun",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}
