import type { PkgxPackage } from '../types'

/**
 * catborgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const catborgPackage: PkgxPackage = {
  name: "catb.org",
  domain: "catb.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx catb.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface CatborgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "catb.org";
  domain: "catb.org";
  description: "Package information for catb.org";
}