import type { PkgxPackage } from '../types'

/**
 * catborgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const catborgPackage: PkgxPackage = {
  "name": "catb.org",
  "domain": "catb.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx catb.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "catb.org"
}

export interface CatborgPackage {
  name: "catb.org";
  domain: "catb.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx catb.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "catb.org";
}
