export const cedarpolicycomcliPackage = {
  name: "cedar" as const,
  domain: "cedarpolicy.com/cli" as const,
  description: "Implementation of the Cedar Policy Language" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/cedarpolicy.com/cli/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) cedar" as const,
  programs: [
    "cedar",
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    "4.4.1",
    "4.4.0",
    "4.3.3",
    "4.3.2",
    "4.3.1",
    "4.3.0",
    "4.2.2",
    "4.2.1",
    "4.2.0",
    "4.1.0",
    "4.0.0",
    "3.4.1",
    "3.4.0",
    "3.3.0",
    "3.2.4",
    "3.2.1",
    "3.2.0",
    "3.1.4",
    "3.1.3",
    "3.1.2",
    "3.1.1",
    "3.1.0",
    "3.0.1",
    "3.0.0",
    "2.5.0",
    "2.4.7",
    "2.4.6",
    "2.4.5",
    "2.4.4",
    "2.4.3",
    "2.4.2",
    "2.4.1",
    "2.4.0",
    "2.3.3",
  ] as const,
  fullPath: "cedarpolicy.com/cli" as const,
  aliases: [
    "cli",
  ] as const,
}

export type CedarpolicycomcliPackage = typeof cedarpolicycomcliPackage
