import type { PkgxPackage } from '../types'

/**
 * cephcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cephcomPackage: PkgxPackage = {
  name: "ceph.com",
  domain: "ceph.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx ceph.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface CephcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "ceph.com";
  domain: "ceph.com";
  description: "Package information for ceph.com";
}
