import type { PkgxPackage } from '../types'

/**
 * ceressolverorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ceressolverorgPackage: PkgxPackage = {
  name: "ceres-solver.org",
  domain: "ceres-solver.org",
  description: "",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/ceres-solver.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +ceres-solver.org -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: [
    "eigen.tuxfamily.org",
    "gflags.github.io",
    "google.com/glog",
    "glaros.dtc.umn.edu/metis",
    "netlib.org/lapack",
    "people.engr.tamu.edu/davis/suitesparse",
    "github.com/oneapi-src/oneTBB"
  ],
  versions: [
    "2.2.0",
    "2.1.0"
  ]
}

export interface CeressolverorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "ceres/solverorg";
  domain: "ceres/solverorg";
  description: "Package information for ceres/solverorg";
}