import type { PkgxPackage } from '../types'

/**
 * certifiioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const certifiioPackage: PkgxPackage = {
  name: "certifi.io",
  domain: "certifi.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx certifi.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface CertifiioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "certifi.io";
  domain: "certifi.io";
  description: "Package information for certifi.io";
}
