import type { PkgxPackage } from '../types'

/**
 * cgalorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cgalorgPackage: PkgxPackage = {
  name: "cgal",
  domain: "cgal.org",
  description: "The public CGAL repository, see the README below",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/cgal.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +cgal.org -- $SHELL -i",
  programs: [
    "cgal_create_CMakeLists",
    "cgal_create_cmake_script",
    "cgal_make_macosx_app"
  ],
  companions: [],
  dependencies: [
    "boost.org",
    "eigen.tuxfamily.org",
    "gnu.org/gmp",
    "gnu.org/mpfr",
    "openssl.org"
  ],
  versions: [
    "6.0.1",
    "6.0.0",
    "5.6.2",
    "5.6.1",
    "5.6.0"
  ]
}

export interface CgalorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "cgal.org";
  domain: "cgal.org";
  description: "Package information for cgal.org";
}
