import type { PkgxPackage } from '../types'

/**
 * charmshPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const charmshPackage: PkgxPackage = {
  name: "charm.sh",
  domain: "charm.sh",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx charm.sh",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface CharmshPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "charm.sh";
  domain: "charm.sh";
  description: "Package information for charm.sh";
}
