import type { charmshPackage } from '../types'

/**
 * charmshPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const charmshPackage: charmshPackage = {
  "name": "charm.sh",
  "domain": "charm.sh",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx charm.sh",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface charmshPackage {
  name: "charm.sh";
  domain: "charm.sh";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx charm.sh";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
