import type { PkgxPackage } from '../types'

/**
 * chromedriverchromiumorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const chromedriverchromiumorgPackage: PkgxPackage = {
  name: "chromedriver",
  domain: "chromedriver.chromium.org",
  description: "",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/chromedriver.chromium.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) chromedriver",
  programs: ["chromedriver"],
  companions: [],
  dependencies: [
    "linuxgnome.org/glib^2mozilla.org/nssx.org/xcb",
    "gnome.org/glib^2",
    "mozilla.org/nss",
    "x.org/xcb"
  ],
  versions: ["114.0.5735.90"]
}

export interface ChromedriverchromiumorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "chromedriverchromium.org";
  domain: "chromedriverchromium.org";
  description: "Package information for chromedriverchromium.org";
}
