import type { PkgxPackage } from '../types'

/**
 * ciliumioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ciliumioPackage: PkgxPackage = {
  name: "cilium.io",
  domain: "cilium.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx cilium.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface CiliumioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "cilium.io";
  domain: "cilium.io";
  description: "Package information for cilium.io";
}