import type { ciliumioPackage } from '../types'

/**
 * ciliumioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ciliumioPackage: ciliumioPackage = {
  "name": "cilium.io",
  "domain": "cilium.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx cilium.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface ciliumioPackage {
  name: "cilium.io";
  domain: "cilium.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx cilium.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
