import type { PkgxPackage } from '../types'

/**
 * clogtoolgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const clogtoolgithubioPackage: PkgxPackage = {
  name: "clog",
  domain: "clog-tool.github.io",
  description: "Colorized pattern-matching log tail utility",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/clog-tool.github.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) clog",
  programs: ["clog"],
  companions: [],
  dependencies: [],
  versions: ["0.9.3"]
}

export interface ClogtoolgithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "clog/toolgithubio";
  domain: "clog/toolgithubio";
  description: "Package information for clog/toolgithubio";
}