import type { cloudflarecomPackage } from '../types'

/**
 * cloudflarecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cloudflarecomPackage: PkgxPackage = {
  "name": "cloudflare.com",
  "domain": "cloudflare.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx cloudflare.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface CloudflarecomPackage {
  name: "cloudflare.com";
  domain: "cloudflare.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx cloudflare.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
