import type { PkgxPackage } from '../types'

/**
 * cloudfoundryorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cloudfoundryorgPackage: PkgxPackage = {
  name: "cloudfoundry.org",
  domain: "cloudfoundry.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx cloudfoundry.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface CloudfoundryorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "cloudfoundry.org";
  domain: "cloudfoundry.org";
  description: "Package information for cloudfoundry.org";
}
