import type { PkgxPackage } from '../types'

/**
 * cloudfoundryorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cloudfoundryorgPackage: PkgxPackage = {
  "name": "cloudfoundry.org",
  "domain": "cloudfoundry.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx cloudfoundry.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "cloudfoundry.org"
}
