import type { PkgxPackage } from '../types'

/**
 * cmockaorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cmockaorgPackage: PkgxPackage = {
  name: "cmocka.org",
  domain: "cmocka.org",
  description: "",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/cmocka.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +cmocka.org -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: [],
  versions: ["1.1.7"]
}

export interface CmockaorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "cmocka.org";
  domain: "cmocka.org";
  description: "Package information for cmocka.org";
}
