import type { PkgxPackage } from '../types'

/**
 * cocogittoioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cocogittoioPackage: PkgxPackage = {
  name: "cog",
  domain: "cocogitto.io",
  description: "The Conventional Commits toolbox",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/cocogitto.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) cog",
  programs: ["cog"],
  companions: [],
  dependencies: ["libgit2.org~1.7"],
  versions: [
    "6.3.0",
    "6.2.0",
    "6.1.0",
    "6.0.1",
    "6.0.0",
    "5.6.0",
    "5.5.0"
  ]
}

export interface CocogittoioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "cocogitto.io";
  domain: "cocogitto.io";
  description: "Package information for cocogitto.io";
}
