export const conftestdevPackage = {
  name: "conftest" as const,
  domain: "conftest.dev" as const,
  description: "Write tests against structured configuration data using the Open Policy Agent Rego query language" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/conftest.dev/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) conftest" as const,
  programs: [
    "conftest",
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    "0.60.0",
    "0.59.0",
    "0.58.0",
    "0.57.0",
    "0.56.0",
    "0.55.0",
    "0.54.0",
    "0.53.0",
    "0.52.0",
    "0.51.0",
    "0.50.0",
    "0.49.1",
    "0.49.0",
    "0.48.0",
    "0.47.0",
    "0.46.0",
  ] as const,
  fullPath: "conftest.dev" as const,
}

export type ConftestdevPackage = typeof conftestdevPackage
