import type { PkgxPackage } from '../types'

/**
 * cratesioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cratesioPackage: PkgxPackage = {
  "name": "crates.io",
  "domain": "crates.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx crates.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "crates.io"
}
