import type { crazymaxdevPackage } from '../types'

/**
 * crazymaxdevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const crazymaxdevPackage: PkgxPackage = {
  "name": "crazymax.dev",
  "domain": "crazymax.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx crazymax.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface CrazymaxdevPackage {
  name: "crazymax.dev";
  domain: "crazymax.dev";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx crazymax.dev";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
