import type { PkgxPackage } from '../types'

/**
 * creativeprojectsgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const creativeprojectsgithubioPackage: PkgxPackage = {
  "name": "creativeprojects.github.io",
  "domain": "creativeprojects.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx creativeprojects.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "creativeprojects.github.io"
}

export interface CreativeprojectsgithubioPackage {
  name: "creativeprojects.github.io";
  domain: "creativeprojects.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx creativeprojects.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "creativeprojects.github.io";
}
