import type { cryptoPackage } from '../types'

/**
 * cryptoPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cryptoPackage: cryptoPackage = {
  "name": "cr.yp.to",
  "domain": "cr.yp.to",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx cr.yp.to",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface cryptoPackage {
  name: "cr.yp.to";
  domain: "cr.yp.to";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx cr.yp.to";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
