import type { PkgxPackage } from '../types'

/**
 * csientuedutwPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const csientuedutwPackage: PkgxPackage = {
  name: "csie.ntu.edu.tw",
  domain: "csie.ntu.edu.tw",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx csie.ntu.edu.tw",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface CsientuedutwPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "csientuedutw";
  domain: "csientuedutw";
  description: "Package information for csientuedutw";
}