import type { PkgxPackage } from '../types'

/**
 * csientuedutwPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const csientuedutwPackage: PkgxPackage = {
  "name": "csie.ntu.edu.tw",
  "domain": "csie.ntu.edu.tw",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx csie.ntu.edu.tw",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "csie.ntu.edu.tw"
}
