export const cuelangorgPackage = {
  name: 'cue' as const,
  domain: 'cuelang.org' as const,
  description: 'The home of the CUE language! Validate and define text-based and dynamic configuration' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/cuelang.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) cue' as const,
  programs: [
    'cue',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '0.13.0',
    '0.12.1',
    '0.12.0',
    '0.11.2',
    '0.11.1',
    '0.11.0',
    '0.10.1',
    '0.10.0',
    '0.9.2',
    '0.9.1',
    '0.9.0',
    '0.8.2',
    '0.8.1',
    '0.8.0',
    '0.7.1',
    '0.7.0',
    '0.6.0',
    '0.5.0',
    '0.4.3',
  ] as const,
  fullPath: 'cuelang.org' as const,
}

export type CuelangorgPackage = typeof cuelangorgPackage
