import type { curlsePackage } from '../types'

/**
 * curlsePackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const curlsePackage: curlsePackage = {
  "name": "cURL",
  "domain": "curl.se",
  "description": "A command line tool and library for transferring data with URL syntax, supporting DICT, FILE, FTP, FTPS, GOPHER, GOPHERS, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, MQTT, POP3, POP3S, RTMP, RTMPS, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET, TFTP, WS and WSS. libcurl offers a myriad of powerful features",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/curl.se/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +curl.se -- $SHELL -i",
  "programs": [
    "curl",
    "curl-config"
  ],
  "companions": [],
  "dependencies": [
    "openssl.org^1.1",
    "curl.se/ca-certs",
    "zlib.net^1.2.11"
  ],
  "versions": [
    "8.9.1",
    "8.9.0",
    "8.8.0",
    "8.7.1",
    "8.6.0",
    "8.5.0",
    "8.4.0",
    "8.3.0",
    "8.2.1",
    "8.2.0",
    "8.13.0",
    "8.12.1",
    "8.12.0",
    "8.11.1",
    "8.11.0",
    "8.10.1",
    "8.10.0",
    "8.1.2",
    "8.1.0",
    "8.0.1",
    "8.0.0",
    "7.86.0",
    "7.85.0"
  ]
}

export interface curlsePackage {
  name: "cURL";
  domain: "curl.se";
  description: "A command line tool and library for transferring data with URL syntax, supporting DICT, FILE, FTP, FTPS, GOPHER, GOPHERS, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, MQTT, POP3, POP3S, RTMP, RTMPS, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET, TFTP, WS and WSS. libcurl offers a myriad of powerful features";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/curl.se/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +curl.se -- $SHELL -i";
  programs: readonly [
    "curl",
    "curl-config"
  ];
  companions: readonly [];
  dependencies: readonly [
    "openssl.org^1.1",
    "curl.se/ca-certs",
    "zlib.net^1.2.11"
  ];
  versions: readonly [
    "8.9.1",
    "8.9.0",
    "8.8.0",
    "8.7.1",
    "8.6.0",
    "8.5.0",
    "8.4.0",
    "8.3.0",
    "8.2.1",
    "8.2.0",
    "8.13.0",
    "8.12.1",
    "8.12.0",
    "8.11.1",
    "8.11.0",
    "8.10.1",
    "8.10.0",
    "8.1.2",
    "8.1.0",
    "8.0.1",
    "8.0.0",
    "7.86.0",
    "7.85.0"
  ];
}
