import type { cyrusimaporgPackage } from '../types'

/**
 * cyrusimaporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const cyrusimaporgPackage: cyrusimaporgPackage = {
  "name": "cyrusimap.org",
  "domain": "cyrusimap.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx cyrusimap.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface cyrusimaporgPackage {
  name: "cyrusimap.org";
  domain: "cyrusimap.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx cyrusimap.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
