import type { PkgxPackage } from '../types'

/**
 * darwinsyscomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const darwinsyscomPackage: PkgxPackage = {
  "name": "darwinsys.com",
  "domain": "darwinsys.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx darwinsys.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "darwinsys.com"
}

export interface DarwinsyscomPackage {
  name: "darwinsys.com";
  domain: "darwinsys.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx darwinsys.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "darwinsys.com";
}
