import type { PkgxPackage } from '../types'

/**
 * denilsonsanombrPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const denilsonsanombrPackage: PkgxPackage = {
  name: "denilson.sa.nom.br",
  domain: "denilson.sa.nom.br",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx denilson.sa.nom.br",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface DenilsonsanombrPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "denilsonsanombr";
  domain: "denilsonsanombr";
  description: "Package information for denilsonsanombr";
}