import type { PkgxPackage } from '../types'

/**
 * denolandPackage information from pkgx.dev
 * Generated by tools/generatePackageData.ts
 */
export const denolandPackage: PkgxPackage = {
  "name": "deno",
  "domain": "deno.land",
  "description": "",
  "packageYmlUrl": "https://raw.githubusercontent.com/pkgxdev/pantry/main/projects/deno.land/package.yml",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx deno",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}
