import type { PkgxPackage } from '../types'

/**
 * developer1passwordcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const developer1passwordcomPackage: PkgxPackage = {
  "name": "developer.1password.com",
  "domain": "developer.1password.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx developer.1password.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "developer.1password.com"
}
