import type { devyorhelnlPackage } from '../types'

/**
 * devyorhelnlPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const devyorhelnlPackage: devyorhelnlPackage = {
  "name": "dev.yorhel.nl",
  "domain": "dev.yorhel.nl",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx dev.yorhel.nl",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface devyorhelnlPackage {
  name: "dev.yorhel.nl";
  domain: "dev.yorhel.nl";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx dev.yorhel.nl";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
