import type { PkgxPackage } from '../types'

/**
 * devyorhelnlPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const devyorhelnlPackage: PkgxPackage = {
  "name": "dev.yorhel.nl",
  "domain": "dev.yorhel.nl",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx dev.yorhel.nl",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "dev.yorhel.nl"
}
