import type { PkgxPackage } from '../types'

/**
 * dgraphioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const dgraphioPackage: PkgxPackage = {
  name: "dgraph",
  domain: "dgraph.io",
  description: "high-performance graph database for real-time use cases",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/dgraph.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) dgraph",
  programs: ["dgraph"],
  companions: [],
  dependencies: [],
  versions: [
    "24.1.2",
    "24.1.1",
    "24.1.0",
    "24.0.5",
    "24.0.4",
    "24.0.2",
    "24.0.1",
    "24.0.0",
    "23.1.1",
    "23.1.0"
  ]
}

export interface DgraphioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "dgraph.io";
  domain: "dgraph.io";
  description: "Package information for dgraph.io";
}