import type { PkgxPackage } from '../types'

/**
 * dhruvkbdevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const dhruvkbdevPackage: PkgxPackage = {
  "name": "dhruvkb.dev",
  "domain": "dhruvkb.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx dhruvkb.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "dhruvkb.dev"
}
