import type { dhruvkbdevPackage } from '../types'

/**
 * dhruvkbdevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const dhruvkbdevPackage: PkgxPackage = {
  "name": "dhruvkb.dev",
  "domain": "dhruvkb.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx dhruvkb.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface DhruvkbdevPackage {
  name: "dhruvkb.dev";
  domain: "dhruvkb.dev";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx dhruvkb.dev";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
