import type { PkgxPackage } from '../types'

/**
 * digiporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const digiporgPackage: PkgxPackage = {
  "name": "digip.org",
  "domain": "digip.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx digip.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface DigiporgPackage {
  name: "digip.org";
  domain: "digip.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx digip.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
