import type { PkgxPackage } from '../types'

/**
 * dkrzdePackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const dkrzdePackage: PkgxPackage = {
  name: "dkrz.de",
  domain: "dkrz.de",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx dkrz.de",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface DkrzdePackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "dkrzde";
  domain: "dkrzde";
  description: "Package information for dkrzde";
}
