import type { PkgxPackage } from '../types'

/**
 * dockercomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const dockercomPackage: PkgxPackage = {
  "name": "docker.com",
  "domain": "docker.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx docker.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "docker.com"
}

export interface DockercomPackage {
  name: "docker.com";
  domain: "docker.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx docker.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "docker.com";
}
