import type { PkgxPackage } from '../types'

/**
 * docutilsorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const docutilsorgPackage: PkgxPackage = {
  name: "docutils.org",
  domain: "docutils.org",
  description: "Text processing system for reStructuredText",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/docutils.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +docutils.org -- $SHELL -i",
  programs: [
    "docutils",
    "rst2html",
    "rst2html4",
    "rst2html5",
    "rst2latex",
    "rst2man",
    "rst2odt",
    "rst2pseudoxml",
    "rst2s5",
    "rst2xetex",
    "rst2xml"
  ],
  companions: [],
  dependencies: ["pkgx.sh^1"],
  versions: [
    "0.21.2",
    "0.21.1",
    "0.21.0",
    "0.20.1",
    "0.20.0",
    "0.19.0"
  ]
}

export interface DocutilsorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "docutils.org";
  domain: "docutils.org";
  description: "Package information for docutils.org";
}