import type { PkgxPackage } from '../types'

/**
 * dotenvlintergithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const dotenvlintergithubioPackage: PkgxPackage = {
  name: "dotenv-linter",
  domain: "dotenv-linter.github.io",
  description: "⚡️Lightning-fast linter for .env files. Written in Rust 🦀",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/dotenv-linter.github.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) dotenv-linter",
  programs: ["dotenv-linter"],
  companions: [],
  dependencies: [],
  versions: ["3.3.0"]
}

export interface DotenvlintergithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "dotenv/lintergithubio";
  domain: "dotenv/lintergithubio";
  description: "Package information for dotenv/lintergithubio";
}
