import type { dotnetmicrosoftcomPackage } from '../types'

/**
 * dotnetmicrosoftcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const dotnetmicrosoftcomPackage: PkgxPackage = {
  "name": "dotnet",
  "domain": "dotnet.microsoft.com",
  "description": "Home of .NET's Virtual Monolithic Repository which includes all the code needed to build the .NET SDK from source",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/dotnet.microsoft.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) dotnet",
  "programs": [
    "dotnet"
  ],
  "companions": [],
  "dependencies": [
    "linuxunicode.org^71openssl.org",
    "unicode.org^71",
    "openssl.org"
  ],
  "versions": [
    "9.0.202",
    "9.0.102",
    "9.0.100",
    "8.0.405",
    "8.0.403",
    "8.0.402",
    "8.0.401",
    "8.0.308",
    "8.0.303",
    "8.0.302",
    "8.0.301",
    "8.0.206",
    "8.0.204",
    "8.0.203",
    "8.0.112",
    "8.0.107",
    "8.0.106",
    "8.0.104",
    "8.0.101",
    "8.0.100",
    "7.0.404",
    "7.0.306",
    "7.0.120",
    "6.0.424",
    "6.0.423",
    "6.0.422",
    "6.0.417",
    "6.0.132",
    "6.0.131",
    "6.0.130"
  ]
}

export interface DotnetmicrosoftcomPackage {
  name: "dotnet";
  domain: "dotnet.microsoft.com";
  description: "Home of .NET's Virtual Monolithic Repository which includes all the code needed to build the .NET SDK from source";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/dotnet.microsoft.com/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) dotnet";
  programs: readonly [
    "dotnet"
  ];
  companions: readonly [];
  dependencies: readonly [
    "linuxunicode.org^71openssl.org",
    "unicode.org^71",
    "openssl.org"
  ];
  versions: readonly [
    "9.0.202",
    "9.0.102",
    "9.0.100",
    "8.0.405",
    "8.0.403",
    "8.0.402",
    "8.0.401",
    "8.0.308",
    "8.0.303",
    "8.0.302",
    "8.0.301",
    "8.0.206",
    "8.0.204",
    "8.0.203",
    "8.0.112",
    "8.0.107",
    "8.0.106",
    "8.0.104",
    "8.0.101",
    "8.0.100",
    "7.0.404",
    "7.0.306",
    "7.0.120",
    "6.0.424",
    "6.0.423",
    "6.0.422",
    "6.0.417",
    "6.0.132",
    "6.0.131",
    "6.0.130"
  ];
}
