import type { duckdborgPackage } from '../types'

/**
 * duckdborgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const duckdborgPackage: duckdborgPackage = {
  "name": "duckdb",
  "domain": "duckdb.org",
  "description": "DuckDB is an analytical in-process SQL database management system",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/duckdb.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) duckdb",
  "programs": [
    "duckdb"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "1.3.0",
    "1.2.2",
    "1.2.1",
    "1.2.0",
    "1.1.3",
    "1.1.2",
    "1.1.1",
    "1.1.0",
    "1.0.0",
    "0.9.2",
    "0.9.1",
    "0.9.0",
    "0.8.1",
    "0.8.0",
    "0.7.1",
    "0.10.3",
    "0.10.2",
    "0.10.1",
    "0.10.0"
  ]
}

export interface duckdborgPackage {
  name: "duckdb";
  domain: "duckdb.org";
  description: "DuckDB is an analytical in-process SQL database management system";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/duckdb.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) duckdb";
  programs: readonly [
    "duckdb"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "1.3.0",
    "1.2.2",
    "1.2.1",
    "1.2.0",
    "1.1.3",
    "1.1.2",
    "1.1.1",
    "1.1.0",
    "1.0.0",
    "0.9.2",
    "0.9.1",
    "0.9.0",
    "0.8.1",
    "0.8.0",
    "0.7.1",
    "0.10.3",
    "0.10.2",
    "0.10.1",
    "0.10.0"
  ];
}
