import type { PkgxPackage } from '../types'

/**
 * dystroyorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const dystroyorgPackage: PkgxPackage = {
  "name": "dystroy.org",
  "domain": "dystroy.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx dystroy.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "dystroy.org"
}
