import type { PkgxPackage } from '../types'

/**
 * earthlydevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const earthlydevPackage: PkgxPackage = {
  "name": "earthly.dev",
  "domain": "earthly.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx earthly.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "earthly.dev"
}

export interface EarthlydevPackage {
  name: "earthly.dev";
  domain: "earthly.dev";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx earthly.dev";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "earthly.dev";
}
