import type { PkgxPackage } from '../types'

/**
 * ebassigithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ebassigithubioPackage: PkgxPackage = {
  "name": "ebassi.github.io",
  "domain": "ebassi.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx ebassi.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "ebassi.github.io"
}

export interface EbassigithubioPackage {
  name: "ebassi.github.io";
  domain: "ebassi.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx ebassi.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "ebassi.github.io";
}
