export const edgedbcomPackage = {
  name: 'edgedb' as const,
  domain: 'edgedb.com' as const,
  description: 'The EdgeDB CLI' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/edgedb.com/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) edgedb' as const,
  programs: [
    'edgedb',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '7.5.0',
    '7.4.0',
    '7.3.0',
    '7.2.0',
    '7.1.1',
    '7.1.0',
    '7.0.3',
    '7.0.2',
    '7.0.1',
    '7.0.0',
    '6.1.2',
    '6.1.1',
    '6.1.0',
    '6.0.3',
    '6.0.2',
    '6.0.1',
    '6.0.0',
    '5.5.2',
    '5.5.1',
    '5.5.0',
    '5.4.1',
    '5.4.0',
    '5.3.0',
    '5.2.3',
    '5.2.2',
    '5.2.1',
    '5.2.0',
    '5.1.0',
    '5.0.0',
    '4.1.1',
    '4.1.0',
    '4.0.2',
    '4.0.1',
    '4.0.0',
    '3.5.0',
  ] as const,
  fullPath: 'edgedb.com' as const,
  aliases: [] as const,
}

export type EdgedbcomPackage = typeof edgedbcomPackage
