import type { eigentuxfamilyorgPackage } from '../types'

/**
 * eigentuxfamilyorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const eigentuxfamilyorgPackage: eigentuxfamilyorgPackage = {
  "name": "eigen.tuxfamily.org",
  "domain": "eigen.tuxfamily.org",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/eigen.tuxfamily.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +eigen.tuxfamily.org -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [
    "linuxgnu.org/gcc/libstdcxx@14",
    "gnu.org/gcc/libstdcxx@14"
  ],
  "versions": [
    "3.4.0"
  ]
}

export interface eigentuxfamilyorgPackage {
  name: "eigen.tuxfamily.org";
  domain: "eigen.tuxfamily.org";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/eigen.tuxfamily.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +eigen.tuxfamily.org -- $SHELL -i";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [
    "linuxgnu.org/gcc/libstdcxx@14",
    "gnu.org/gcc/libstdcxx@14"
  ];
  versions: readonly [
    "3.4.0"
  ];
}
