import type { encoredevPackage } from '../types'

/**
 * encoredevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const encoredevPackage: PkgxPackage = {
  "name": "encore.dev",
  "domain": "encore.dev",
  "description": "Open Source Development Platform for building robust type-safe distributed systems with declarative infrastructure",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/encore.dev/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +encore.dev -- $SHELL -i",
  "programs": [
    "encore",
    "git-remote-encore"
  ],
  "companions": [],
  "dependencies": [
    "encore.dev/go^1.21"
  ],
  "versions": [
    "1.47.0",
    "1.46.9",
    "1.46.8",
    "1.46.7",
    "1.46.6",
    "1.46.5",
    "1.46.4",
    "1.46.22",
    "1.46.21",
    "1.46.20",
    "1.46.2",
    "1.46.19",
    "1.46.18",
    "1.46.17",
    "1.46.16",
    "1.46.15",
    "1.46.14",
    "1.46.13",
    "1.46.12",
    "1.46.11",
    "1.46.10",
    "1.46.1",
    "1.46.0",
    "1.45.6",
    "1.45.1",
    "1.44.9",
    "1.44.4",
    "1.44.0",
    "1.43.9",
    "1.43.7",
    "1.43.3",
    "1.42.3",
    "1.42.1",
    "1.41.9",
    "1.41.7",
    "1.41.4",
    "1.41.3",
    "1.41.1",
    "1.40.0",
    "1.39.0",
    "1.38.0",
    "1.37.0",
    "1.35.3",
    "1.34.7",
    "1.31.0",
    "1.30.0",
    "1.29.2",
    "1.28.0",
    "1.27.0",
    "1.26.0",
    "1.25.0"
  ]
}

export interface EncoredevPackage {
  name: "encore.dev";
  domain: "encore.dev";
  description: "Open Source Development Platform for building robust type-safe distributed systems with declarative infrastructure";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/encore.dev/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +encore.dev -- $SHELL -i";
  programs: readonly [
    "encore",
    "git-remote-encore"
  ];
  companions: readonly [];
  dependencies: readonly [
    "encore.dev/go^1.21"
  ];
  versions: readonly [
    "1.47.0",
    "1.46.9",
    "1.46.8",
    "1.46.7",
    "1.46.6",
    "1.46.5",
    "1.46.4",
    "1.46.22",
    "1.46.21",
    "1.46.20",
    "1.46.2",
    "1.46.19",
    "1.46.18",
    "1.46.17",
    "1.46.16",
    "1.46.15",
    "1.46.14",
    "1.46.13",
    "1.46.12",
    "1.46.11",
    "1.46.10",
    "1.46.1",
    "1.46.0",
    "1.45.6",
    "1.45.1",
    "1.44.9",
    "1.44.4",
    "1.44.0",
    "1.43.9",
    "1.43.7",
    "1.43.3",
    "1.42.3",
    "1.42.1",
    "1.41.9",
    "1.41.7",
    "1.41.4",
    "1.41.3",
    "1.41.1",
    "1.40.0",
    "1.39.0",
    "1.38.0",
    "1.37.0",
    "1.35.3",
    "1.34.7",
    "1.31.0",
    "1.30.0",
    "1.29.2",
    "1.28.0",
    "1.27.0",
    "1.26.0",
    "1.25.0"
  ];
}
