import type { PkgxPackage } from '../types'

/**
 * etcdioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const etcdioPackage: PkgxPackage = {
  name: "etcd",
  domain: "etcd.io",
  description: "Distributed reliable key-value store for the most critical data of a distributed system",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/etcd.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +etcd.io -- $SHELL -i",
  programs: [
    "etcd",
    "etcdctl"
  ],
  companions: [],
  dependencies: [],
  versions: [
    "3.6.0",
    "3.5.21",
    "3.5.20",
    "3.5.19",
    "3.5.18",
    "3.5.17",
    "3.5.16",
    "3.5.15",
    "3.5.14",
    "3.4.37",
    "3.4.36"
  ]
}

export interface EtcdioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "etcd.io";
  domain: "etcd.io";
  description: "Package information for etcd.io";
}