import type { PkgxPackage } from '../types'

/**
 * f1bonacc1githubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const f1bonacc1githubioPackage: PkgxPackage = {
  "name": "f1bonacc1.github.io",
  "domain": "f1bonacc1.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx f1bonacc1.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface F1bonacc1githubioPackage {
  name: "f1bonacc1.github.io";
  domain: "f1bonacc1.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx f1bonacc1.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
