import type { PkgxPackage } from '../types'

/**
 * facebookcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const facebookcomPackage: PkgxPackage = {
  name: "facebook.com",
  domain: "facebook.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx facebook.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface FacebookcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "facebook.com";
  domain: "facebook.com";
  description: "Package information for facebook.com";
}
