import type { fairwindscomPackage } from '../types'

/**
 * fairwindscomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const fairwindscomPackage: PkgxPackage = {
  "name": "fairwinds.com",
  "domain": "fairwinds.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx fairwinds.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface FairwindscomPackage {
  name: "fairwinds.com";
  domain: "fairwinds.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx fairwinds.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
