import type { PkgxPackage } from '../types'

/**
 * felixkratzgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const felixkratzgithubioPackage: PkgxPackage = {
  "name": "felixkratz.github.io",
  "domain": "felixkratz.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx felixkratz.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface FelixkratzgithubioPackage {
  name: "felixkratz.github.io";
  domain: "felixkratz.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx felixkratz.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
