import type { PkgxPackage } from '../types'

/**
 * fermyoncomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const fermyoncomPackage: PkgxPackage = {
  "name": "fermyon.com",
  "domain": "fermyon.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx fermyon.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "fermyon.com"
}

export interface FermyoncomPackage {
  name: "fermyon.com";
  domain: "fermyon.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx fermyon.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "fermyon.com";
}
