import type { ffmpegorgPackage } from '../types'

/**
 * ffmpegorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ffmpegorgPackage: PkgxPackage = {
  "name": "ffmpeg.org",
  "domain": "ffmpeg.org",
  "description": "Play, record, convert, and stream audio and video",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/ffmpeg.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +ffmpeg.org -- $SHELL -i",
  "programs": [
    "ffmpeg",
    "ffplay",
    "ffprobe"
  ],
  "companions": [],
  "dependencies": [
    "lame.sourceforge.io>=3.98.3",
    "libsdl.org^2",
    "freetype.org^2",
    "harfbuzz.org^8",
    "videolan.org/x264^0.164",
    "videolan.org/x265^3",
    "webmproject.org/libvpx^1",
    "opus-codec.org^1",
    "google.com/webp^1"
  ],
  "versions": [
    "7.1.1",
    "7.1.0",
    "7.0.2",
    "7.0.1",
    "7.0.0",
    "6.1.2",
    "6.1.1",
    "6.1.0",
    "6.0.1",
    "6.0.0",
    "5.1.6",
    "5.1.5",
    "5.1.4",
    "5.1.2",
    "4.4.6",
    "4.4.5",
    "4.3.9",
    "4.3.8",
    "4.3.7",
    "4.2.11",
    "4.2.10",
    "4.1.11",
    "3.4.14",
    "3.4.13"
  ]
}

export interface FfmpegorgPackage {
  name: "ffmpeg.org";
  domain: "ffmpeg.org";
  description: "Play, record, convert, and stream audio and video";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/ffmpeg.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +ffmpeg.org -- $SHELL -i";
  programs: readonly [
    "ffmpeg",
    "ffplay",
    "ffprobe"
  ];
  companions: readonly [];
  dependencies: readonly [
    "lame.sourceforge.io>=3.98.3",
    "libsdl.org^2",
    "freetype.org^2",
    "harfbuzz.org^8",
    "videolan.org/x264^0.164",
    "videolan.org/x265^3",
    "webmproject.org/libvpx^1",
    "opus-codec.org^1",
    "google.com/webp^1"
  ];
  versions: readonly [
    "7.1.1",
    "7.1.0",
    "7.0.2",
    "7.0.1",
    "7.0.0",
    "6.1.2",
    "6.1.1",
    "6.1.0",
    "6.0.1",
    "6.0.0",
    "5.1.6",
    "5.1.5",
    "5.1.4",
    "5.1.2",
    "4.4.6",
    "4.4.5",
    "4.3.9",
    "4.3.8",
    "4.3.7",
    "4.2.11",
    "4.2.10",
    "4.1.11",
    "3.4.14",
    "3.4.13"
  ];
}
