export const ffmpegorgPackage = {
  name: 'ffmpeg.org' as const,
  domain: 'ffmpeg.org' as const,
  description: 'Play, record, convert, and stream audio and video' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/ffmpeg.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +ffmpeg.org -- $SHELL -i' as const,
  programs: [
    'ffmpeg',
    'ffplay',
    'ffprobe',
  ] as const,
  companions: [] as const,
  dependencies: [
    'lame.sourceforge.io>=3.98.3',
    'libsdl.org^2',
    'freetype.org^2',
    'harfbuzz.org^8',
    'videolan.org/x264^0.164',
    'videolan.org/x265^3',
    'webmproject.org/libvpx^1',
    'opus-codec.org^1',
    'google.com/webp^1',
  ] as const,
  versions: [
    '7.1.1',
    '7.1.0',
    '7.0.2',
    '7.0.1',
    '7.0.0',
    '6.1.2',
    '6.1.1',
    '6.1.0',
    '6.0.1',
    '6.0.0',
    '5.1.6',
    '5.1.5',
    '5.1.4',
    '5.1.2',
    '4.4.6',
    '4.4.5',
    '4.3.9',
    '4.3.8',
    '4.3.7',
    '4.2.11',
    '4.2.10',
    '4.1.11',
    '3.4.14',
    '3.4.13',
  ] as const,
  fullPath: 'ffmpeg.org' as const,
}

export type FfmpegorgPackage = typeof ffmpegorgPackage
