import type { PkgxPackage } from '../types'

/**
 * fftworgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const fftworgPackage: PkgxPackage = {
  name: "fftw",
  domain: "fftw.org",
  description: "C routines to compute the Discrete Fourier Transform",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/fftw.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +fftw.org -- $SHELL -i",
  programs: [
    "fftw-wisdom",
    "fftw-wisdom-to-conf",
    "fftwf-wisdom",
    "fftwl-wisdom"
  ],
  companions: [],
  dependencies: ["open-mpi.org"],
  versions: ["3.3.10"]
}

export interface FftworgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "fftw.org";
  domain: "fftw.org";
  description: "Package information for fftw.org";
}