import type { fluxcdioPackage } from '../types'

/**
 * fluxcdioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const fluxcdioPackage: fluxcdioPackage = {
  "name": "fluxcd.io",
  "domain": "fluxcd.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx fluxcd.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface fluxcdioPackage {
  name: "fluxcd.io";
  domain: "fluxcd.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx fluxcd.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
