import type { flywaydborgPackage } from '../types'

/**
 * flywaydborgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const flywaydborgPackage: flywaydborgPackage = {
  "name": "flyway",
  "domain": "flywaydb.org",
  "description": "Database version control to control migrations",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/flywaydb.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) flyway",
  "programs": [
    "flyway"
  ],
  "companions": [],
  "dependencies": [
    "openjdk.org^21"
  ],
  "versions": [
    "11.8.2",
    "11.8.1",
    "11.8.0",
    "11.7.2",
    "11.7.1",
    "11.7.0",
    "11.6.0",
    "11.5.0",
    "11.4.1",
    "11.4.0",
    "11.3.4",
    "11.3.3",
    "11.3.2",
    "11.3.1",
    "11.3.0",
    "11.2.0",
    "11.1.1",
    "11.1.0",
    "11.0.1",
    "11.0.0",
    "10.22.0",
    "10.21.0",
    "10.20.1",
    "10.20.0",
    "10.19.0",
    "10.18.2",
    "10.18.1",
    "10.18.0",
    "10.17.3",
    "10.17.2",
    "10.17.1",
    "10.17.0",
    "10.16.0",
    "10.15.2",
    "10.15.0",
    "10.14.0",
    "10.13.0",
    "10.12.0",
    "10.11.1",
    "10.11.0",
    "10.10.0"
  ]
}

export interface flywaydborgPackage {
  name: "flyway";
  domain: "flywaydb.org";
  description: "Database version control to control migrations";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/flywaydb.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) flyway";
  programs: readonly [
    "flyway"
  ];
  companions: readonly [];
  dependencies: readonly [
    "openjdk.org^21"
  ];
  versions: readonly [
    "11.8.2",
    "11.8.1",
    "11.8.0",
    "11.7.2",
    "11.7.1",
    "11.7.0",
    "11.6.0",
    "11.5.0",
    "11.4.1",
    "11.4.0",
    "11.3.4",
    "11.3.3",
    "11.3.2",
    "11.3.1",
    "11.3.0",
    "11.2.0",
    "11.1.1",
    "11.1.0",
    "11.0.1",
    "11.0.0",
    "10.22.0",
    "10.21.0",
    "10.20.1",
    "10.20.0",
    "10.19.0",
    "10.18.2",
    "10.18.1",
    "10.18.0",
    "10.17.3",
    "10.17.2",
    "10.17.1",
    "10.17.0",
    "10.16.0",
    "10.15.2",
    "10.15.0",
    "10.14.0",
    "10.13.0",
    "10.12.0",
    "10.11.1",
    "10.11.0",
    "10.10.0"
  ];
}
