export const fnaxnagithubioPackage = {
  name: 'fna-xna.github.io' as const,
  domain: 'fna-xna.github.io' as const,
  description: 'FAudio - Accuracy-focused XAudio reimplementation for open platforms' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/fna-xna.github.io/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +fna-xna.github.io -- $SHELL -i' as const,
  programs: [] as const,
  companions: [] as const,
  dependencies: [
    'libsdl.org^2.28',
  ] as const,
  versions: [
    '25.5.0',
    '25.4.0',
    '25.3.0',
    '25.2.0',
    '25.1.0',
    '24.12.0',
    '24.11.0',
    '24.10.0',
    '24.9.0',
    '24.8.0',
    '24.7.0',
    '24.6.0',
    '24.5.0',
    '24.4.0',
    '24.3.0',
    '24.2.0',
    '24.1.0',
  ] as const,
  fullPath: 'fna-xna.github.io' as const,
  aliases: [] as const,
}

export type FnaxnagithubioPackage = typeof fnaxnagithubioPackage
