/**
 * Generated from pkgx.dev data
 */
export const freetdsorgPackage = {
  programs: [
    "bsqldb",
    "bsqlodbc",
    "datacopy",
    "defncopy",
    "fisql",
    "freebcp",
    "osql",
    "tdspool",
    "tsql",
  ] as const,
  companions: [] as const,
  dependencies: [
    "openssl.org^1.1",
    "unixodbc.org",
    "kerberos.org",
    "gnu.org/readline",
  ] as const,
  versions: [
    "1.5.1",
    "1.4.27",
    "1.4.26",
    "1.4.24",
    "1.4.23",
    "1.4.22",
    "1.4.21",
    "1.4.20",
    "1.4.19",
    "1.4.17",
    "1.4.16",
    "1.4.15",
    "1.4.14",
    "1.4.13",
    "1.4.12",
    "1.4.11",
    "1.4.10",
    "1.4.9",
    "1.4.8",
    "1.4.7",
    "1.4.6",
    "1.4.5",
    "1.4.4",
    "1.4.3",
    "1.4.2",
    "1.4.1",
    "1.3.21",
    "1.3.20",
    "1.3.19",
    "1.3.18",
  ] as const,
  name: "freetds.org" as const,
  domain: "freetds.org" as const,
  description: "Package information for freetds.org" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/freetds.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +freetds.org -- $SHELL -i" as const,
}

export type FreetdsorgPackage = typeof freetdsorgPackage
