import type { PkgxPackage } from '../types'

/**
 * frei0rdyneorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const frei0rdyneorgPackage: PkgxPackage = {
  name: "frei0r.dyne.org",
  domain: "frei0r.dyne.org",
  description: "",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/frei0r.dyne.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +frei0r.dyne.org -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: [],
  versions: ["1.8.0"]
}

export interface Frei0rdyneorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "frei0rdyne.org";
  domain: "frei0rdyne.org";
  description: "Package information for frei0rdyne.org";
}