import type { PkgxPackage } from '../types'

/**
 * fuellabsgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const fuellabsgithubioPackage: PkgxPackage = {
  name: "fuellabs.github.io",
  domain: "fuellabs.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx fuellabs.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface FuellabsgithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "fuellabsgithub.io";
  domain: "fuellabsgithub.io";
  description: "Package information for fuellabsgithub.io";
}