import type { PkgxPackage } from '../types'

/**
 * fukuchiorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const fukuchiorgPackage: PkgxPackage = {
  name: "fukuchi.org",
  domain: "fukuchi.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx fukuchi.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface FukuchiorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "fukuchi.org";
  domain: "fukuchi.org";
  description: "Package information for fukuchi.org";
}
