import type { PkgxPackage } from '../types'

/**
 * fullstorycomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const fullstorycomPackage: PkgxPackage = {
  name: "fullstory.com",
  domain: "fullstory.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx fullstory.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface FullstorycomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "fullstory.com";
  domain: "fullstory.com";
  description: "Package information for fullstory.com";
}
