export const fxwtfPackage = {
  name: 'fx' as const,
  domain: 'fx.wtf' as const,
  description: 'Terminal JSON viewer & processor' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/fx.wtf/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) fx' as const,
  programs: [
    'fx',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '36.0.3',
    '36.0.2',
    '36.0.1',
    '36.0.0',
    '35.0.0',
    '34.0.0',
    '33.0.0',
    '32.0.0',
    '31.0.0',
    '30.2.0',
    '30.1.1',
    '30.1.0',
    '30.0.3',
    '30.0.2',
    '30.0.1',
    '30.0.0',
    '24.1.0',
  ] as const,
  fullPath: 'fx.wtf' as const,
  aliases: [] as const,
}

export type FxwtfPackage = typeof fxwtfPackage
