import type { PkgxPackage } from '../types'

/**
 * geoffgreerfmPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const geoffgreerfmPackage: PkgxPackage = {
  "name": "geoff.greer.fm",
  "domain": "geoff.greer.fm",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx geoff.greer.fm",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "geoff.greer.fm"
}
