import type { PkgxPackage } from '../types'

/**
 * getcomposerorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const getcomposerorgPackage: PkgxPackage = {
  name: "composer",
  domain: "getcomposer.org",
  description: "Dependency Manager for PHP",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/getcomposer.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +getcomposer.org -- $SHELL -i",
  programs: [
    "composer",
    "composer.phar"
  ],
  companions: [],
  dependencies: ["php.net"],
  versions: [
    "2.8.9",
    "2.8.8",
    "2.8.7",
    "2.8.6",
    "2.8.5",
    "2.8.4",
    "2.8.3",
    "2.8.2",
    "2.8.1",
    "2.8.0",
    "2.7.9",
    "2.7.8",
    "2.7.7",
    "2.7.6",
    "2.7.5",
    "2.7.4",
    "2.7.3",
    "2.7.2",
    "2.7.1",
    "2.7.0",
    "2.6.6",
    "2.6.5",
    "2.6.4",
    "2.6.3",
    "2.6.2",
    "2.6.1",
    "2.6.0",
    "2.5.8",
    "2.2.24",
    "2.2.23"
  ]
}

export interface GetcomposerorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "getcomposer.org";
  domain: "getcomposer.org";
  description: "Package information for getcomposer.org";
}