import type { PkgxPackage } from '../types'

/**
 * getsynthcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const getsynthcomPackage: PkgxPackage = {
  "name": "synth",
  "domain": "getsynth.com",
  "description": "The Declarative Data Generator",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/getsynth.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) synth",
  "programs": [
    "synth"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "0.6.9"
  ],
  "fullPath": "getsynth.com",
  "aliases": [
    "synth"
  ]
}
