import type { PkgxPackage } from '../types'

/**
 * ghostgumcomauPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ghostgumcomauPackage: PkgxPackage = {
  "name": "ghostgum.com.au",
  "domain": "ghostgum.com.au",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx ghostgum.com.au",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "ghostgum.com.au"
}
