export const ghostscriptcomPackage = {
  name: "ghostscript.com" as const,
  domain: "ghostscript.com" as const,
  description: "This is purely for downloads, please check the website for full information" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/ghostscript.com/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +ghostscript.com -- $SHELL -i" as const,
  programs: [
    "dvipdf",
    "eps2eps",
    "gpcl6",
    "gpcl6c",
    "gpdlc",
    "gs",
    "gsbj",
    "gsc",
    "gsdj",
    "gsdj500",
    "gslj",
    "gslp",
    "gsnd",
    "gsx",
    "gxps",
    "gxpsc",
    "lprsetup.sh",
    "pdf2dsc",
    "pdf2ps",
    "pf2afm",
    "pfbtopfa",
    "pphs",
    "printafm",
    "ps2ascii",
    "ps2epsi",
    "ps2pdf",
    "ps2pdf12",
    "ps2pdf13",
    "ps2pdf14",
    "ps2pdfwr",
    "ps2ps",
    "ps2ps2",
    "unix-lpr.sh",
  ] as const,
  companions: [] as const,
  dependencies: [
    "zlib.net^1.2",
    "libpng.org^1.6",
    "libjpeg-turbo.org^2",
    "simplesystems.org/libtiff^4",
    "littlecms.com^2.15",
    "gnu.org/libidn^1.41",
    "freedesktop.org/fontconfig^2.14",
    "jbig2dec.com^0.19",
    "libexpat.github.io^2.5",
    "openjpeg.org^2.5",
    "freetype.org^2.13",
  ] as const,
  versions: [
    "10.5.1",
    "10.4.0",
    "10.3.1",
    "10.3.0",
    "10.2.1",
    "10.2.0",
    "10.1.2",
  ] as const,
  fullPath: "ghostscript.com" as const,
}

export type GhostscriptcomPackage = typeof ghostscriptcomPackage
