export const gitclifforgPackage = {
  name: 'git-cliff' as const,
  domain: 'git-cliff.org' as const,
  description: 'A highly customizable Changelog Generator that follows Conventional Commit specifications ⛰️' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/git-cliff.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) git-cliff' as const,
  programs: [
    'git-cliff',
  ] as const,
  companions: [] as const,
  dependencies: [
    'libgit2.org~1.7',
  ] as const,
  versions: [
    '2.8.0',
    '2.7.0',
    '2.6.1',
    '2.6.0',
    '2.5.0',
    '2.4.0',
    '2.3.0',
    '2.2.2',
    '2.2.1',
    '2.2.0',
    '2.1.2',
    '2.1.1',
    '2.0.4',
    '2.0.3',
    '2.0.2',
    '2.0.1',
    '2.0.0',
    '1.4.0',
    '1.3.1',
    '1.3.0',
    '1.2.0',
  ] as const,
  fullPath: 'git-cliff.org' as const,
  aliases: [] as const,
}

export type GitclifforgPackage = typeof gitclifforgPackage
