import type { gitscmorgPackage } from '../types'

/**
 * gitscmorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gitscmorgPackage: gitscmorgPackage = {
  "name": "git",
  "domain": "git-scm.org",
  "description": "Git Source Code Mirror - This is a publish-only repository but pull requests can be turned into patches to the mailing list via GitGitGadget (https://gitgitgadget.github.io/). Please follow Documentation/SubmittingPatches procedure for any of your improvements.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/git-scm.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +git-scm.org -- $SHELL -i",
  "programs": [
    "git",
    "git-cvsserver",
    "git-receive-pack",
    "git-shell",
    "git-upload-archive",
    "git-upload-pack",
    "scalar",
    "git-credential-osxkeychain"
  ],
  "companions": [],
  "dependencies": [
    "zlib.net@1",
    "gnu.org/gettext^0.21",
    "curl.se>=5",
    "curl.se/ca-certs",
    "perl.org",
    "libexpat.github.io~2"
  ],
  "versions": [
    "2.49.0",
    "2.48.0",
    "2.47.1",
    "2.47.0",
    "2.46.2",
    "2.46.1",
    "2.46.0",
    "2.45.2",
    "2.45.0",
    "2.44.0",
    "2.43.3",
    "2.43.2",
    "2.43.1",
    "2.43.0",
    "2.42.1",
    "2.42.0",
    "2.41.0",
    "2.40.0",
    "2.39.1",
    "2.39.0",
    "2.38.1"
  ],
  "fullPath": "git-scm.org"
}

export interface gitscmorgPackage {
  name: "git";
  domain: "git-scm.org";
  description: "Git Source Code Mirror - This is a publish-only repository but pull requests can be turned into patches to the mailing list via GitGitGadget (https://gitgitgadget.github.io/). Please follow Documentation/SubmittingPatches procedure for any of your improvements.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/git-scm.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +git-scm.org -- $SHELL -i";
  programs: readonly [
    "git",
    "git-cvsserver",
    "git-receive-pack",
    "git-shell",
    "git-upload-archive",
    "git-upload-pack",
    "scalar",
    "git-credential-osxkeychain"
  ];
  companions: readonly [];
  dependencies: readonly [
    "zlib.net@1",
    "gnu.org/gettext^0.21",
    "curl.se>=5",
    "curl.se/ca-certs",
    "perl.org",
    "libexpat.github.io~2"
  ];
  versions: readonly [
    "2.49.0",
    "2.48.0",
    "2.47.1",
    "2.47.0",
    "2.46.2",
    "2.46.1",
    "2.46.0",
    "2.45.2",
    "2.45.0",
    "2.44.0",
    "2.43.3",
    "2.43.2",
    "2.43.1",
    "2.43.0",
    "2.42.1",
    "2.42.0",
    "2.41.0",
    "2.40.0",
    "2.39.1",
    "2.39.0",
    "2.38.1"
  ];
  fullPath: "git-scm.org";
}
