export const githubcomfastfetchclifastfetchPackage = {
  name: 'github.com/fastfetch-cli/fastfetch' as const,
  domain: 'github.com/fastfetch-cli/fastfetch' as const,
  description: 'A maintained, feature-rich and performance oriented, neofetch like system information tool.' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/github.com/fastfetch-cli/fastfetch/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +github.com/fastfetch-cli/fastfetch -- $SHELL -i' as const,
  programs: [
    'fastfetch',
    'flashfetch',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '2.44.0',
    '2.43.0',
    '2.42.0',
    '2.41.0',
    '2.40.4',
    '2.40.3',
    '2.40.2',
    '2.40.1',
    '2.40.0',
    '2.39.1',
    '2.39.0',
    '2.38.0',
    '2.37.0',
    '2.36.1',
    '2.36.0',
    '2.35.0',
    '2.34.1',
    '2.34.0',
    '2.33.0',
  ] as const,
  fullPath: 'github.com/fastfetch-cli/fastfetch' as const,
  aliases: [
    'fastfetch-cli/fastfetch',
  ] as const,
}

export type GithubcomfastfetchclifastfetchPackage = typeof githubcomfastfetchclifastfetchPackage
