import type { gitlabcomPackage } from '../types'

/**
 * gitlabcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gitlabcomPackage: gitlabcomPackage = {
  "name": "gitlab.com",
  "domain": "gitlab.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx gitlab.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface gitlabcomPackage {
  name: "gitlab.com";
  domain: "gitlab.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx gitlab.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
