import type { PkgxPackage } from '../types'

/**
 * gitlabcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gitlabcomPackage: PkgxPackage = {
  "name": "gitlab.com",
  "domain": "gitlab.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx gitlab.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "gitlab.com"
}
