import type { PkgxPackage } from '../types'

/**
 * gitosgeoorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gitosgeoorgPackage: PkgxPackage = {
  name: "git.osgeo.org",
  domain: "git.osgeo.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx git.osgeo.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface GitosgeoorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "gitosgeo.org";
  domain: "gitosgeo.org";
  description: "Package information for gitosgeo.org";
}