import type { PkgxPackage } from '../types'

/**
 * gitosgeoorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gitosgeoorgPackage: PkgxPackage = {
  "name": "git.osgeo.org",
  "domain": "git.osgeo.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx git.osgeo.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "git.osgeo.org"
}

export interface GitosgeoorgPackage {
  name: "git.osgeo.org";
  domain: "git.osgeo.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx git.osgeo.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "git.osgeo.org";
}
