import type { PkgxPackage } from '../types'

/**
 * gittoztnetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gittoztnetPackage: PkgxPackage = {
  name: "git.tozt.net",
  domain: "git.tozt.net",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx git.tozt.net",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface GittoztnetPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "gittozt.net";
  domain: "gittozt.net";
  description: "Package information for gittozt.net";
}