import type { glarosdtcumneduPackage } from '../types'

/**
 * glarosdtcumneduPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const glarosdtcumneduPackage: glarosdtcumneduPackage = {
  "name": "glaros.dtc.umn.edu",
  "domain": "glaros.dtc.umn.edu",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx glaros.dtc.umn.edu",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface glarosdtcumneduPackage {
  name: "glaros.dtc.umn.edu";
  domain: "glaros.dtc.umn.edu";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx glaros.dtc.umn.edu";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
