import type { PkgxPackage } from '../types'

/**
 * glarosdtcumneduPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const glarosdtcumneduPackage: PkgxPackage = {
  "name": "glaros.dtc.umn.edu",
  "domain": "glaros.dtc.umn.edu",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx glaros.dtc.umn.edu",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "glaros.dtc.umn.edu"
}

export interface GlarosdtcumneduPackage {
  name: "glaros.dtc.umn.edu";
  domain: "glaros.dtc.umn.edu";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx glaros.dtc.umn.edu";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "glaros.dtc.umn.edu";
}
