import type { PkgxPackage } from '../types'

/**
 * gnomeorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gnomeorgPackage: PkgxPackage = {
  "name": "gnome.org",
  "domain": "gnome.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx gnome.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface GnomeorgPackage {
  name: "gnome.org";
  domain: "gnome.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx gnome.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
