import type { PkgxPackage } from '../types'

/**
 * gnuorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gnuorgPackage: PkgxPackage = {
  "name": "gnu.org",
  "domain": "gnu.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx gnu.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "gnu.org"
}

export interface GnuorgPackage {
  name: "gnu.org";
  domain: "gnu.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx gnu.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "gnu.org";
}
