import type { PkgxPackage } from '../types'

/**
 * gnuorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gnuorgPackage: PkgxPackage = {
  name: "gnu.org",
  domain: "gnu.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx gnu.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface GnuorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "gnu.org";
  domain: "gnu.org";
  description: "Package information for gnu.org";
}