export const gnupgorgPackage = {
  name: 'gnupg.org' as const,
  domain: 'gnupg.org' as const,
  description: 'GNU Pretty Good Privacy (PGP) package' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/gnupg.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +gnupg.org -- $SHELL -i' as const,
  programs: [
    'gpg',
    'gpg-agent',
    'gpg-connect-agent',
    'gpg-wks-server',
    'gpgconf',
    'gpgparsemail',
    'gpgscm',
    'gpgsm',
    'gpgsplit',
    'gpgtar',
    'gpgv',
    'kbxutil',
    'watchgnupg',
  ] as const,
  companions: [] as const,
  dependencies: [
    'zlib.net^1.1',
    'sourceware.org/bzip2',
    'gnupg.org/npth',
    'gnupg.org/libgpg-error',
    'gnupg.org/libksba',
    'gnupg.org/libassuan@2',
    'gnupg.org/libgcrypt',
    'gnupg.org/pinentry',
    'gnutls.org^3',
    'openldap.org^2',
    'gnu.org/readline^8',
    'sqlite.org^3',
    'darwingnu.org/gettext^0.21',
    'gnu.org/gettext^0.21',
  ] as const,
  versions: [
    '2.4.8',
    '2.4.7',
    '2.4.6',
    '2.4.5',
    '2.4.4',
    '2.4.3',
    '2.4.2',
    '2.3.7',
    '2.2.45',
    '2.2.44',
    '2.2.43',
    '2.2.42',
  ] as const,
  fullPath: 'gnupg.org' as const,
  aliases: [] as const,
}

export type GnupgorgPackage = typeof gnupgorgPackage
