import type { PkgxPackage } from '../types'

/**
 * golangci-lintrunPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const golangcilintrunPackage: PkgxPackage = {
  "name": "golangci-lint",
  "domain": "golangci-lint.run",
  "description": "Fast linters runner for Go",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/golangci-lint.run/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) golangci-lint",
  "programs": [
    "golangci-lint"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "2.1.6",
    "2.1.5",
    "2.1.4",
    "2.1.3",
    "2.1.2",
    "2.1.1",
    "2.1.0",
    "2.0.2",
    "2.0.1",
    "2.0.0",
    "1.64.8",
    "1.64.7",
    "1.64.6",
    "1.64.5",
    "1.64.4",
    "1.64.3",
    "1.64.2",
    "1.63.4",
    "1.63.3",
    "1.63.2",
    "1.63.1",
    "1.63.0",
    "1.62.2",
    "1.62.0",
    "1.61.0",
    "1.60.3",
    "1.60.2",
    "1.60.1",
    "1.59.1",
    "1.59.0",
    "1.58.2",
    "1.58.1",
    "1.58.0",
    "1.57.2",
    "1.57.1",
    "1.57.0",
    "1.56.2",
    "1.56.1",
    "1.56.0",
    "1.55.2",
    "1.55.1",
    "1.55.0",
    "1.54.2",
    "1.54.1",
    "1.53.3",
    "1.53.2",
    "1.53.1",
    "1.53.0",
    "1.52.2",
    "1.52.1",
    "1.52.0",
    "1.51.2"
  ],
  "fullPath": "golangci-lint.run"
}

export interface GolangcilintrunPackage {
  name: "golangci-lint";
  domain: "golangci-lint.run";
  description: "Fast linters runner for Go";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/golangci-lint.run/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) golangci-lint";
  programs: readonly [
    "golangci-lint"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "2.1.6",
    "2.1.5",
    "2.1.4",
    "2.1.3",
    "2.1.2",
    "2.1.1",
    "2.1.0",
    "2.0.2",
    "2.0.1",
    "2.0.0",
    "1.64.8",
    "1.64.7",
    "1.64.6",
    "1.64.5",
    "1.64.4",
    "1.64.3",
    "1.64.2",
    "1.63.4",
    "1.63.3",
    "1.63.2",
    "1.63.1",
    "1.63.0",
    "1.62.2",
    "1.62.0",
    "1.61.0",
    "1.60.3",
    "1.60.2",
    "1.60.1",
    "1.59.1",
    "1.59.0",
    "1.58.2",
    "1.58.1",
    "1.58.0",
    "1.57.2",
    "1.57.1",
    "1.57.0",
    "1.56.2",
    "1.56.1",
    "1.56.0",
    "1.55.2",
    "1.55.1",
    "1.55.0",
    "1.54.2",
    "1.54.1",
    "1.53.3",
    "1.53.2",
    "1.53.1",
    "1.53.0",
    "1.52.2",
    "1.52.1",
    "1.52.0",
    "1.51.2"
  ];
  fullPath: "golangci-lint.run";
}
