import type { PkgxPackage } from '../types'

/**
 * googlecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const googlecomPackage: PkgxPackage = {
  "name": "google.com",
  "domain": "google.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx google.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "google.com"
}
