import type { googlecomPackage } from '../types'

/**
 * googlecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const googlecomPackage: googlecomPackage = {
  "name": "google.com",
  "domain": "google.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx google.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface googlecomPackage {
  name: "google.com";
  domain: "google.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx google.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
