import type { PkgxPackage } from '../types'

/**
 * googlegithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const googlegithubioPackage: PkgxPackage = {
  "name": "google.github.io",
  "domain": "google.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx google.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "google.github.io"
}
