import type { gouberorgPackage } from '../types'

/**
 * gouberorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gouberorgPackage: gouberorgPackage = {
  "name": "go.uber.org",
  "domain": "go.uber.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx go.uber.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface gouberorgPackage {
  name: "go.uber.org";
  domain: "go.uber.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx go.uber.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
