import type { PkgxPackage } from '../types'

/**
 * gouberorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gouberorgPackage: PkgxPackage = {
  "name": "go.uber.org",
  "domain": "go.uber.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx go.uber.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "go.uber.org"
}

export interface GouberorgPackage {
  name: "go.uber.org";
  domain: "go.uber.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx go.uber.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "go.uber.org";
}
