import type { PkgxPackage } from '../types'

/**
 * gphotoorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gphotoorgPackage: PkgxPackage = {
  name: "gphoto.org",
  domain: "gphoto.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx gphoto.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface GphotoorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "gphoto.org";
  domain: "gphoto.org";
  description: "Package information for gphoto.org";
}