import type { gphotoorgPackage } from '../types'

/**
 * gphotoorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gphotoorgPackage: gphotoorgPackage = {
  "name": "gphoto.org",
  "domain": "gphoto.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx gphoto.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface gphotoorgPackage {
  name: "gphoto.org";
  domain: "gphoto.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx gphoto.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
