import type { PkgxPackage } from '../types'

/**
 * granteddevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const granteddevPackage: PkgxPackage = {
  name: "granted",
  domain: "granted.dev",
  description: "The easiest way to access your cloud.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/granted.dev/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) granted",
  programs: ["granted"],
  companions: [],
  dependencies: [],
  versions: [
    "0.38.0",
    "0.37.0",
    "0.36.3",
    "0.36.2",
    "0.36.1",
    "0.36.0",
    "0.35.2",
    "0.35.1",
    "0.35.0",
    "0.34.1",
    "0.34.0",
    "0.33.0",
    "0.32.0",
    "0.31.2",
    "0.31.1",
    "0.31.0",
    "0.30.0",
    "0.29.3",
    "0.29.2",
    "0.29.1",
    "0.29.0",
    "0.28.0",
    "0.27.5",
    "0.27.4",
    "0.27.3",
    "0.27.2",
    "0.27.1",
    "0.27.0",
    "0.26.2",
    "0.26.1",
    "0.26.0",
    "0.25.0",
    "0.24.0",
    "0.23.2",
    "0.23.1",
    "0.23.0",
    "0.22.0",
    "0.21.1"
  ]
}

export interface GranteddevPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "granted.dev";
  domain: "granted.dev";
  description: "Package information for granted.dev";
}