export const graphvizorgPackage = {
  name: 'graphviz.org' as const,
  domain: 'graphviz.org' as const,
  description: 'Graph visualization software from AT&T and Bell Labs' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/graphviz.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +graphviz.org -- $SHELL -i' as const,
  programs: [
    'acyclic',
    'bcomps',
    'ccomps',
    'circo',
    'cluster',
    'dijkstra',
    'dot',
    'dot2gxl',
    'dot_builtins',
    'edgepaint',
    'fdp',
    'gc',
    'gml2gv',
    'graphml2gv',
    'gv2gml',
    'gv2gxl',
    'gvcolor',
    'gvgen',
    'gvmap',
    'gvmap.sh',
    'gvpack',
    'gvpr',
    'gxl2dot',
    'gxl2gv',
    'mm2gv',
    'neato',
    'nop',
    'osage',
    'patchwork',
    'prune',
    'sccmap',
    'sfdp',
    'tred',
    'twopi',
    'unflatten',
  ] as const,
  companions: [] as const,
  dependencies: [
    'cairographics.org^1.1.10',
    'freedesktop.org/fontconfig^2.3.95',
    'freetype.org^2.1.0',
    'gnome.org/glib^2.11.0',
    'gnome.org/pango^1.12.4',
    'gnu.org/libtool^2',
    'libexpat.github.io^2.0.0',
    'libpng.org^1.2.10',
    'poppler.freedesktop.org',
    'zlib.net^1.2.3',
  ] as const,
  versions: [
    '12.2.1',
    '12.2.0',
    '12.1.2',
    '12.1.1',
    '12.1.0',
    '12.0.0',
    '11.0.0',
    '10.0.1',
    '9.0.0',
    '8.1.0',
    '7.1.0',
  ] as const,
  fullPath: 'graphviz.org' as const,
  aliases: [] as const,
}

export type GraphvizorgPackage = typeof graphvizorgPackage
