import type { graphqleditorcomPackage } from '../types'

/**
 * graphqleditorcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const graphqleditorcomPackage: graphqleditorcomPackage = {
  "name": "graphqleditor.com",
  "domain": "graphqleditor.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx graphqleditor.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface graphqleditorcomPackage {
  name: "graphqleditor.com";
  domain: "graphqleditor.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx graphqleditor.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
