/**
 * Generated from pkgx.dev data
 */
export const groongaorgPackage = {
  programs: [
    "groonga",
    "groonga-suggest-create-dataset",
  ] as const,
  companions: [] as const,
  dependencies: [
    "darwintaku910.github.io/mecabtaku910.github.io/mecab-ipadic",
    "taku910.github.io/mecab",
    "taku910.github.io/mecab-ipadic",
    "linux/x86-64taku910.github.io/mecabtaku910.github.io/mecab-ipadic",
    "taku910.github.io/mecab",
    "taku910.github.io/mecab-ipadic",
    "msgpack.org",
    "openssl.org",
    "pcre.org/v2",
    "github.com/besser82/libxcrypt",
    "linuxgnome.org/glib",
    "gnome.org/glib",
  ] as const,
  versions: [
    "15.0.9",
    "15.0.4",
    "15.0.3",
    "15.0.2",
    "15.0.1",
    "15.0.0",
    "14.1.3",
    "14.1.2",
    "14.1.1",
    "14.1.0",
    "14.0.9",
    "14.0.8",
    "14.0.7",
    "14.0.6",
    "14.0.5",
    "14.0.4",
    "14.0.3",
    "14.0.2",
    "14.0.1",
    "14.0.0",
    "13.1.1",
    "13.1.0",
    "13.0.9",
    "13.0.8",
    "13.0.7",
    "13.0.6",
  ] as const,
  name: "groonga.org" as const,
  domain: "groonga.org" as const,
  description: "Package information for groonga.org" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/groonga.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +groonga.org -- $SHELL -i" as const,
}

export type GroongaorgPackage = typeof groongaorgPackage
