import type { PkgxPackage } from '../types'

/**
 * gstreamerfreedesktoporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gstreamerfreedesktoporgPackage: PkgxPackage = {
  name: "gstreamer.freedesktop.org",
  domain: "gstreamer.freedesktop.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx gstreamer.freedesktop.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface GstreamerfreedesktoporgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "gstreamerfreedesktop.org";
  domain: "gstreamerfreedesktop.org";
  description: "Package information for gstreamerfreedesktop.org";
}
