import type { PkgxPackage } from '../types'

/**
 * gtssourceforgenetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const gtssourceforgenetPackage: PkgxPackage = {
  "name": "gts.sourceforge.net",
  "domain": "gts.sourceforge.net",
  "description": "GNU triangulated surface library",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/gts.sourceforge.net/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +gts.sourceforge.net -- $SHELL -i",
  "programs": [
    "delaunay",
    "gts2dxf",
    "gts2oogl",
    "gts2stl",
    "gtscheck",
    "gtscompare",
    "gtstemplate",
    "stl2gts",
    "transform"
  ],
  "companions": [],
  "dependencies": [
    "gnome.org/glib>=2.4.0"
  ],
  "versions": [
    "0.7.6"
  ]
}

export interface GtssourceforgenetPackage {
  name: "gts.sourceforge.net";
  domain: "gts.sourceforge.net";
  description: "GNU triangulated surface library";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/gts.sourceforge.net/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +gts.sourceforge.net -- $SHELL -i";
  programs: readonly [
    "delaunay",
    "gts2dxf",
    "gts2oogl",
    "gts2stl",
    "gtscheck",
    "gtscompare",
    "gtstemplate",
    "stl2gts",
    "transform"
  ];
  companions: readonly [];
  dependencies: readonly [
    "gnome.org/glib>=2.4.0"
  ];
  versions: readonly [
    "0.7.6"
  ];
}
