import type { hardingmotdcaPackage } from '../types'

/**
 * hardingmotdcaPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const hardingmotdcaPackage: hardingmotdcaPackage = {
  "name": "harding.motd.ca",
  "domain": "harding.motd.ca",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx harding.motd.ca",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface hardingmotdcaPackage {
  name: "harding.motd.ca";
  domain: "harding.motd.ca";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx harding.motd.ca";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
