import type { PkgxPackage } from '../types'

/**
 * hardingmotdcaPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const hardingmotdcaPackage: PkgxPackage = {
  name: "harding.motd.ca",
  domain: "harding.motd.ca",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx harding.motd.ca",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface HardingmotdcaPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "hardingmotdca";
  domain: "hardingmotdca";
  description: "Package information for hardingmotdca";
}
