export const harfbuzzorgPackage = {
  name: 'harfbuzz.org' as const,
  domain: 'harfbuzz.org' as const,
  description: 'HarfBuzz text shaping engine' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/harfbuzz.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +harfbuzz.org -- $SHELL -i' as const,
  programs: [
    'hb-ot-shape-closure',
    'hb-shape',
    'hb-subset',
    'hb-view',
  ] as const,
  companions: [] as const,
  dependencies: [
    'cairographics.org@1',
    'freetype.org@2',
    'gnome.org/glib@2',
    'graphite.sil.org',
    'unicode.org^71',
  ] as const,
  versions: [
    '11.2.1',
    '11.2.0',
    '11.1.0',
    '11.0.1',
    '11.0.0',
    '10.4.0',
    '10.3.0',
    '10.2.0',
    '10.1.0',
    '10.0.1',
    '10.0.0',
    '9.0.0',
    '8.5.0',
    '8.4.0',
    '8.3.0',
    '8.2.2',
    '8.2.1',
    '8.2.0',
    '8.1.1',
    '8.1.0',
    '8.0.1',
    '8.0.0',
    '7.3.0',
    '7.2.0',
    '7.1.0',
    '7.0.1',
    '7.0.0',
    '5.3.1',
  ] as const,
  fullPath: 'harfbuzz.org' as const,
  aliases: [] as const,
}

export type HarfbuzzorgPackage = typeof harfbuzzorgPackage
