import type { PkgxPackage } from '../types'

/**
 * hboehminfoPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const hboehminfoPackage: PkgxPackage = {
  "name": "hboehm.info",
  "domain": "hboehm.info",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx hboehm.info",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "hboehm.info"
}
