import type { PkgxPackage } from '../types'

/**
 * hdfgrouporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const hdfgrouporgPackage: PkgxPackage = {
  "name": "hdfgroup.org",
  "domain": "hdfgroup.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx hdfgroup.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "hdfgroup.org"
}
