import type { heasarcgsfcnasagovPackage } from '../types'

/**
 * heasarcgsfcnasagovPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const heasarcgsfcnasagovPackage: heasarcgsfcnasagovPackage = {
  "name": "heasarc.gsfc.nasa.gov",
  "domain": "heasarc.gsfc.nasa.gov",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx heasarc.gsfc.nasa.gov",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface heasarcgsfcnasagovPackage {
  name: "heasarc.gsfc.nasa.gov";
  domain: "heasarc.gsfc.nasa.gov";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx heasarc.gsfc.nasa.gov";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
