import type { PkgxPackage } from '../types'

/**
 * hetznercomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const hetznercomPackage: PkgxPackage = {
  "name": "hetzner.com",
  "domain": "hetzner.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx hetzner.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "hetzner.com"
}

export interface HetznercomPackage {
  name: "hetzner.com";
  domain: "hetzner.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx hetzner.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "hetzner.com";
}
