import type { hjsongithubioPackage } from '../types'

/**
 * hjsongithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const hjsongithubioPackage: hjsongithubioPackage = {
  "name": "hjson",
  "domain": "hjson.github.io",
  "description": "Hjson for Rust",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/hjson.github.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) hjson",
  "programs": [
    "hjson"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "1.1.0",
    "1.0.0"
  ]
}

export interface hjsongithubioPackage {
  name: "hjson";
  domain: "hjson.github.io";
  description: "Hjson for Rust";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/hjson.github.io/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) hjson";
  programs: readonly [
    "hjson"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "1.1.0",
    "1.0.0"
  ];
}
