import type { PkgxPackage } from '../types'

/**
 * hjsongithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const hjsongithubioPackage: PkgxPackage = {
  name: "hjson",
  domain: "hjson.github.io",
  description: "Hjson for Rust",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/hjson.github.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) hjson",
  programs: ["hjson"],
  companions: [],
  dependencies: [],
  versions: [
    "1.1.0",
    "1.0.0"
  ]
}

export interface HjsongithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "hjsongithub.io";
  domain: "hjsongithub.io";
  description: "Package information for hjsongithub.io";
}