import type { httpieioPackage } from '../types'

/**
 * httpieioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const httpieioPackage: httpieioPackage = {
  "name": "httpie.io",
  "domain": "httpie.io",
  "description": "🥧 HTTPie CLI  — modern, user-friendly command-line HTTP client for the API era. JSON support, colors, sessions, downloads, plugins & more.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/httpie.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +httpie.io -- $SHELL -i",
  "programs": [
    "http",
    "httpie",
    "https"
  ],
  "companions": [],
  "dependencies": [
    "python.org>=3<3.12"
  ],
  "versions": [
    "3.2.4",
    "3.2.3",
    "3.2.2",
    "3.2.1"
  ]
}

export interface httpieioPackage {
  name: "httpie.io";
  domain: "httpie.io";
  description: "🥧 HTTPie CLI  — modern, user-friendly command-line HTTP client for the API era. JSON support, colors, sessions, downloads, plugins & more.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/httpie.io/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +httpie.io -- $SHELL -i";
  programs: readonly [
    "http",
    "httpie",
    "https"
  ];
  companions: readonly [];
  dependencies: readonly [
    "python.org>=3<3.12"
  ];
  versions: readonly [
    "3.2.4",
    "3.2.3",
    "3.2.2",
    "3.2.1"
  ];
}
