import type { PkgxPackage } from '../types'

/**
 * hurldevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const hurldevPackage: PkgxPackage = {
  name: "hurl",
  domain: "hurl.dev",
  description: "Run and Test HTTP Requests with plain text and curl",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/hurl.dev/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +hurl.dev -- $SHELL -i",
  programs: [
    "hurl",
    "hurlfmt"
  ],
  companions: [],
  dependencies: [
    "gnome.org/libxml2",
    "curl.se"
  ],
  versions: [
    "6.1.1",
    "6.1.0",
    "6.0.0",
    "5.0.1",
    "5.0.0",
    "4.3.0",
    "4.2.0",
    "4.1.0",
    "4.0.0"
  ]
}

export interface HurldevPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "hurl.dev";
  domain: "hurl.dev";
  description: "Package information for hurl.dev";
}
