import type { PkgxPackage } from '../types'

/**
 * idleberggithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const idleberggithubioPackage: PkgxPackage = {
  "name": "idleberg.github.io",
  "domain": "idleberg.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx idleberg.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "idleberg.github.io"
}

export interface IdleberggithubioPackage {
  name: "idleberg.github.io";
  domain: "idleberg.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx idleberg.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "idleberg.github.io";
}
