import type { indexsupplycomPackage } from '../types'

/**
 * indexsupplycomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const indexsupplycomPackage: indexsupplycomPackage = {
  "name": "indexsupply.com",
  "domain": "indexsupply.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx indexsupply.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface indexsupplycomPackage {
  name: "indexsupply.com";
  domain: "indexsupply.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx indexsupply.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
