import type { PkgxPackage } from '../types'

/**
 * info-ziporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const infoziporgPackage: PkgxPackage = {
  "name": "info-zip.org",
  "domain": "info-zip.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx info-zip.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "info-zip.org"
}
