import type { PkgxPackage } from '../types'

/**
 * infoziporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const infoziporgPackage: PkgxPackage = {
  name: "info-zip.org",
  domain: "info-zip.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx info-zip.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface InfoziporgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "info/ziporg";
  domain: "info/ziporg";
  description: "Package information for info/ziporg";
}