import type { intelcomPackage } from '../types'

/**
 * intelcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const intelcomPackage: intelcomPackage = {
  "name": "intel.com",
  "domain": "intel.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx intel.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface intelcomPackage {
  name: "intel.com";
  domain: "intel.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx intel.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
