import type { PkgxPackage } from '../types'

/**
 * invisible-islandnetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const invisibleislandnetPackage: PkgxPackage = {
  "name": "invisible-island.net",
  "domain": "invisible-island.net",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx invisible-island.net",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "invisible-island.net"
}
