import type { PkgxPackage } from '../types'

/**
 * ipfstechPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ipfstechPackage: PkgxPackage = {
  "name": "ipfs",
  "domain": "ipfs.tech",
  "description": "Peer-to-peer hypermedia protocol",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/ipfs.tech/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) ipfs",
  "programs": [
    "ipfs"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "0.35.0",
    "0.34.1",
    "0.34.0",
    "0.33.2",
    "0.33.1",
    "0.33.0",
    "0.32.1",
    "0.32.0",
    "0.31.0",
    "0.30.0",
    "0.29.0",
    "0.28.0",
    "0.27.0",
    "0.26.0",
    "0.25.0",
    "0.24.0",
    "0.23.0",
    "0.22.0",
    "0.21.1",
    "0.21.0",
    "0.20.0",
    "0.19.2",
    "0.19.1",
    "0.19.0",
    "0.18.1",
    "0.18.0",
    "0.17.0",
    "0.16.0"
  ]
}

export interface IpfstechPackage {
  name: "ipfs";
  domain: "ipfs.tech";
  description: "Peer-to-peer hypermedia protocol";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/ipfs.tech/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) ipfs";
  programs: readonly [
    "ipfs"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "0.35.0",
    "0.34.1",
    "0.34.0",
    "0.33.2",
    "0.33.1",
    "0.33.0",
    "0.32.1",
    "0.32.0",
    "0.31.0",
    "0.30.0",
    "0.29.0",
    "0.28.0",
    "0.27.0",
    "0.26.0",
    "0.25.0",
    "0.24.0",
    "0.23.0",
    "0.22.0",
    "0.21.1",
    "0.21.0",
    "0.20.0",
    "0.19.2",
    "0.19.1",
    "0.19.0",
    "0.18.1",
    "0.18.0",
    "0.17.0",
    "0.16.0"
  ];
}
