import type { PkgxPackage } from '../types'

/**
 * ivarchcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ivarchcomPackage: PkgxPackage = {
  "name": "ivarch.com",
  "domain": "ivarch.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx ivarch.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "ivarch.com"
}
