export const jbangdevPackage = {
  name: 'jbang' as const,
  domain: 'jbang.dev' as const,
  description: 'Unleash the power of Java - JBang Lets Students, Educators and Professional Developers create, edit and run self-contained source-only Java programs with unprecedented ease.' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/jbang.dev/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) jbang' as const,
  programs: [
    'jbang',
  ] as const,
  companions: [] as const,
  dependencies: [
    'openjdk.org',
  ] as const,
  versions: [
    '0.126.1',
    '0.126.0',
    '0.125.1',
    '0.125.0',
    '0.124.0',
    '0.123.0',
    '0.122.0',
    '0.121.0',
    '0.120.4',
    '0.119.0',
    '0.118.0',
    '0.117.1',
    '0.117.0',
    '0.116.0',
    '0.115.0',
    '0.114.0',
    '0.113.0',
    '0.112.4',
    '0.111.0',
    '0.110.1',
  ] as const,
  fullPath: 'jbang.dev' as const,
}

export type JbangdevPackage = typeof jbangdevPackage
