import type { jedisct1githubioPackage } from '../types'

/**
 * jedisct1githubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jedisct1githubioPackage: jedisct1githubioPackage = {
  "name": "jedisct1.github.io",
  "domain": "jedisct1.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx jedisct1.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface jedisct1githubioPackage {
  name: "jedisct1.github.io";
  domain: "jedisct1.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx jedisct1.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
