import type { jedsoftorgPackage } from '../types'

/**
 * jedsoftorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jedsoftorgPackage: PkgxPackage = {
  "name": "jedsoft.org",
  "domain": "jedsoft.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx jedsoft.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface JedsoftorgPackage {
  name: "jedsoft.org";
  domain: "jedsoft.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx jedsoft.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
