import type { PkgxPackage } from '../types'

/**
 * jedsoftorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jedsoftorgPackage: PkgxPackage = {
  "name": "jedsoft.org",
  "domain": "jedsoft.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx jedsoft.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "jedsoft.org"
}
