import type { PkgxPackage } from '../types'

/**
 * jetporchcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jetporchcomPackage: PkgxPackage = {
  name: "jetp",
  domain: "jetporch.com",
  description: "Read-only mirror: see https://www.jetporch.com/community/sourcehut",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/jetporch.com/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) jetp",
  programs: ["jetp"],
  companions: [],
  dependencies: [],
  versions: ["0.0.1"]
}

export interface JetporchcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "jetporch.com";
  domain: "jetporch.com";
  description: "Package information for jetporch.com";
}