import type { jfrogcomPackage } from '../types'

/**
 * jfrogcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jfrogcomPackage: jfrogcomPackage = {
  "name": "jfrog.com",
  "domain": "jfrog.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx jfrog.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface jfrogcomPackage {
  name: "jfrog.com";
  domain: "jfrog.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx jfrog.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
