import type { PkgxPackage } from '../types'

/**
 * jonasgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jonasgithubioPackage: PkgxPackage = {
  name: "jonas.github.io",
  domain: "jonas.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx jonas.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface JonasgithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "jonasgithub.io";
  domain: "jonasgithub.io";
  description: "Package information for jonasgithub.io";
}
