import type { PkgxPackage } from '../types'

/**
 * jpegorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jpegorgPackage: PkgxPackage = {
  name: "jpeg.org",
  domain: "jpeg.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx jpeg.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface JpegorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "jpeg.org";
  domain: "jpeg.org";
  description: "Package information for jpeg.org";
}
