import type { jugitfzjuelichdePackage } from '../types'

/**
 * jugitfzjuelichdePackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jugitfzjuelichdePackage: PkgxPackage = {
  "name": "jugit.fz-juelich.de",
  "domain": "jugit.fz-juelich.de",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx jugit.fz-juelich.de",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface JugitfzjuelichdePackage {
  name: "jugit.fz-juelich.de";
  domain: "jugit.fz-juelich.de";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx jugit.fz-juelich.de";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
