import type { PkgxPackage } from '../types'

/**
 * jujuisPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const jujuisPackage: PkgxPackage = {
  "name": "juju",
  "domain": "juju.is",
  "description": "Orchestration engine that enables the deployment, integration and lifecycle management of applications at any scale, on any infrastructure (Kubernetes or otherwise).",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/juju.is/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) juju",
  "programs": [
    "juju"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "3.6.5",
    "3.6.4",
    "3.6.3",
    "3.6.2",
    "3.6.1",
    "3.6.0",
    "3.5.7",
    "3.5.6",
    "3.5.5",
    "3.5.4",
    "3.5.3",
    "3.4.6",
    "3.3.7",
    "3.1.10",
    "2.9.51"
  ],
  "fullPath": "juju.is"
}
