import type { keephqdevPackage } from '../types'

/**
 * keephqdevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const keephqdevPackage: keephqdevPackage = {
  "name": "keep",
  "domain": "keephq.dev",
  "description": "The open-source AIOps and alert management platform",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/keephq.dev/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) keep",
  "programs": [
    "keep"
  ],
  "companions": [],
  "dependencies": [
    "python.org>=3<3.12"
  ],
  "versions": [
    "0.0.0"
  ]
}

export interface keephqdevPackage {
  name: "keep";
  domain: "keephq.dev";
  description: "The open-source AIOps and alert management platform";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/keephq.dev/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) keep";
  programs: readonly [
    "keep"
  ];
  companions: readonly [];
  dependencies: readonly [
    "python.org>=3<3.12"
  ];
  versions: readonly [
    "0.0.0"
  ];
}
