/**
 * Generated from pkgx.dev data
 */
export const kerberosorgPackage = {
  programs: [
    "compile_et",
    "gss-client",
    "k5srvutil",
    "kadmin",
    "kdestroy",
    "kinit",
    "klist",
    "kpasswd",
    "krb5-config",
    "kswitch",
    "ktutil",
    "kvno",
    "sclient",
    "sim_client",
    "uuclient",
    "gss-server",
    "kadmin.local",
    "kadmind",
    "kdb5_util",
    "kprop",
    "kpropd",
    "kproplog",
    "krb5-send-pr",
    "krb5kdc",
    "sim_server",
    "sserver",
    "uuserver",
  ] as const,
  companions: [] as const,
  dependencies: [
    "openssl.org^1.1",
  ] as const,
  versions: [
    "1.21.3",
    "1.21.2",
    "1.21.1",
    "1.21.0",
    "1.20.2",
    "1.20.1",
  ] as const,
  name: "kerberos.org" as const,
  domain: "kerberos.org" as const,
  description: "Package information for kerberos.org" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/kerberos.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +kerberos.org -- $SHELL -i" as const,
}

export type KerberosorgPackage = typeof kerberosorgPackage
