import type { PkgxPackage } from '../types'

/**
 * kernelorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const kernelorgPackage: PkgxPackage = {
  name: "kernel.org",
  domain: "kernel.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx kernel.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface KernelorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "kernel.org";
  domain: "kernel.org";
  description: "Package information for kernel.org";
}