import type { khanacademyorgPackage } from '../types'

/**
 * khanacademyorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const khanacademyorgPackage: PkgxPackage = {
  "name": "khanacademy.org",
  "domain": "khanacademy.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx khanacademy.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface KhanacademyorgPackage {
  name: "khanacademy.org";
  domain: "khanacademy.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx khanacademy.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
