import type { PkgxPackage } from '../types'

/**
 * khronosorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const khronosorgPackage: PkgxPackage = {
  "name": "khronos.org",
  "domain": "khronos.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx khronos.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "khronos.org"
}

export interface KhronosorgPackage {
  name: "khronos.org";
  domain: "khronos.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx khronos.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "khronos.org";
}
