import type { khronosorgPackage } from '../types'

/**
 * khronosorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const khronosorgPackage: khronosorgPackage = {
  "name": "khronos.org",
  "domain": "khronos.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx khronos.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface khronosorgPackage {
  name: "khronos.org";
  domain: "khronos.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx khronos.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
