import type { kornelskiPackage } from '../types'

/**
 * kornelskiPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const kornelskiPackage: kornelskiPackage = {
  "name": "kornel.ski",
  "domain": "kornel.ski",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx kornel.ski",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface kornelskiPackage {
  name: "kornel.ski";
  domain: "kornel.ski";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx kornel.ski";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
