import type { PkgxPackage } from '../types'

/**
 * kornelskiPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const kornelskiPackage: PkgxPackage = {
  "name": "kornel.ski",
  "domain": "kornel.ski",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx kornel.ski",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "kornel.ski"
}
