export const kotlinlangorgPackage = {
  name: "kotlinlang.org" as const,
  domain: "kotlinlang.org" as const,
  description: "Statically typed programming language for the JVM" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/kotlinlang.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +kotlinlang.org -- $SHELL -i" as const,
  programs: [
    "kapt",
    "kotlin",
    "kotlinc",
    "kotlinc-js",
    "kotlinc-jvm",
  ] as const,
  companions: [] as const,
  dependencies: [
    "openjdk.org",
  ] as const,
  versions: [
    "2.1.21",
    "2.1.20",
    "2.1.10",
    "2.1.0",
    "2.0.21",
    "2.0.20",
    "2.0.10",
    "2.0.0",
    "1.9.25",
    "1.9.24",
    "1.9.23",
    "1.9.22",
    "1.9.21",
    "1.9.20",
    "1.9.10",
    "1.9.0",
  ] as const,
  fullPath: "kotlinlang.org" as const,
}

export type KotlinlangorgPackage = typeof kotlinlangorgPackage
