import type { PkgxPackage } from '../types'

/**
 * kubectxdevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const kubectxdevPackage: PkgxPackage = {
  name: "kube",
  domain: "kubectx.dev",
  description: "Tool that can switch between kubectl contexts easily and create aliases",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/kubectx.dev/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +kubectx.dev -- $SHELL -i",
  programs: [
    "kubectx",
    "kubens"
  ],
  companions: [],
  dependencies: ["github.com/junegunn/fzf"],
  versions: [
    "0.9.5",
    "0.9.4"
  ]
}

export interface KubectxdevPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "kubectx.dev";
  domain: "kubectx.dev";
  description: "Package information for kubectx.dev";
}
