import type { kubebuilderioPackage } from '../types'

/**
 * kubebuilderioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const kubebuilderioPackage: PkgxPackage = {
  "name": "kubebuilder",
  "domain": "kubebuilder.io",
  "description": "Kubebuilder - SDK for building Kubernetes APIs using CRDs",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/kubebuilder.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) kubebuilder",
  "programs": [
    "kubebuilder"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "4.5.2",
    "4.5.1",
    "4.5.0",
    "4.4.0",
    "4.3.1",
    "4.3.0",
    "4.2.0",
    "4.1.1",
    "4.1.0",
    "4.0.0",
    "3.15.1",
    "3.15.0",
    "3.14.2",
    "3.14.1",
    "3.14.0",
    "3.13.0",
    "3.12.0"
  ]
}

export interface KubebuilderioPackage {
  name: "kubebuilder";
  domain: "kubebuilder.io";
  description: "Kubebuilder - SDK for building Kubernetes APIs using CRDs";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/kubebuilder.io/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) kubebuilder";
  programs: readonly [
    "kubebuilder"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "4.5.2",
    "4.5.1",
    "4.5.0",
    "4.4.0",
    "4.3.1",
    "4.3.0",
    "4.2.0",
    "4.1.1",
    "4.1.0",
    "4.0.0",
    "3.15.1",
    "3.15.0",
    "3.14.2",
    "3.14.1",
    "3.14.0",
    "3.13.0",
    "3.12.0"
  ];
}
