import type { PkgxPackage } from '../types'

/**
 * kubernetesioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const kubernetesioPackage: PkgxPackage = {
  "name": "kubernetes.io",
  "domain": "kubernetes.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx kubernetes.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "kubernetes.io"
}

export interface KubernetesioPackage {
  name: "kubernetes.io";
  domain: "kubernetes.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx kubernetes.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "kubernetes.io";
}
