import type { ladspaorgPackage } from '../types'

/**
 * ladspaorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ladspaorgPackage: ladspaorgPackage = {
  "name": "ladspa.org",
  "domain": "ladspa.org",
  "description": "Linux Audio Developer's Simple Plugin",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/ladspa.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +ladspa.org -- $SHELL -i",
  "programs": [
    "analyseplugin",
    "applyplugin",
    "listplugins"
  ],
  "companions": [],
  "dependencies": [
    "github.com/libsndfile/libsndfile^1.2"
  ],
  "versions": [
    "1.17.0"
  ]
}

export interface ladspaorgPackage {
  name: "ladspa.org";
  domain: "ladspa.org";
  description: "Linux Audio Developer's Simple Plugin";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/ladspa.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +ladspa.org -- $SHELL -i";
  programs: readonly [
    "analyseplugin",
    "applyplugin",
    "listplugins"
  ];
  companions: readonly [];
  dependencies: readonly [
    "github.com/libsndfile/libsndfile^1.2"
  ];
  versions: readonly [
    "1.17.0"
  ];
}
