import type { PkgxPackage } from '../types'

/**
 * lamesourceforgeioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const lamesourceforgeioPackage: PkgxPackage = {
  "name": "lame",
  "domain": "lame.sourceforge.io",
  "description": "High quality MPEG Audio Layer III (MP3) encoder",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/lame.sourceforge.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) lame",
  "programs": [
    "lame"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "3.100.0"
  ],
  "fullPath": "lame.sourceforge.io"
}
