import type { PkgxPackage } from '../types'

/**
 * langchaincomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const langchaincomPackage: PkgxPackage = {
  "name": "langchain.com",
  "domain": "langchain.com",
  "description": "🦜🔗 Build context-aware reasoning applications",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/langchain.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +langchain.com -- $SHELL -i",
  "programs": [
    "f2py",
    "jsondiff",
    "jsonpatch",
    "jsonpointer",
    "langchain-server",
    "langsmith",
    "normalizer"
  ],
  "companions": [],
  "dependencies": [
    "python.org^3.12",
    "docker.com/compose^2.23"
  ],
  "versions": [
    "0.1.9",
    "0.1.8",
    "0.1.7",
    "0.1.6",
    "0.1.5",
    "0.1.4",
    "0.1.3",
    "0.1.2",
    "0.1.16",
    "0.1.15",
    "0.1.14",
    "0.1.13",
    "0.1.12",
    "0.1.11",
    "0.1.10",
    "0.1.1",
    "0.1.0",
    "0.0.354",
    "0.0.353",
    "0.0.352",
    "0.0.351",
    "0.0.350",
    "0.0.349",
    "0.0.348",
    "0.0.347",
    "0.0.346",
    "0.0.345",
    "0.0.344",
    "0.0.343"
  ]
}

export interface LangchaincomPackage {
  name: "langchain.com";
  domain: "langchain.com";
  description: "🦜🔗 Build context-aware reasoning applications";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/langchain.com/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +langchain.com -- $SHELL -i";
  programs: readonly [
    "f2py",
    "jsondiff",
    "jsonpatch",
    "jsonpointer",
    "langchain-server",
    "langsmith",
    "normalizer"
  ];
  companions: readonly [];
  dependencies: readonly [
    "python.org^3.12",
    "docker.com/compose^2.23"
  ];
  versions: readonly [
    "0.1.9",
    "0.1.8",
    "0.1.7",
    "0.1.6",
    "0.1.5",
    "0.1.4",
    "0.1.3",
    "0.1.2",
    "0.1.16",
    "0.1.15",
    "0.1.14",
    "0.1.13",
    "0.1.12",
    "0.1.11",
    "0.1.10",
    "0.1.1",
    "0.1.0",
    "0.0.354",
    "0.0.353",
    "0.0.352",
    "0.0.351",
    "0.0.350",
    "0.0.349",
    "0.0.348",
    "0.0.347",
    "0.0.346",
    "0.0.345",
    "0.0.344",
    "0.0.343"
  ];
}
