import type { leethomasongithubioPackage } from '../types'

/**
 * leethomasongithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const leethomasongithubioPackage: leethomasongithubioPackage = {
  "name": "leethomason.github.io",
  "domain": "leethomason.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx leethomason.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface leethomasongithubioPackage {
  name: "leethomason.github.io";
  domain: "leethomason.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx leethomason.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
