import type { PkgxPackage } from '../types'

/**
 * leethomasongithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const leethomasongithubioPackage: PkgxPackage = {
  name: "leethomason.github.io",
  domain: "leethomason.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx leethomason.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface LeethomasongithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "leethomasongithub.io";
  domain: "leethomasongithub.io";
  description: "Package information for leethomasongithub.io";
}