import type { PkgxPackage } from '../types'

/**
 * leolangorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const leolangorgPackage: PkgxPackage = {
  name: "leo",
  domain: "leo-lang.org",
  description: "🦁 The Leo Programming Language. A Programming Language for Formally Verified, Zero-Knowledge Applications",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/leo-lang.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) leo",
  programs: ["leo"],
  companions: [],
  dependencies: [
    "openssl.org^1.1",
    "curl.se^8.4"
  ],
  versions: [
    "2.6.0",
    "2.5.0",
    "2.4.1",
    "2.4.0",
    "2.3.1",
    "2.3.0",
    "2.2.0",
    "2.1.0",
    "2.0.0",
    "1.12.0",
    "1.11.0",
    "1.10.0"
  ]
}

export interface LeolangorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "leo/langorg";
  domain: "leo/langorg";
  description: "Package information for leo/langorg";
}
