import type { PkgxPackage } from '../types'

/**
 * leonerdorgukPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const leonerdorgukPackage: PkgxPackage = {
  "name": "leonerd.org.uk",
  "domain": "leonerd.org.uk",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx leonerd.org.uk",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "leonerd.org.uk"
}
