import type { leonerdorgukPackage } from '../types'

/**
 * leonerdorgukPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const leonerdorgukPackage: leonerdorgukPackage = {
  "name": "leonerd.org.uk",
  "domain": "leonerd.org.uk",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx leonerd.org.uk",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface leonerdorgukPackage {
  name: "leonerd.org.uk";
  domain: "leonerd.org.uk";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx leonerd.org.uk";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
