import type { PkgxPackage } from '../types'

/**
 * libislsourceforgeioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const libislsourceforgeioPackage: PkgxPackage = {
  "name": "libisl.sourceforge.io",
  "domain": "libisl.sourceforge.io",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/libisl.sourceforge.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +libisl.sourceforge.io -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [
    "gnu.org/gmp^6"
  ],
  "versions": [
    "0.27.0",
    "0.26.0"
  ],
  "fullPath": "libisl.sourceforge.io"
}

export interface LibislsourceforgeioPackage {
  name: "libisl.sourceforge.io";
  domain: "libisl.sourceforge.io";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/libisl.sourceforge.io/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +libisl.sourceforge.io -- $SHELL -i";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [
    "gnu.org/gmp^6"
  ];
  versions: readonly [
    "0.27.0",
    "0.26.0"
  ];
  fullPath: "libisl.sourceforge.io";
}
