import type { PkgxPackage } from '../types'

/**
 * libjpegturboorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const libjpegturboorgPackage: PkgxPackage = {
  name: "libjpeg-turbo.org",
  domain: "libjpeg-turbo.org",
  description: "Main libjpeg-turbo repository",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/libjpeg-turbo.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +libjpeg-turbo.org -- $SHELL -i",
  programs: [
    "cjpeg",
    "djpeg",
    "jpegtran",
    "rdjpgcom",
    "tjbench",
    "wrjpgcom"
  ],
  companions: [],
  dependencies: [],
  versions: [
    "3.1.0",
    "3.0.4",
    "3.0.3",
    "3.0.2",
    "3.0.1",
    "3.0.0",
    "2.1.5.1"
  ]
}

export interface LibjpegturboorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "libjpeg/turboorg";
  domain: "libjpeg/turboorg";
  description: "Package information for libjpeg/turboorg";
}
