import type { PkgxPackage } from '../types'

/**
 * liblqrwikidotcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const liblqrwikidotcomPackage: PkgxPackage = {
  name: "liblqr.wikidot.com",
  domain: "liblqr.wikidot.com",
  description: "Liquid Rescale library",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/liblqr.wikidot.com/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +liblqr.wikidot.com -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: ["gnome.org/glib"],
  versions: [
    "0.4.3",
    "0.4.2"
  ]
}

export interface LiblqrwikidotcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "liblqrwikidot.com";
  domain: "liblqrwikidot.com";
  description: "Package information for liblqrwikidot.com";
}