import type { PkgxPackage } from '../types'

/**
 * libpipelinegitlabioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const libpipelinegitlabioPackage: PkgxPackage = {
  "name": "libpipeline.gitlab.io",
  "domain": "libpipeline.gitlab.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx libpipeline.gitlab.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "libpipeline.gitlab.io"
}
