import type { PkgxPackage } from '../types'

/**
 * libsshorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const libsshorgPackage: PkgxPackage = {
  name: "libssh.org",
  domain: "libssh.org",
  description: "",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/libssh.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +libssh.org -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: [
    "openssl.org^1.1",
    "zlib.net^1"
  ],
  versions: [
    "0.11.1",
    "0.11.0",
    "0.10.6",
    "0.10.5",
    "0.10.4",
    "0.9.8",
    "0.9.7"
  ]
}

export interface LibsshorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "libssh.org";
  domain: "libssh.org";
  description: "Package information for libssh.org";
}
