import type { PkgxPackage } from '../types'

/**
 * libtomnetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const libtomnetPackage: PkgxPackage = {
  name: "libtom.net",
  domain: "libtom.net",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx libtom.net",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface LibtomnetPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "libtom.net";
  domain: "libtom.net";
  description: "Package information for libtom.net";
}
