import type { PkgxPackage } from '../types'

/**
 * libusbinfoPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const libusbinfoPackage: PkgxPackage = {
  name: "libusb.info",
  domain: "libusb.info",
  description: "A cross-platform library to access USB devices",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/libusb.info/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +libusb.info -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: [],
  versions: [
    "1.0.28",
    "1.0.27",
    "1.0.26"
  ]
}

export interface LibusbinfoPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "libusbinfo";
  domain: "libusbinfo";
  description: "Package information for libusbinfo";
}
