export const libvipsorgPackage = {
  name: "vips" as const,
  domain: "libvips.org" as const,
  description: "A fast image processing library with low memory needs." as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/libvips.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +libvips.org -- $SHELL -i" as const,
  programs: [
    "vips",
    "vipsedit",
    "vipsheader",
    "vipsprofile",
    "vipsthumbnail",
  ] as const,
  companions: [] as const,
  dependencies: [
    "mozilla.org/mozjpeg",
    "cairographics.org",
    "heasarc.gsfc.nasa.gov/cfitsio",
    "github.com/dloebl/cgif",
    "fftw.org",
    "freedesktop.org/fontconfig",
    "gnu.org/gettext",
    "gnome.org/glib",
    "graphicsmagick.org",
    "jpeg.org/jpegxl",
    "libexif.github.io",
    "gnome.org/libgsf",
    "github.com/strukturag/libheif",
    "pngquant.org/lib",
    "matio.sourceforge.io",
    "gnome.org/librsvg",
    "libspng.org",
    "simplesystems.org/libtiff",
    "littlecms.com",
    "openexr.com",
    "openjpeg.org",
    "gstreamer.freedesktop.org/orc",
    "gnome.org/pango",
    "poppler.freedesktop.org",
    "google.com/webp",
    "libexpat.github.io",
    "zlib.net",
  ] as const,
  versions: [
    "8.16.1",
    "8.16.0",
    "8.15.5",
    "8.15.3",
    "8.15.2",
    "8.15.1",
    "8.15.0",
    "8.14.5",
  ] as const,
  fullPath: "libvips.org" as const,
  aliases: [
    "vips",
  ] as const,
}

export type LibvipsorgPackage = typeof libvipsorgPackage
