import type { PkgxPackage } from '../types'

/**
 * linkerdioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const linkerdioPackage: PkgxPackage = {
  "name": "linkerd.io",
  "domain": "linkerd.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx linkerd.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "linkerd.io"
}
