import type { linkerdioPackage } from '../types'

/**
 * linkerdioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const linkerdioPackage: linkerdioPackage = {
  "name": "linkerd.io",
  "domain": "linkerd.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx linkerd.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface linkerdioPackage {
  name: "linkerd.io";
  domain: "linkerd.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx linkerd.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
