import type { PkgxPackage } from '../types'

/**
 * lloydgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const lloydgithubioPackage: PkgxPackage = {
  "name": "lloyd.github.io",
  "domain": "lloyd.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx lloyd.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface LloydgithubioPackage {
  name: "lloyd.github.io";
  domain: "lloyd.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx lloyd.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
