import type { localaiioPackage } from '../types'

/**
 * localaiioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const localaiioPackage: PkgxPackage = {
  "name": "LocalAI",
  "domain": "localai.io",
  "description": ":robot: The free, Open Source alternative to OpenAI, Claude and others. Self-hosted and local-first. Drop-in replacement for OpenAI,  running on consumer-grade hardware. No GPU required. Runs gguf, transformers, diffusers and many more models architectures. Features: Generate Text, Audio, Video, Images, Voice Cloning, Distributed, P2P inference",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/localai.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) local-ai",
  "programs": [
    "local-ai"
  ],
  "companions": [
    "linux"
  ],
  "dependencies": [
    "darwinopenmp.llvm.org@18",
    "openmp.llvm.org@18"
  ],
  "versions": [
    "2.9.0",
    "2.8.2",
    "2.8.1",
    "2.8.0",
    "2.7.0",
    "2.6.1",
    "2.26.0",
    "2.25.0",
    "2.24.2",
    "2.24.1",
    "2.24.0",
    "2.23.0",
    "2.22.1",
    "2.22.0",
    "2.21.1",
    "2.21.0",
    "2.20.1",
    "2.20.0",
    "2.19.4",
    "2.19.3",
    "2.19.2",
    "2.19.1",
    "2.19.0",
    "2.18.1",
    "2.18.0",
    "2.17.1",
    "2.17.0",
    "2.15.0",
    "2.14.0",
    "2.13.0",
    "2.12.4",
    "2.12.3",
    "2.12.1",
    "2.12.0",
    "2.11.0",
    "2.10.1",
    "2.10.0"
  ]
}

export interface LocalaiioPackage {
  name: "LocalAI";
  domain: "localai.io";
  description: ":robot: The free, Open Source alternative to OpenAI, Claude and others. Self-hosted and local-first. Drop-in replacement for OpenAI,  running on consumer-grade hardware. No GPU required. Runs gguf, transformers, diffusers and many more models architectures. Features: Generate Text, Audio, Video, Images, Voice Cloning, Distributed, P2P inference";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/localai.io/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) local-ai";
  programs: readonly [
    "local-ai"
  ];
  companions: readonly [
    "linux"
  ];
  dependencies: readonly [
    "darwinopenmp.llvm.org@18",
    "openmp.llvm.org@18"
  ];
  versions: readonly [
    "2.9.0",
    "2.8.2",
    "2.8.1",
    "2.8.0",
    "2.7.0",
    "2.6.1",
    "2.26.0",
    "2.25.0",
    "2.24.2",
    "2.24.1",
    "2.24.0",
    "2.23.0",
    "2.22.1",
    "2.22.0",
    "2.21.1",
    "2.21.0",
    "2.20.1",
    "2.20.0",
    "2.19.4",
    "2.19.3",
    "2.19.2",
    "2.19.1",
    "2.19.0",
    "2.18.1",
    "2.18.0",
    "2.17.1",
    "2.17.0",
    "2.15.0",
    "2.14.0",
    "2.13.0",
    "2.12.4",
    "2.12.3",
    "2.12.1",
    "2.12.0",
    "2.11.0",
    "2.10.1",
    "2.10.0"
  ];
}
