import type { PkgxPackage } from '../types'

/**
 * logdydevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const logdydevPackage: PkgxPackage = {
  name: "logdy",
  domain: "logdy.dev",
  description: "Web based real-time log viewer. Stream ANY content to a web UI with autogenerated filters. Parse any format with TypeScript.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/logdy.dev/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) logdy",
  programs: ["logdy"],
  companions: [],
  dependencies: [],
  versions: [
    "0.16.0",
    "0.15.0",
    "0.14.1",
    "0.14.0",
    "0.13.3",
    "0.13.2",
    "0.13.1",
    "0.13.0",
    "0.12.2",
    "0.12.0",
    "0.11.0",
    "0.10.0",
    "0.9.0"
  ]
}

export interface LogdydevPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "logdy.dev";
  domain: "logdy.dev";
  description: "Package information for logdy.dev";
}
