import type { PkgxPackage } from '../types'

/**
 * luaorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const luaorgPackage: PkgxPackage = {
  "name": "lua",
  "domain": "lua.org",
  "description": "Powerful, lightweight programming language",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/lua.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +lua.org -- $SHELL -i",
  "programs": [
    "lua",
    "luac"
  ],
  "companions": [
    "luarocks.org"
  ],
  "dependencies": [
    "gnu.org/readline"
  ],
  "versions": [
    "5.4.7",
    "5.4.6",
    "5.4.4"
  ],
  "fullPath": "lua.org"
}
