import type { PkgxPackage } from '../types'

/**
 * lz4orgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const lz4orgPackage: PkgxPackage = {
  name: "lz4",
  domain: "lz4.org",
  description: "Extremely Fast Compression algorithm",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/lz4.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) lz4",
  programs: ["lz4"],
  companions: [],
  dependencies: [],
  versions: [
    "1.10.0",
    "1.9.4"
  ]
}

export interface Lz4orgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "lz4.org";
  domain: "lz4.org";
  description: "Package information for lz4.org";
}
