import type { mariadbcomPackage } from '../types'

/**
 * mariadbcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mariadbcomPackage: PkgxPackage = {
  "name": "mariadb.com",
  "domain": "mariadb.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx mariadb.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface MariadbcomPackage {
  name: "mariadb.com";
  domain: "mariadb.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx mariadb.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
