import type { PkgxPackage } from '../types'

/**
 * mariadbcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mariadbcomPackage: PkgxPackage = {
  name: "mariadb.com",
  domain: "mariadb.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx mariadb.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface MariadbcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "mariadb.com";
  domain: "mariadb.com";
  description: "Package information for mariadb.com";
}