import type { PkgxPackage } from '../types'

/**
 * markupsafepalletsprojectscomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const markupsafepalletsprojectscomPackage: PkgxPackage = {
  name: "markupsafe.palletsprojects.com",
  domain: "markupsafe.palletsprojects.com",
  description: "Safely add untrusted strings to HTML/XML markup.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/markupsafe.palletsprojects.com/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +markupsafe.palletsprojects.com -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: ["python.org~3.11"],
  versions: [
    "3.0.2",
    "3.0.1",
    "3.0.0",
    "2.1.5",
    "2.1.4",
    "2.1.3"
  ]
}

export interface MarkupsafepalletsprojectscomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "markupsafepalletsprojects.com";
  domain: "markupsafepalletsprojects.com";
  description: "Package information for markupsafepalletsprojects.com";
}