export const maturinrsPackage = {
  name: 'maturin' as const,
  domain: 'maturin.rs' as const,
  description: 'Build and publish crates with pyo3, cffi and uniffi bindings as well as rust binaries as python packages' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/maturin.rs/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) maturin' as const,
  programs: [
    'maturin',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '1.8.6',
    '1.8.5',
    '1.8.3',
    '1.8.2',
    '1.8.1',
    '1.8.0',
    '1.7.8',
    '1.7.7',
    '1.7.6',
    '1.7.5',
    '1.7.4',
    '1.7.3',
    '1.7.2',
    '1.7.1',
    '1.7.0',
    '1.6.0',
    '1.5.1',
    '1.5.0',
    '1.4.0',
  ] as const,
  fullPath: 'maturin.rs' as const,
  aliases: [] as const,
}

export type MaturinrsPackage = typeof maturinrsPackage
