import type { PkgxPackage } from '../types'

/**
 * maturinrsPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const maturinrsPackage: PkgxPackage = {
  name: "maturin",
  domain: "maturin.rs",
  description: "Build and publish crates with pyo3, cffi and uniffi bindings as well as rust binaries as python packages",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/maturin.rs/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) maturin",
  programs: ["maturin"],
  companions: [],
  dependencies: [],
  versions: [
    "1.8.6",
    "1.8.5",
    "1.8.3",
    "1.8.2",
    "1.8.1",
    "1.8.0",
    "1.7.8",
    "1.7.7",
    "1.7.6",
    "1.7.5",
    "1.7.4",
    "1.7.3",
    "1.7.2",
    "1.7.1",
    "1.7.0",
    "1.6.0",
    "1.5.1",
    "1.5.0",
    "1.4.0"
  ]
}

export interface MaturinrsPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "maturinrs";
  domain: "maturinrs";
  description: "Package information for maturinrs";
}