import type { mavenapacheorgPackage } from '../types'

/**
 * mavenapacheorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mavenapacheorgPackage: PkgxPackage = {
  "name": "mvn",
  "domain": "maven.apache.org",
  "description": "Java-based project management",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/maven.apache.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +maven.apache.org -- $SHELL -i",
  "programs": [
    "mvn",
    "mvnDebug",
    "mvnyjp"
  ],
  "companions": [],
  "dependencies": [
    "openjdk.org"
  ],
  "versions": [
    "3.9.9",
    "3.9.8",
    "3.9.7",
    "3.9.6",
    "3.9.5",
    "3.9.4",
    "3.9.3",
    "3.8.7",
    "3.6.3"
  ]
}

export interface MavenapacheorgPackage {
  name: "mvn";
  domain: "maven.apache.org";
  description: "Java-based project management";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/maven.apache.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +maven.apache.org -- $SHELL -i";
  programs: readonly [
    "mvn",
    "mvnDebug",
    "mvnyjp"
  ];
  companions: readonly [];
  dependencies: readonly [
    "openjdk.org"
  ];
  versions: readonly [
    "3.9.9",
    "3.9.8",
    "3.9.7",
    "3.9.6",
    "3.9.5",
    "3.9.4",
    "3.9.3",
    "3.8.7",
    "3.6.3"
  ];
}
