import type { PkgxPackage } from '../types'

/**
 * mcmcjagssourceforgeioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mcmcjagssourceforgeioPackage: PkgxPackage = {
  name: "jags",
  domain: "mcmc-jags.sourceforge.io",
  description: "Just Another Gibbs Sampler for Bayesian MCMC simulation",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/mcmc-jags.sourceforge.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) jags",
  programs: ["jags"],
  companions: [],
  dependencies: [
    "gnu.org/gcc",
    "linuxnetlib.org/lapack^3",
    "netlib.org/lapack^3"
  ],
  versions: ["4.3.2"]
}

export interface McmcjagssourceforgeioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "mcmc/jagssourceforgeio";
  domain: "mcmc/jagssourceforgeio";
  description: "Package information for mcmc/jagssourceforgeio";
}