export const mesonbuildcomPackage = {
  name: 'meson' as const,
  domain: 'mesonbuild.com' as const,
  description: 'Fast and user friendly build system' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/mesonbuild.com/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) meson' as const,
  programs: [
    'meson',
  ] as const,
  companions: [] as const,
  dependencies: [
    'pkgx.sh^1',
  ] as const,
  versions: [
    '1.8.1',
    '1.8.0',
    '1.7.2',
    '1.7.1',
    '1.7.0',
    '1.6.1',
    '1.6.0',
    '1.5.2',
    '1.5.1',
    '1.5.0',
    '1.4.2',
    '1.4.1',
    '1.4.0',
    '1.3.2',
    '1.3.1',
    '1.3.0',
    '1.2.3',
    '1.2.2',
    '1.2.0',
    '1.1.1',
    '1.1.0',
    '1.0.2',
    '1.0.1',
    '1.0.0',
    '0.64.1',
    '0.64.0',
    '0.63.3',
  ] as const,
  fullPath: 'mesonbuild.com' as const,
  aliases: [] as const,
}

export type MesonbuildcomPackage = typeof mesonbuildcomPackage
