import type { microbreworgPackage } from '../types'

/**
 * microbreworgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const microbreworgPackage: microbreworgPackage = {
  "name": "microbrew.org",
  "domain": "microbrew.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx microbrew.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface microbreworgPackage {
  name: "microbrew.org";
  domain: "microbrew.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx microbrew.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
