import type { PkgxPackage } from '../types'

/**
 * microbreworgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const microbreworgPackage: PkgxPackage = {
  name: "microbrew.org",
  domain: "microbrew.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx microbrew.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface MicrobreworgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "microbrew.org";
  domain: "microbrew.org";
  description: "Package information for microbrew.org";
}