import type { microsoftcomPackage } from '../types'

/**
 * microsoftcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const microsoftcomPackage: PkgxPackage = {
  "name": "microsoft.com",
  "domain": "microsoft.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx microsoft.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface MicrosoftcomPackage {
  name: "microsoft.com";
  domain: "microsoft.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx microsoft.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
