import type { minioPackage } from '../types'

/**
 * minioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const minioPackage: minioPackage = {
  "name": "minio",
  "domain": "min.io",
  "description": "MinIO is a high-performance, S3 compatible object store, open sourced under GNU AGPLv3 license.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/min.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) minio",
  "programs": [
    "minio"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "2023.10.25.6.33.25"
  ]
}

export interface minioPackage {
  name: "minio";
  domain: "min.io";
  description: "MinIO is a high-performance, S3 compatible object store, open sourced under GNU AGPLv3 license.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/min.io/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) minio";
  programs: readonly [
    "minio"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "2023.10.25.6.33.25"
  ];
}
