export const mitmproxyorgPackage = {
  name: "mitmproxy" as const,
  domain: "mitmproxy.org" as const,
  description: "An interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers." as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/mitmproxy.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) mitmproxy" as const,
  programs: [
    "mitmproxy",
  ] as const,
  companions: [] as const,
  dependencies: [
    "pkgx.sh^1",
  ] as const,
  versions: [
    "12.0.1",
    "12.0.0",
    "11.1.3",
    "11.1.2",
    "11.1.1",
    "11.1.0",
    "11.0.2",
    "11.0.1",
    "11.0.0",
    "10.4.2",
    "10.4.1",
    "10.4.0",
    "10.3.0",
    "10.2.4",
    "10.2.3",
    "10.2.2",
    "10.2.1",
    "10.2.0",
    "10.1.6",
    "10.1.5",
    "10.1.4",
    "10.1.3",
    "10.1.2",
    "10.1.1",
    "10.1.0",
  ] as const,
  fullPath: "mitmproxy.org" as const,
}

export type MitmproxyorgPackage = typeof mitmproxyorgPackage
