import type { mitmproxyorgPackage } from '../types'

/**
 * mitmproxyorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mitmproxyorgPackage: mitmproxyorgPackage = {
  "name": "mitmproxy",
  "domain": "mitmproxy.org",
  "description": "An interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/mitmproxy.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) mitmproxy",
  "programs": [
    "mitmproxy"
  ],
  "companions": [],
  "dependencies": [
    "pkgx.sh^1"
  ],
  "versions": [
    "12.0.1",
    "12.0.0",
    "11.1.3",
    "11.1.2",
    "11.1.1",
    "11.1.0",
    "11.0.2",
    "11.0.1",
    "11.0.0",
    "10.4.2",
    "10.4.1",
    "10.4.0",
    "10.3.0",
    "10.2.4",
    "10.2.3",
    "10.2.2",
    "10.2.1",
    "10.2.0",
    "10.1.6",
    "10.1.5",
    "10.1.4",
    "10.1.3",
    "10.1.2",
    "10.1.1",
    "10.1.0"
  ]
}

export interface mitmproxyorgPackage {
  name: "mitmproxy";
  domain: "mitmproxy.org";
  description: "An interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/mitmproxy.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) mitmproxy";
  programs: readonly [
    "mitmproxy"
  ];
  companions: readonly [];
  dependencies: readonly [
    "pkgx.sh^1"
  ];
  versions: readonly [
    "12.0.1",
    "12.0.0",
    "11.1.3",
    "11.1.2",
    "11.1.1",
    "11.1.0",
    "11.0.2",
    "11.0.1",
    "11.0.0",
    "10.4.2",
    "10.4.1",
    "10.4.0",
    "10.3.0",
    "10.2.4",
    "10.2.3",
    "10.2.2",
    "10.2.1",
    "10.2.0",
    "10.1.6",
    "10.1.5",
    "10.1.4",
    "10.1.3",
    "10.1.2",
    "10.1.1",
    "10.1.0"
  ];
}
