import type { moonrepodevPackage } from '../types'

/**
 * moonrepodevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const moonrepodevPackage: PkgxPackage = {
  "name": "moonrepo.dev",
  "domain": "moonrepo.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx moonrepo.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface MoonrepodevPackage {
  name: "moonrepo.dev";
  domain: "moonrepo.dev";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx moonrepo.dev";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
