import type { moshorgPackage } from '../types'

/**
 * moshorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const moshorgPackage: PkgxPackage = {
  "name": "mosh",
  "domain": "mosh.org",
  "description": "Remote terminal application",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/mosh.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +mosh.org -- $SHELL -i",
  "programs": [
    "mosh-client",
    "mosh-server"
  ],
  "companions": [],
  "dependencies": [
    "protobuf.dev@26.1.0",
    "invisible-island.net/ncurses@6",
    "zlib.net@1.3",
    "linuxopenssl.org@3",
    "openssl.org@3"
  ],
  "versions": [
    "1.4.0"
  ]
}

export interface MoshorgPackage {
  name: "mosh";
  domain: "mosh.org";
  description: "Remote terminal application";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/mosh.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +mosh.org -- $SHELL -i";
  programs: readonly [
    "mosh-client",
    "mosh-server"
  ];
  companions: readonly [];
  dependencies: readonly [
    "protobuf.dev@26.1.0",
    "invisible-island.net/ncurses@6",
    "zlib.net@1.3",
    "linuxopenssl.org@3",
    "openssl.org@3"
  ];
  versions: readonly [
    "1.4.0"
  ];
}
