import type { mozillaorgPackage } from '../types'

/**
 * mozillaorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mozillaorgPackage: mozillaorgPackage = {
  "name": "mozilla.org",
  "domain": "mozilla.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx mozilla.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface mozillaorgPackage {
  name: "mozilla.org";
  domain: "mozilla.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx mozilla.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
