import type { PkgxPackage } from '../types'

/**
 * mpmathorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mpmathorgPackage: PkgxPackage = {
  name: "mpmath.org",
  domain: "mpmath.org",
  description: "",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/mpmath.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +mpmath.org -- $SHELL -i",
  programs: [],
  companions: [],
  dependencies: ["python.org~3.11"],
  versions: ["1.3.0"]
}

export interface MpmathorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "mpmath.org";
  domain: "mpmath.org";
  description: "Package information for mpmath.org";
}
