import type { musllibcorgPackage } from '../types'

/**
 * musllibcorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const musllibcorgPackage: musllibcorgPackage = {
  "name": "musl.libc.org",
  "domain": "musl.libc.org",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/musl.libc.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +musl.libc.org -- $SHELL -i",
  "programs": [
    "ld.musl-clang",
    "musl-clang"
  ],
  "companions": [],
  "dependencies": [
    "llvm.org"
  ],
  "versions": [
    "1.2.3"
  ]
}

export interface musllibcorgPackage {
  name: "musl.libc.org";
  domain: "musl.libc.org";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/musl.libc.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +musl.libc.org -- $SHELL -i";
  programs: readonly [
    "ld.musl-clang",
    "musl-clang"
  ];
  companions: readonly [];
  dependencies: readonly [
    "llvm.org"
  ];
  versions: readonly [
    "1.2.3"
  ];
}
