import type { mvdanccPackage } from '../types'

/**
 * mvdanccPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mvdanccPackage: mvdanccPackage = {
  "name": "mvdan.cc",
  "domain": "mvdan.cc",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx mvdan.cc",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface mvdanccPackage {
  name: "mvdan.cc";
  domain: "mvdan.cc";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx mvdan.cc";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
