import type { mypylangorgPackage } from '../types'

/**
 * mypylangorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const mypylangorgPackage: mypylangorgPackage = {
  "name": "mypy-lang.org",
  "domain": "mypy-lang.org",
  "description": "Experimental optional static type checker for Python",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/mypy-lang.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +mypy-lang.org -- $SHELL -i",
  "programs": [
    "mypy",
    "mypyc",
    "dmypy"
  ],
  "companions": [],
  "dependencies": [
    "pkgx.sh^1"
  ],
  "versions": [
    "1.9.0",
    "1.8.0",
    "1.7.1",
    "1.7.0",
    "1.6.1",
    "1.6.0",
    "1.5.1",
    "1.5.0",
    "1.4.1",
    "1.4.0",
    "1.3.0",
    "1.2.0",
    "1.15.0",
    "1.14.1",
    "1.14.0",
    "1.13.0",
    "1.12.1",
    "1.12.0",
    "1.11.2",
    "1.11.1",
    "1.11.0",
    "1.10.1",
    "1.10.0"
  ],
  "fullPath": "mypy-lang.org"
}

export interface mypylangorgPackage {
  name: "mypy-lang.org";
  domain: "mypy-lang.org";
  description: "Experimental optional static type checker for Python";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/mypy-lang.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +mypy-lang.org -- $SHELL -i";
  programs: readonly [
    "mypy",
    "mypyc",
    "dmypy"
  ];
  companions: readonly [];
  dependencies: readonly [
    "pkgx.sh^1"
  ];
  versions: readonly [
    "1.9.0",
    "1.8.0",
    "1.7.1",
    "1.7.0",
    "1.6.1",
    "1.6.0",
    "1.5.1",
    "1.5.0",
    "1.4.1",
    "1.4.0",
    "1.3.0",
    "1.2.0",
    "1.15.0",
    "1.14.1",
    "1.14.0",
    "1.13.0",
    "1.12.1",
    "1.12.0",
    "1.11.2",
    "1.11.1",
    "1.11.0",
    "1.10.1",
    "1.10.0"
  ];
  fullPath: "mypy-lang.org";
}
