import type { PkgxPackage } from '../types'

/**
 * netflixcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const netflixcomPackage: PkgxPackage = {
  "name": "netflix.com",
  "domain": "netflix.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx netflix.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "netflix.com"
}
