/**
 * **netpbm.sourceforge** - Image manipulation
 *
 * @domain `netpbm.sourceforge.net`
 * @programs `411toppm`, `asciitopgm`, `atktopbm`, `avstopam`, `bioradtopgm`, ... (+310 more)
 * @version `10.86.48` (12 versions available)
 * @versions From newest version to oldest.
 *
 * @install `launchpad install netpbm.sourceforge.net`
 * @homepage https://netpbm.sourceforge.net/
 * @dependencies `github.com/jasper-software/jasper`, `libjpeg-turbo.org`, `libpng.org`, ... (+3 more)
 * @buildDependencies `gnu.org/make`, `github.com/westes/flex`, `linux:perl.org` (includes OS-specific dependencies with `os:package` format) - required only when building from source
 *
 * @example
 * ```typescript
 * import { pantry } from 'ts-pkgx'
 *
 * const pkg = pantry.netpbmsourceforgenet
 * console.log(pkg.name)        // "netpbm.sourceforge"
 * console.log(pkg.description) // "Image manipulation"
 * console.log(pkg.programs)    // ["411toppm", "asciitopgm", ...]
 * console.log(pkg.versions[0]) // "10.86.48" (latest)
 * ```
 *
 * @see https://ts-pkgx.netlify.app/packages/netpbm-sourceforge-net.md
 * @see https://ts-pkgx.netlify.app/usage
 */
export const netpbmsourceforgenetPackage = {
  /**
   * The display name of this package.
   */
  name: 'netpbm.sourceforge' as const,
  /**
   * The canonical domain name for this package.
   */
  domain: 'netpbm.sourceforge.net' as const,
  /**
   * Brief description of what this package does.
   */
  description: 'Image manipulation' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/netpbm.sourceforge.net/package.yml' as const,
  homepageUrl: 'https://netpbm.sourceforge.net/' as const,
  githubUrl: '' as const,
  /**
   * Command to install this package using launchpad.
   * @example launchpad install package-name
   */
  installCommand: 'launchpad install netpbm.sourceforge.net' as const,
  pkgxInstallCommand: 'sh <(curl https://pkgx.sh) +netpbm.sourceforge.net -- $SHELL -i' as const,
  launchpadInstallCommand: 'launchpad install netpbm.sourceforge.net' as const,
  /**
   * Executable programs provided by this package.
   * These can be run after installation.
   */
  programs: [
    '411toppm',
    'asciitopgm',
    'atktopbm',
    'avstopam',
    'bioradtopgm',
    'bmptopnm',
    'brushtopbm',
    'cameratopam',
    'cistopbm',
    'cmuwmtopbm',
    'ddbugtopbm',
    'escp2topbm',
    'eyuvtoppm',
    'fiascotopnm',
    'fitstopnm',
    'fstopgm',
    'gemtopnm',
    'giftopnm',
    'gouldtoppm',
    'hdifftopam',
    'hipstopgm',
    'ilbmtoppm',
    'imgtoppm',
    'infotopam',
    'jbigtopnm',
    'jpeg2ktopam',
    'jpegtopnm',
    'leaftoppm',
    'lispmtopgm',
    'macptopbm',
    'mdatopbm',
    'mgrtopbm',
    'mrftopbm',
    'mtvtoppm',
    'neotoppm',
    'palmtopnm',
    'pamaddnoise',
    'pamarith',
    'pambackground',
    'pambayer',
    'pamchannel',
    'pamcomp',
    'pamcrater',
    'pamcut',
    'pamdeinterlace',
    'pamdepth',
    'pamdice',
    'pamditherbw',
    'pamedge',
    'pamendian',
    'pamenlarge',
    'pamexec',
    'pamfile',
    'pamfix',
    'pamflip',
    'pamfunc',
    'pamgauss',
    'pamgradient',
    'pamlookup',
    'pammasksharpen',
    'pammixinterlace',
    'pammosaicknit',
    'pamoil',
    'pampaintspill',
    'pamperspective',
    'pampick',
    'pampop9',
    'pamrecolor',
    'pamrubber',
    'pamscale',
    'pamseq',
    'pamshadedrelief',
    'pamsharpmap',
    'pamsharpness',
    'pamsistoaglyph',
    'pamslice',
    'pamsplit',
    'pamstack',
    'pamstereogram',
    'pamstretch',
    'pamsumm',
    'pamsummcol',
    'pamthreshold',
    'pamtilt',
    'pamtoavs',
    'pamtodjvurle',
    'pamtofits',
    'pamtogif',
    'pamtohdiff',
    'pamtohtmltbl',
    'pamtojpeg2k',
    'pamtompfont',
    'pamtooctaveimg',
    'pamtopam',
    'pamtopdbimg',
    'pamtopfm',
    'pamtopng',
    'pamtopnm',
    'pamtosrf',
    'pamtosvg',
    'pamtotga',
    'pamtotiff',
    'pamtouil',
    'pamtowinicon',
    'pamtoxvmini',
    'pamundice',
    'pamunlookup',
    'pamvalidate',
    'pamwipeout',
    'pbmclean',
    'pbmlife',
    'pbmmake',
    'pbmmask',
    'pbmminkowski',
    'pbmpage',
    'pbmpscale',
    'pbmreduce',
    'pbmtext',
    'pbmtextps',
    'pbmto10x',
    'pbmto4425',
    'pbmtoascii',
    'pbmtoatk',
    'pbmtobbnbg',
    'pbmtocis',
    'pbmtocmuwm',
    'pbmtodjvurle',
    'pbmtoepsi',
    'pbmtoepson',
    'pbmtoescp2',
    'pbmtog3',
    'pbmtogem',
    'pbmtogo',
    'pbmtoibm23xx',
    'pbmtolj',
    'pbmtoln03',
    'pbmtolps',
    'pbmtomacp',
    'pbmtomatrixorbital',
    'pbmtomda',
    'pbmtomgr',
    'pbmtomrf',
    'pbmtonokia',
    'pbmtopgm',
    'pbmtopi3',
    'pbmtopk',
    'pbmtoplot',
    'pbmtoppa',
    'pbmtopsg3',
    'pbmtoptx',
    'pbmtosunicon',
    'pbmtowbmp',
    'pbmtoxbm',
    'pbmtoybm',
    'pbmtozinc',
    'pc1toppm',
    'pcxtoppm',
    'pdbimgtopam',
    'pfmtopam',
    'pgmabel',
    'pgmbentley',
    'pgmdeshadow',
    'pgmenhance',
    'pgmhist',
    'pgmkernel',
    'pgmmake',
    'pgmmedian',
    'pgmminkowski',
    'pgmmorphconv',
    'pgmnoise',
    'pgmramp',
    'pgmtexture',
    'pgmtofs',
    'pgmtolispm',
    'pgmtopbm',
    'pgmtopgm',
    'pgmtoppm',
    'pgmtosbig',
    'pgmtost4',
    'pi1toppm',
    'pi3topbm',
    'picttoppm',
    'pjtoppm',
    'pktopbm',
    'pngtopam',
    'pnmalias',
    'pnmcat',
    'pnmcolormap',
    'pnmconvol',
    'pnmcrop',
    'pnmgamma',
    'pnmhisteq',
    'pnmhistmap',
    'pnmindex',
    'pnminvert',
    'pnmmercator',
    'pnmmontage',
    'pnmnlfilt',
    'pnmnorm',
    'pnmpad',
    'pnmpaste',
    'pnmpsnr',
    'pnmremap',
    'pnmrotate',
    'pnmscalefixed',
    'pnmshear',
    'pnmsmooth',
    'pnmstitch',
    'pnmtile',
    'pnmtoddif',
    'pnmtofiasco',
    'pnmtojbig',
    'pnmtojpeg',
    'pnmtopalm',
    'pnmtopclxl',
    'pnmtopng',
    'pnmtops',
    'pnmtorast',
    'pnmtorle',
    'pnmtosgi',
    'pnmtosir',
    'pnmtotiffcmyk',
    'pnmtoxwd',
    'ppm3d',
    'ppmbrighten',
    'ppmchange',
    'ppmcie',
    'ppmcolormask',
    'ppmcolors',
    'ppmdcfont',
    'ppmdim',
    'ppmdist',
    'ppmdither',
    'ppmdmkfont',
    'ppmdraw',
    'ppmflash',
    'ppmforge',
    'ppmglobe',
    'ppmhist',
    'ppmlabel',
    'ppmmake',
    'ppmmix',
    'ppmntsc',
    'ppmpat',
    'ppmrelief',
    'ppmrough',
    'ppmshift',
    'ppmspread',
    'ppmtoacad',
    'ppmtoapplevol',
    'ppmtoarbtxt',
    'ppmtoascii',
    'ppmtobmp',
    'ppmtoeyuv',
    'ppmtogif',
    'ppmtoicr',
    'ppmtoilbm',
    'ppmtoleaf',
    'ppmtolj',
    'ppmtomitsu',
    'ppmtompeg',
    'ppmtoneo',
    'ppmtopcx',
    'ppmtopgm',
    'ppmtopi1',
    'ppmtopict',
    'ppmtopj',
    'ppmtopjxl',
    'ppmtoppm',
    'ppmtopuzz',
    'ppmtorgb3',
    'ppmtosixel',
    'ppmtospu',
    'ppmtoterm',
    'ppmtowinicon',
    'ppmtoxpm',
    'ppmtoyuv',
    'ppmtoyuvsplit',
    'ppmtv',
    'psidtopgm',
    'pstopnm',
    'qrttoppm',
    'rasttopnm',
    'rawtopgm',
    'rawtoppm',
    'rgb3toppm',
    'rlatopam',
    'rletopnm',
    'sbigtopgm',
    'sgitopnm',
    'sirtopnm',
    'sldtoppm',
    'spctoppm',
    'spottopgm',
    'sputoppm',
    'srftopam',
    'st4topgm',
    'sunicontopnm',
    'svgtopam',
    'tgatoppm',
    'thinkjettopbm',
    'tifftopnm',
    'wbmptopbm',
    'winicontopam',
    'winicontoppm',
    'xbmtopbm',
    'ximtoppm',
    'xpmtoppm',
    'xvminitoppm',
    'xwdtopnm',
    'ybmtopbm',
    'yuvsplittoppm',
    'yuvtoppm',
    'yuy2topam',
    'zeisstopnm',
  ] as const,
  companions: [] as const,
  /**
   * Runtime dependencies for this package.
   * These are required when running the package.
   */
  dependencies: [
    'github.com/jasper-software/jasper',
    'libjpeg-turbo.org',
    'libpng.org',
    'simplesystems.org/libtiff',
    'gnome.org/libxml2',
    'zlib.net',
  ] as const,
  /**
   * Build dependencies for this package.
   * These are only required when building the package from source.
   * OS-specific dependencies are prefixed with `os:` (e.g., `linux:gnu.org/gcc`).
   */
  buildDependencies: [
    'gnu.org/make',
    'github.com/westes/flex',
    'linux:perl.org',
  ] as const,
  /**
   * Available versions from newest to oldest.
   * @see https://ts-pkgx.netlify.app/usage for installation instructions
   */
  versions: [
    '10.86.48',
    '10.86.47',
    '10.86.46',
    '10.86.45',
    '10.86.44',
    '10.86.43',
    '10.86.42',
    '10.86.41',
    '10.86.40',
    '10.86.39',
    '10.86.38',
    '10.73.43',
  ] as const,
  aliases: [] as const,
}

export type NetpbmsourceforgenetPackage = typeof netpbmsourceforgenetPackage
