import type { nikecomPackage } from '../types'

/**
 * nikecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const nikecomPackage: nikecomPackage = {
  "name": "nike.com",
  "domain": "nike.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx nike.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface nikecomPackage {
  name: "nike.com";
  domain: "nike.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx nike.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
