export const nimlangorgPackage = {
  name: 'nim-lang.org' as const,
  domain: 'nim-lang.org' as const,
  description: 'Nim is a statically typed compiled systems programming language. It combines successful concepts from mature languages like Python, Ada and Modula. Its design focuses on efficiency, expressiveness, and elegance (in that order of priority).' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/nim-lang.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +nim-lang.org -- $SHELL -i' as const,
  programs: [
    'nim',
    'nim_dbg',
    'testament',
    'nimsuggest',
    'nimgrep',
    'nim-gdb',
    'atlas',
    'nimpretty',
    'nimble',
  ] as const,
  companions: [] as const,
  dependencies: [
    'gnu.org/gcc',
    'pcre.org',
    'openssl.org',
  ] as const,
  versions: [
    '2.2.4',
    '2.2.2',
    '2.2.0',
    '2.0.16',
    '2.0.14',
    '2.0.12',
    '2.0.8',
    '2.0.6',
    '2.0.4',
    '2.0.2',
    '2.0.0',
    '1.6.20',
    '1.6.18',
    '1.6.16',
    '1.6.14',
  ] as const,
  fullPath: 'nim-lang.org' as const,
  aliases: [] as const,
}

export type NimlangorgPackage = typeof nimlangorgPackage
