import type { PkgxPackage } from '../types'

/**
 * ninjabuildorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ninjabuildorgPackage: PkgxPackage = {
  name: "ninja",
  domain: "ninja-build.org",
  description: "Small build system for use with gyp or CMake",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/ninja-build.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) ninja",
  programs: ["ninja"],
  companions: [],
  dependencies: [],
  versions: [
    "1.12.1",
    "1.12.0",
    "1.11.1",
    "1.11.0"
  ]
}

export interface NinjabuildorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "ninja/buildorg";
  domain: "ninja/buildorg";
  description: "Package information for ninja/buildorg";
}