import type { nixosorgPackage } from '../types'

/**
 * nixosorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const nixosorgPackage: nixosorgPackage = {
  "name": "nixos.org",
  "domain": "nixos.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx nixos.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface nixosorgPackage {
  name: "nixos.org";
  domain: "nixos.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx nixos.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
