import type { PkgxPackage } from '../types'

/**
 * notrojgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const notrojgithubioPackage: PkgxPackage = {
  "name": "notroj.github.io",
  "domain": "notroj.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx notroj.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "notroj.github.io"
}
