import type { PkgxPackage } from '../types'

/**
 * oauth2proxygithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const oauth2proxygithubioPackage: PkgxPackage = {
  name: "oauth2-proxy",
  domain: "oauth2-proxy.github.io",
  description: "A reverse proxy that provides authentication with Google, Azure, OpenID Connect and many more identity providers.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/oauth2-proxy.github.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) oauth2-proxy",
  programs: ["oauth2-proxy"],
  companions: [],
  dependencies: [],
  versions: [
    "7.9.0",
    "7.8.2",
    "7.8.1",
    "7.8.0",
    "7.7.1",
    "7.7.0",
    "7.6.0"
  ]
}

export interface Oauth2proxygithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "oauth2/proxygithubio";
  domain: "oauth2/proxygithubio";
  description: "Package information for oauth2/proxygithubio";
}
