import type { PkgxPackage } from '../types'

/**
 * openaicomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const openaicomPackage: PkgxPackage = {
  "name": "openai.com",
  "domain": "openai.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx openai.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface OpenaicomPackage {
  name: "openai.com";
  domain: "openai.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx openai.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
