import type { PkgxPackage } from '../types'

/**
 * openldaporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const openldaporgPackage: PkgxPackage = {
  name: "ldap",
  domain: "openldap.org",
  description: "Open source suite of directory software",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/openldap.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +openldap.org -- $SHELL -i",
  programs: [
    "ldapcompare",
    "ldapdelete",
    "ldapexop",
    "ldapmodify",
    "ldapmodrdn",
    "ldappasswd",
    "ldapsearch",
    "ldapurl",
    "ldapvc",
    "ldapwhoami"
  ],
  companions: [],
  dependencies: [
    "openssl.org^1.1",
    "linuxgithub.com/util-linux/util-linux",
    "github.com/util-linux/util-linux"
  ],
  versions: [
    "2.6.9",
    "2.6.8",
    "2.6.7",
    "2.6.6",
    "2.6.5",
    "2.6.4",
    "2.5.19",
    "2.5.18",
    "2.5.17",
    "2.5.16",
    "2.5.15"
  ]
}

export interface OpenldaporgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "openldap.org";
  domain: "openldap.org";
  description: "Package information for openldap.org";
}