import type { PkgxPackage } from '../types'

/**
 * openbaoorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const openbaoorgPackage: PkgxPackage = {
  name: "openbao.org",
  domain: "openbao.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx openbao.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface OpenbaoorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "openbao.org";
  domain: "openbao.org";
  description: "Package information for openbao.org";
}
