import type { openmpllvmorgPackage } from '../types'

/**
 * openmpllvmorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const openmpllvmorgPackage: openmpllvmorgPackage = {
  "name": "libomp",
  "domain": "openmp.llvm.org",
  "description": "The LLVM Project is a collection of modular and reusable compiler and toolchain technologies.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/openmp.llvm.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +openmp.llvm.org -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [
    "20.1.5",
    "20.1.4",
    "20.1.3",
    "20.1.2",
    "20.1.1",
    "20.1.0",
    "19.1.7",
    "19.1.6",
    "19.1.5",
    "19.1.4",
    "19.1.3",
    "19.1.2",
    "19.1.1",
    "19.1.0",
    "18.1.8",
    "18.1.7",
    "18.1.6",
    "18.1.5",
    "18.1.4",
    "18.1.3",
    "18.1.2",
    "18.1.1",
    "18.1.0",
    "17.0.6",
    "17.0.5",
    "17.0.4",
    "17.0.3",
    "17.0.2",
    "17.0.1",
    "17.0.0",
    "16.0.6"
  ]
}

export interface openmpllvmorgPackage {
  name: "libomp";
  domain: "openmp.llvm.org";
  description: "The LLVM Project is a collection of modular and reusable compiler and toolchain technologies.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/openmp.llvm.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +openmp.llvm.org -- $SHELL -i";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "20.1.5",
    "20.1.4",
    "20.1.3",
    "20.1.2",
    "20.1.1",
    "20.1.0",
    "19.1.7",
    "19.1.6",
    "19.1.5",
    "19.1.4",
    "19.1.3",
    "19.1.2",
    "19.1.1",
    "19.1.0",
    "18.1.8",
    "18.1.7",
    "18.1.6",
    "18.1.5",
    "18.1.4",
    "18.1.3",
    "18.1.2",
    "18.1.1",
    "18.1.0",
    "17.0.6",
    "17.0.5",
    "17.0.4",
    "17.0.3",
    "17.0.2",
    "17.0.1",
    "17.0.0",
    "16.0.6"
  ];
}
