import type { openprintinggithubioPackage } from '../types'

/**
 * openprintinggithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const openprintinggithubioPackage: openprintinggithubioPackage = {
  "name": "openprinting.github.io",
  "domain": "openprinting.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx openprinting.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface openprintinggithubioPackage {
  name: "openprinting.github.io";
  domain: "openprinting.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx openprinting.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
