import type { PkgxPackage } from '../types'

/**
 * openrestyorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const openrestyorgPackage: PkgxPackage = {
  name: "openresty.org",
  domain: "openresty.org",
  description: "High Performance Web Platform Based on Nginx and LuaJIT",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/openresty.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +openresty.org -- $SHELL -i",
  programs: [
    "nginx-xml2pod",
    "opm",
    "resty",
    "restydoc",
    "restydoc-index"
  ],
  companions: [],
  dependencies: [
    "pcre.org@8",
    "openssl.org^1.1",
    "zlib.net^1.2",
    "perl.org"
  ],
  versions: ["1.25.3.2"]
}

export interface OpenrestyorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "openresty.org";
  domain: "openresty.org";
  description: "Package information for openresty.org";
}
