import type { PkgxPackage } from '../types'

/**
 * opendaporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const opendaporgPackage: PkgxPackage = {
  name: "opendap.org",
  domain: "opendap.org",
  description: "A new version of libdap that contains both DAP2 and DAP4 support",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/opendap.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +opendap.org -- $SHELL -i",
  programs: [
    "dap-config",
    "dap-config-pkgconfig",
    "getdap",
    "getdap4"
  ],
  companions: [],
  dependencies: [
    "gnome.org/libxml2",
    "openssl.org",
    "curl.se",
    "linuxsourceforge.net/libtirpcgithub.com/util-linux/util-linux",
    "sourceforge.net/libtirpc",
    "github.com/util-linux/util-linux"
  ],
  versions: [
    "3.21.1",
    "3.20.11"
  ]
}

export interface OpendaporgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "opendap.org";
  domain: "opendap.org";
  description: "Package information for opendap.org";
}
