import type { PkgxPackage } from '../types'

/**
 * opencore-amrsourceforgeioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const opencoreamrsourceforgeioPackage: PkgxPackage = {
  "name": "opencore-amr.sourceforge.io",
  "domain": "opencore-amr.sourceforge.io",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/opencore-amr.sourceforge.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +opencore-amr.sourceforge.io -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [
    "0.1.6"
  ],
  "fullPath": "opencore-amr.sourceforge.io"
}
