import type { operatorframeworkioPackage } from '../types'

/**
 * operatorframeworkioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const operatorframeworkioPackage: operatorframeworkioPackage = {
  "name": "operatorframework.io",
  "domain": "operatorframework.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx operatorframework.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface operatorframeworkioPackage {
  name: "operatorframework.io";
  domain: "operatorframework.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx operatorframework.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
