import type { PkgxPackage } from '../types'

/**
 * oraclecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const oraclecomPackage: PkgxPackage = {
  name: "oracle.com",
  domain: "oracle.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx oracle.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface OraclecomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "oracle.com";
  domain: "oracle.com";
  description: "Package information for oracle.com";
}