import type { ordinalscomPackage } from '../types'

/**
 * ordinalscomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ordinalscomPackage: ordinalscomPackage = {
  "name": "ord",
  "domain": "ordinals.com",
  "description": "Index, block explorer, and command-line wallet",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/ordinals.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) ord",
  "programs": [
    "ord"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "0.6.1",
    "0.6.0",
    "0.5.1",
    "0.5.0"
  ]
}

export interface ordinalscomPackage {
  name: "ord";
  domain: "ordinals.com";
  description: "Index, block explorer, and command-line wallet";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/ordinals.com/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) ord";
  programs: readonly [
    "ord"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "0.6.1",
    "0.6.0",
    "0.5.1",
    "0.5.0"
  ];
}
