import type { PkgxPackage } from '../types'

/**
 * orhundevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const orhundevPackage: PkgxPackage = {
  "name": "orhun.dev",
  "domain": "orhun.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx orhun.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "orhun.dev"
}

export interface OrhundevPackage {
  name: "orhun.dev";
  domain: "orhun.dev";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx orhun.dev";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "orhun.dev";
}
