import type { PkgxPackage } from '../types'

/**
 * pagureioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pagureioPackage: PkgxPackage = {
  name: "pagure.io",
  domain: "pagure.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx pagure.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface PagureioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "pagure.io";
  domain: "pagure.io";
  description: "Package information for pagure.io";
}