import type { PkgxPackage } from '../types'

/**
 * palletsprojectscomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const palletsprojectscomPackage: PkgxPackage = {
  "name": "palletsprojects.com",
  "domain": "palletsprojects.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx palletsprojects.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "palletsprojects.com"
}

export interface PalletsprojectscomPackage {
  name: "palletsprojects.com";
  domain: "palletsprojects.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx palletsprojects.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "palletsprojects.com";
}
