import type { PkgxPackage } from '../types'

/**
 * pantsbuildorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pantsbuildorgPackage: PkgxPackage = {
  name: "pantsbuild.org",
  domain: "pantsbuild.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx pantsbuild.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface PantsbuildorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "pantsbuild.org";
  domain: "pantsbuild.org";
  description: "Package information for pantsbuild.org";
}
