import type { PkgxPackage } from '../types'

/**
 * paulfitzgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const paulfitzgithubioPackage: PkgxPackage = {
  name: "paulfitz.github.io",
  domain: "paulfitz.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx paulfitz.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface PaulfitzgithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "paulfitzgithub.io";
  domain: "paulfitzgithub.io";
  description: "Package information for paulfitzgithub.io";
}