import type { PkgxPackage } from '../types'

/**
 * pcreorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pcreorgPackage: PkgxPackage = {
  name: "pcre",
  domain: "pcre.org",
  description: "Perl compatible regular expressions library",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/pcre.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +pcre.org -- $SHELL -i",
  programs: [
    "pcre-config",
    "pcregrep",
    "pcretest"
  ],
  companions: [],
  dependencies: [
    "sourceware.org/bzip2@1",
    "zlib.net@1"
  ],
  versions: ["8.45.0"]
}

export interface PcreorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "pcre.org";
  domain: "pcre.org";
  description: "Package information for pcre.org";
}