import type { pcscliteapdufrPackage } from '../types'

/**
 * pcscliteapdufrPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pcscliteapdufrPackage: pcscliteapdufrPackage = {
  "name": "pcsc-lite",
  "domain": "pcsclite.apdu.fr",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/pcsclite.apdu.fr/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) pcscd",
  "programs": [
    "pcscd"
  ],
  "companions": [],
  "dependencies": [
    "libusb.info^1",
    "linuxsystemd.io^254",
    "systemd.io^254"
  ],
  "versions": [
    "2.3.3",
    "2.3.2",
    "2.3.1",
    "2.3.0",
    "2.2.3",
    "2.2.2",
    "2.2.1",
    "2.2.0",
    "2.1.0",
    "2.0.3",
    "2.0.2",
    "2.0.1",
    "2.0.0"
  ]
}

export interface pcscliteapdufrPackage {
  name: "pcsc-lite";
  domain: "pcsclite.apdu.fr";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/pcsclite.apdu.fr/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) pcscd";
  programs: readonly [
    "pcscd"
  ];
  companions: readonly [];
  dependencies: readonly [
    "libusb.info^1",
    "linuxsystemd.io^254",
    "systemd.io^254"
  ];
  versions: readonly [
    "2.3.3",
    "2.3.2",
    "2.3.1",
    "2.3.0",
    "2.2.3",
    "2.2.2",
    "2.2.1",
    "2.2.0",
    "2.1.0",
    "2.0.3",
    "2.0.2",
    "2.0.1",
    "2.0.0"
  ];
}
