import type { PkgxPackage } from '../types'

/**
 * peopleengrtamueduPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const peopleengrtamueduPackage: PkgxPackage = {
  name: "people.engr.tamu.edu",
  domain: "people.engr.tamu.edu",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx people.engr.tamu.edu",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface PeopleengrtamueduPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "peopleengrtamuedu";
  domain: "peopleengrtamuedu";
  description: "Package information for peopleengrtamuedu";
}