/**
 * Generated from pkgx.dev data
 */
export const perlorgPackage = {
  programs: [
    "corelist",
    "cpan",
    "enc2xs",
    "encguess",
    "h2ph",
    "h2xs",
    "instmodsh",
    "json_pp",
    "libnetcfg",
    "perl",
    "perlbug",
    "perldoc",
    "perlivp",
    "perlthanks",
    "piconv",
    "pl2pm",
    "pod2html",
    "pod2man",
    "pod2text",
    "pod2usage",
    "podchecker",
    "prove",
    "ptar",
    "ptardiff",
    "ptargrep",
    "shasum",
    "splain",
    "streamzip",
    "xsubpp",
    "zipdetails",
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    "5.40.2",
    "5.40.1",
    "5.40.0",
    "5.38.4",
    "5.38.3",
    "5.38.2",
    "5.38.1",
    "5.38.0",
    "5.36.3",
    "5.36.2",
    "5.36.1",
    "5.36.0",
    "5.34.3",
    "5.34.2",
  ] as const,
  aliases: [
    "perl",
  ] as const,
  name: "perl.org" as const,
  domain: "perl.org" as const,
  description: "Package information for perl.org" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/perl.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +perl.org -- $SHELL -i" as const,
}

export type PerlorgPackage = typeof perlorgPackage
