import type { PkgxPackage } from '../types'

/**
 * pimalayaorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pimalayaorgPackage: PkgxPackage = {
  "name": "pimalaya.org",
  "domain": "pimalaya.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx pimalaya.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "pimalaya.org"
}

export interface PimalayaorgPackage {
  name: "pimalaya.org";
  domain: "pimalaya.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx pimalaya.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "pimalaya.org";
}
