/**
 * Generated from pkgx.dev data
 */
export const pkgxshPackage = {
  programs: [
    "pkgx",
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    "2.7.0",
    "2.6.0",
    "2.5.0",
    "2.4.0",
    "2.3.2",
    "2.3.1",
    "2.3.0",
    "2.2.1",
    "2.2.0",
    "2.1.4",
    "2.1.3",
    "2.1.2",
    "2.1.1",
    "2.1.0",
    "2.0.0",
    "1.5.0",
    "1.4.1",
    "1.4.0",
    "1.3.1",
    "1.3.0",
    "1.2.2",
    "1.2.1",
    "1.2.0",
    "1.1.6",
    "1.1.5",
    "1.1.4",
    "1.1.3",
    "1.1.2",
    "1.1.1",
    "1.1.0",
    "1.0.4",
    "1.0.3",
    "1.0.2",
    "1.0.1",
    "1.0.0",
  ] as const,
  name: "pkgx.sh" as const,
  domain: "pkgx.sh" as const,
  description: "Package information for pkgx.sh" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/pkgx.sh/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +pkgx.sh -- $SHELL -i" as const,
}

export type PkgxshPackage = typeof pkgxshPackage
