import type { PkgxPackage } from '../types'

/**
 * plasmasturmorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const plasmasturmorgPackage: PkgxPackage = {
  "name": "plasmasturm.org",
  "domain": "plasmasturm.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx plasmasturm.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "plasmasturm.org"
}
