import type { pluralithcomPackage } from '../types'

/**
 * pluralithcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pluralithcomPackage: PkgxPackage = {
  "name": "pluralith",
  "domain": "pluralith.com",
  "description": "A tool for Terraform state visualisation and automated generation of infrastructure documentation",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/pluralith.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) pluralith",
  "programs": [
    "pluralith"
  ],
  "companions": [],
  "dependencies": [
    "curl.se/ca-certs"
  ],
  "versions": [
    "0.2.2"
  ]
}

export interface PluralithcomPackage {
  name: "pluralith";
  domain: "pluralith.com";
  description: "A tool for Terraform state visualisation and automated generation of infrastructure documentation";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/pluralith.com/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) pluralith";
  programs: readonly [
    "pluralith"
  ];
  companions: readonly [];
  dependencies: readonly [
    "curl.se/ca-certs"
  ];
  versions: readonly [
    "0.2.2"
  ];
}
