import type { PkgxPackage } from '../types'

/**
 * pngquantorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pngquantorgPackage: PkgxPackage = {
  "name": "pngquant.org",
  "domain": "pngquant.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx pngquant.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface PngquantorgPackage {
  name: "pngquant.org";
  domain: "pngquant.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx pngquant.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
