export const podmanioPackage = {
  name: "podman" as const,
  domain: "podman.io" as const,
  description: "Podman: A tool for managing OCI containers and pods." as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/podman.io/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +podman.io -- $SHELL -i" as const,
  programs: [
    "podman",
    "podman-remote",
    "podman-mac-helper",
  ] as const,
  companions: [
    "openssh.com",
  ] as const,
  dependencies: [
    "qemu.org",
    "github.com/containers/gvisor-tap-vsock",
    "darwingithub.com/crc-org/vfkit",
    "github.com/crc-org/vfkit",
  ] as const,
  versions: [
    "5.5.0",
    "5.4.2",
    "5.4.1",
    "5.4.0",
    "5.3.2",
    "5.3.1",
    "5.3.0",
    "5.2.5",
    "5.2.4",
    "5.2.3",
    "5.2.2",
    "5.2.1",
    "5.2.0",
    "5.1.2",
    "5.1.1",
    "5.1.0",
    "5.0.3",
    "5.0.2",
    "5.0.1",
    "5.0.0",
    "4.9.5",
    "4.9.4",
    "4.9.3",
    "4.9.2",
    "4.9.1",
    "4.9.0",
    "4.8.3",
    "4.8.2",
    "4.8.1",
    "4.8.0",
    "4.7.2",
    "4.7.1",
    "4.7.0",
    "4.6.2",
    "4.6.1",
    "4.6.0",
    "4.5.1",
    "4.5.0",
  ] as const,
  fullPath: "podman.io" as const,
}

export type PodmanioPackage = typeof podmanioPackage
