import type { PkgxPackage } from '../types'

/**
 * poktnetworkPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const poktnetworkPackage: PkgxPackage = {
  name: "pocket",
  domain: "pokt.network",
  description: "Official implementation of the Pocket Network Protocol",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/pokt.network/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) pocket",
  programs: ["pocket"],
  companions: [],
  dependencies: [],
  versions: [
    "0.12.0",
    "0.11.3",
    "0.11.2",
    "0.11.1",
    "0.10.4",
    "0.10.3",
    "0.10.0",
    "0.9.2"
  ]
}

export interface PoktnetworkPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "poktnetwork";
  domain: "poktnetwork";
  description: "Package information for poktnetwork";
}
