/**
 * Generated from pkgx.dev data
 */
export const popplerfreedesktoporgPackage = {
  programs: [
    "pdfattach",
    "pdfdetach",
    "pdffonts",
    "pdfimages",
    "pdfinfo",
    "pdfseparate",
    "pdftocairo",
    "pdftohtml",
    "pdftoppm",
    "pdftops",
    "pdftotext",
    "pdfunite",
  ] as const,
  companions: [] as const,
  dependencies: [
    "boost.org>=1.58.0",
    "cairographics.org>=1.16.0",
    "curl.se",
    "freedesktop.org/fontconfig>=2.13",
    "freetype.org>=2.10",
    "gnome.org/glib>=2.64",
    "gnome.org/libxml2~2.13",
    "libjpeg-turbo.org",
    "libpng.org",
    "openjpeg.org",
    "poppler.freedesktop.org/poppler-data",
    "simplesystems.org/libtiff",
    "zlib.net",
    "mozilla.org/nss>=3.68",
    "gnupg.org/gpgme>=1.19",
    "gnupg.org/libgpg-error@1",
    "gnupg.org/libassuan@2",
    "littlecms.com^2.9",
    "linuxgnu.org/gcc/libstdcxx@14",
    "gnu.org/gcc/libstdcxx@14",
  ] as const,
  versions: [
    "25.5.0",
    "25.4.0",
    "25.3.0",
    "25.2.0",
    "25.1.0",
    "24.12.0",
    "24.11.0",
    "24.10.0",
    "24.9.0",
    "24.8.0",
    "24.7.0",
    "24.6.1",
    "24.6.0",
    "24.5.0",
    "24.4.0",
    "22.12.0",
  ] as const,
  name: "poppler.freedesktop.org" as const,
  domain: "poppler.freedesktop.org" as const,
  description: "Package information for poppler.freedesktop.org" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/poppler.freedesktop.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +poppler.freedesktop.org -- $SHELL -i" as const,
}

export type PopplerfreedesktoporgPackage = typeof popplerfreedesktoporgPackage
