import type { practicalschemenetPackage } from '../types'

/**
 * practicalschemenetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const practicalschemenetPackage: PkgxPackage = {
  "name": "practical-scheme.net",
  "domain": "practical-scheme.net",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx practical-scheme.net",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface PracticalschemenetPackage {
  name: "practical-scheme.net";
  domain: "practical-scheme.net";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx practical-scheme.net";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
