import type { PkgxPackage } from '../types'

/**
 * presslygithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const presslygithubioPackage: PkgxPackage = {
  name: "pressly.github.io",
  domain: "pressly.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx pressly.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface PresslygithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "presslygithub.io";
  domain: "presslygithub.io";
  description: "Package information for presslygithub.io";
}