import type { presslygithubioPackage } from '../types'

/**
 * presslygithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const presslygithubioPackage: presslygithubioPackage = {
  "name": "pressly.github.io",
  "domain": "pressly.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx pressly.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface presslygithubioPackage {
  name: "pressly.github.io";
  domain: "pressly.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx pressly.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
