import type { PkgxPackage } from '../types'

/**
 * printfngithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const printfngithubioPackage: PkgxPackage = {
  "name": "printfn.github.io",
  "domain": "printfn.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx printfn.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "printfn.github.io"
}
