import type { PkgxPackage } from '../types'

/**
 * projectdiscoveryioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const projectdiscoveryioPackage: PkgxPackage = {
  "name": "projectdiscovery.io",
  "domain": "projectdiscovery.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx projectdiscovery.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface ProjectdiscoveryioPackage {
  name: "projectdiscovery.io";
  domain: "projectdiscovery.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx projectdiscovery.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
