export const prqllangorgPackage = {
  name: 'prql' as const,
  domain: 'prql-lang.org' as const,
  description: 'PRQL is a modern language for transforming data — a simple, powerful, pipelined SQL replacement' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/prql-lang.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +prql-lang.org -- $SHELL -i' as const,
  programs: [
    'prql-compiler',
    'prqlc',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '0.13.4',
    '0.13.3',
    '0.13.2',
    '0.13.1',
    '0.13.0',
    '0.12.2',
    '0.12.1',
    '0.12.0',
    '0.11.4',
    '0.11.3',
    '0.11.2',
    '0.11.1',
    '0.11.0',
    '0.10.1',
    '0.10.0',
    '0.9.5',
    '0.9.3',
    '0.9.2',
    '0.9.1',
    '0.9.0',
    '0.8.1',
    '0.8.0',
    '0.7.1',
    '0.7.0',
    '0.6.1',
    '0.6.0',
    '0.5.2',
    '0.5.1',
    '0.5.0',
    '0.4.2',
    '0.4.1',
    '0.4.0',
    '0.3.1',
  ] as const,
  fullPath: 'prql-lang.org' as const,
}

export type PrqllangorgPackage = typeof prqllangorgPackage
