import type { PkgxPackage } from '../types'

/**
 * pwgensourceforgeioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pwgensourceforgeioPackage: PkgxPackage = {
  name: "pwgen",
  domain: "pwgen.sourceforge.io",
  description: "Password generator",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/pwgen.sourceforge.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) pwgen",
  programs: ["pwgen"],
  companions: [],
  dependencies: [],
  versions: ["2.8.0"]
}

export interface PwgensourceforgeioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "pwgensourceforge.io";
  domain: "pwgensourceforge.io";
  description: "Package information for pwgensourceforge.io";
}
