import type { PkgxPackage } from '../types'

/**
 * pyinvokeorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pyinvokeorgPackage: PkgxPackage = {
  "name": "invoke",
  "domain": "pyinvoke.org",
  "description": "Pythonic task management & command execution.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/pyinvoke.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) invoke",
  "programs": [
    "invoke"
  ],
  "companions": [],
  "dependencies": [
    "pkgx.sh^1"
  ],
  "versions": [
    "2.2.0"
  ],
  "fullPath": "pyinvoke.org",
  "aliases": [
    "invoke"
  ]
}
