import type { PkgxPackage } from '../types'

/**
 * pypagithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pypagithubioPackage: PkgxPackage = {
  name: "pypa.github.io",
  domain: "pypa.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx pypa.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface PypagithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "pypagithub.io";
  domain: "pypagithub.io";
  description: "Package information for pypagithub.io";
}