import type { PkgxPackage } from '../types'

/**
 * pypaioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const pypaioPackage: PkgxPackage = {
  "name": "pypa.io",
  "domain": "pypa.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx pypa.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "pypa.io"
}

export interface PypaioPackage {
  name: "pypa.io";
  domain: "pypa.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx pypa.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "pypa.io";
}
