import type { quarydevPackage } from '../types'

/**
 * quarydevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const quarydevPackage: quarydevPackage = {
  "name": "quary.dev",
  "domain": "quary.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx quary.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface quarydevPackage {
  name: "quary.dev";
  domain: "quary.dev";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx quary.dev";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
