import type { rwosorgPackage } from '../types'

/**
 * rwosorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rwosorgPackage: rwosorgPackage = {
  "name": "r-wos.org",
  "domain": "r-wos.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx r-wos.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "r-wos.org"
}

export interface RwosorgPackage {
  name: "r-wos.org";
  domain: "r-wos.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx r-wos.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "r-wos.org";
}
