import type { PkgxPackage } from '../types'

/**
 * raccoinorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const raccoinorgPackage: PkgxPackage = {
  name: "raccoin",
  domain: "raccoin.org",
  description: "Crypto Portfolio and Tax Reporting Tool",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/raccoin.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) raccoin",
  programs: ["raccoin"],
  companions: [],
  dependencies: [
    "gnu.org/libiconv^1",
    "openssl.org^1.1"
  ],
  versions: [
    "0.2.0",
    "0.1.0"
  ]
}

export interface RaccoinorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "raccoin.org";
  domain: "raccoin.org";
  description: "Package information for raccoin.org";
}