export const radicleorgPackage = {
  name: 'radicle.org' as const,
  domain: 'radicle.org' as const,
  description: 'Radicle CLI' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/radicle.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +radicle.org -- $SHELL -i' as const,
  programs: [
    'rad',
    'git-remote-rad',
    'rad-account',
    'rad-auth',
    'rad-checkout',
    'rad-clone',
    'rad-edit',
    'rad-ens',
    'rad-gov',
    'rad-help',
    'rad-init',
    'rad-inspect',
    'rad-issue',
    'rad-ls',
    'rad-merge',
    'rad-patch',
    'rad-path',
    'rad-pull',
    'rad-push',
    'rad-remote',
    'rad-reward',
    'rad-rm',
    'rad-self',
    'rad-sync',
    'rad-track',
    'rad-untrack',
  ] as const,
  companions: [] as const,
  dependencies: [
    'openssl.org^1.1.1',
  ] as const,
  versions: [
    '0.6.1',
  ] as const,
  fullPath: 'radicle.org' as const,
  aliases: [] as const,
}

export type RadicleorgPackage = typeof radicleorgPackage
