import type { PkgxPackage } from '../types'

/**
 * rapidjsonorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rapidjsonorgPackage: PkgxPackage = {
  "name": "rapidjson.org",
  "domain": "rapidjson.org",
  "description": "A fast JSON parser/generator for C++ with both SAX/DOM style API",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/rapidjson.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +rapidjson.org -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [
    "1.1.0"
  ]
}

export interface RapidjsonorgPackage {
  name: "rapidjson.org";
  domain: "rapidjson.org";
  description: "A fast JSON parser/generator for C++ with both SAX/DOM style API";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/rapidjson.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +rapidjson.org -- $SHELL -i";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "1.1.0"
  ];
}
