import type { rbenvorgPackage } from '../types'

/**
 * rbenvorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rbenvorgPackage: PkgxPackage = {
  "name": "rbenv.org",
  "domain": "rbenv.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx rbenv.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface RbenvorgPackage {
  name: "rbenv.org";
  domain: "rbenv.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx rbenv.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
