import type { rebar3orgPackage } from '../types'

/**
 * rebar3orgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rebar3orgPackage: rebar3orgPackage = {
  "name": "rebar3",
  "domain": "rebar3.org",
  "description": "Erlang build tool that makes it easy to compile and test Erlang applications and releases.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/rebar3.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) rebar3",
  "programs": [
    "rebar3"
  ],
  "companions": [],
  "dependencies": [
    "erlang.org"
  ],
  "versions": [
    "3.24.0",
    "3.23.0"
  ]
}

export interface rebar3orgPackage {
  name: "rebar3";
  domain: "rebar3.org";
  description: "Erlang build tool that makes it easy to compile and test Erlang applications and releases.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/rebar3.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) rebar3";
  programs: readonly [
    "rebar3"
  ];
  companions: readonly [];
  dependencies: readonly [
    "erlang.org"
  ];
  versions: readonly [
    "3.24.0",
    "3.23.0"
  ];
}
