import type { PkgxPackage } from '../types'

/**
 * resticnetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const resticnetPackage: PkgxPackage = {
  name: "restic.net",
  domain: "restic.net",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx restic.net",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface ResticnetPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "restic.net";
  domain: "restic.net";
  description: "Package information for restic.net";
}