import type { PkgxPackage } from '../types'

/**
 * rigauxorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rigauxorgPackage: PkgxPackage = {
  name: "rigaux.org",
  domain: "rigaux.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx rigaux.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface RigauxorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "rigaux.org";
  domain: "rigaux.org";
  description: "Package information for rigaux.org";
}