import type { PkgxPackage } from '../types'

/**
 * riverbankcomputingcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const riverbankcomputingcomPackage: PkgxPackage = {
  "name": "riverbankcomputing.com",
  "domain": "riverbankcomputing.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx riverbankcomputing.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "riverbankcomputing.com"
}

export interface RiverbankcomputingcomPackage {
  name: "riverbankcomputing.com";
  domain: "riverbankcomputing.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx riverbankcomputing.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "riverbankcomputing.com";
}
