import type { rockdabootgithubioPackage } from '../types'

/**
 * rockdabootgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rockdabootgithubioPackage: rockdabootgithubioPackage = {
  "name": "rockdaboot.github.io",
  "domain": "rockdaboot.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx rockdaboot.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface rockdabootgithubioPackage {
  name: "rockdaboot.github.io";
  domain: "rockdaboot.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx rockdaboot.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
