import type { rtomaykogithubioPackage } from '../types'

/**
 * rtomaykogithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rtomaykogithubioPackage: rtomaykogithubioPackage = {
  "name": "rtomayko.github.io",
  "domain": "rtomayko.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx rtomayko.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface rtomaykogithubioPackage {
  name: "rtomayko.github.io";
  domain: "rtomayko.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx rtomayko.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
