import type { rubygemsorgPackage } from '../types'

/**
 * rubygemsorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rubygemsorgPackage: rubygemsorgPackage = {
  "name": "rubygems.org",
  "domain": "rubygems.org",
  "description": "Powerful, clean, object-oriented scripting language",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/rubygems.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +rubygems.org -- $SHELL -i",
  "programs": [
    "bundle",
    "bundler",
    "gem"
  ],
  "companions": [],
  "dependencies": [
    "ruby-lang.org>=2.3"
  ],
  "versions": [
    "3.6.9",
    "3.6.8",
    "3.6.7",
    "3.6.6",
    "3.6.5",
    "3.6.4",
    "3.6.3",
    "3.6.2",
    "3.6.1",
    "3.6.0",
    "3.5.9",
    "3.5.8",
    "3.5.7",
    "3.5.6",
    "3.5.5",
    "3.5.4",
    "3.5.3",
    "3.5.23",
    "3.5.22",
    "3.5.21",
    "3.5.20",
    "3.5.2",
    "3.5.19",
    "3.5.18",
    "3.5.17",
    "3.5.16",
    "3.5.15",
    "3.5.14",
    "3.5.13",
    "3.5.12",
    "3.5.11",
    "3.5.10",
    "3.5.1",
    "3.5.0",
    "3.4.9",
    "3.4.7",
    "3.4.6",
    "3.4.5",
    "3.4.3",
    "3.4.22",
    "3.4.21",
    "3.4.20",
    "3.4.2",
    "3.4.19",
    "3.4.18",
    "3.4.17",
    "3.4.16",
    "3.4.15",
    "3.4.14",
    "3.4.13",
    "3.4.10",
    "3.4.1",
    "3.4.0",
    "3.3.27",
    "3.3.26",
    "3.3.25",
    "3.2.34"
  ]
}

export interface rubygemsorgPackage {
  name: "rubygems.org";
  domain: "rubygems.org";
  description: "Powerful, clean, object-oriented scripting language";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/rubygems.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +rubygems.org -- $SHELL -i";
  programs: readonly [
    "bundle",
    "bundler",
    "gem"
  ];
  companions: readonly [];
  dependencies: readonly [
    "ruby-lang.org>=2.3"
  ];
  versions: readonly [
    "3.6.9",
    "3.6.8",
    "3.6.7",
    "3.6.6",
    "3.6.5",
    "3.6.4",
    "3.6.3",
    "3.6.2",
    "3.6.1",
    "3.6.0",
    "3.5.9",
    "3.5.8",
    "3.5.7",
    "3.5.6",
    "3.5.5",
    "3.5.4",
    "3.5.3",
    "3.5.23",
    "3.5.22",
    "3.5.21",
    "3.5.20",
    "3.5.2",
    "3.5.19",
    "3.5.18",
    "3.5.17",
    "3.5.16",
    "3.5.15",
    "3.5.14",
    "3.5.13",
    "3.5.12",
    "3.5.11",
    "3.5.10",
    "3.5.1",
    "3.5.0",
    "3.4.9",
    "3.4.7",
    "3.4.6",
    "3.4.5",
    "3.4.3",
    "3.4.22",
    "3.4.21",
    "3.4.20",
    "3.4.2",
    "3.4.19",
    "3.4.18",
    "3.4.17",
    "3.4.16",
    "3.4.15",
    "3.4.14",
    "3.4.13",
    "3.4.10",
    "3.4.1",
    "3.4.0",
    "3.3.27",
    "3.3.26",
    "3.3.25",
    "3.2.34"
  ];
}
