export const rubylangorgPackage = {
  name: 'ruby-lang.org' as const,
  domain: 'ruby-lang.org' as const,
  description: 'Powerful, clean, object-oriented scripting language' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/ruby-lang.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) +ruby-lang.org -- $SHELL -i' as const,
  programs: [
    'erb',
    'irb',
    'rake',
    'rdoc',
    'ri',
    'ruby',
  ] as const,
  companions: [
    'rubygems.org',
  ] as const,
  dependencies: [
    'openssl.org^1.1',
    'pyyaml.org^0.2',
    'zlib.net^1',
  ] as const,
  versions: [
    '3.4.4',
    '3.4.3',
    '3.4.2',
    '3.4.1',
    '3.3.8',
    '3.3.7',
    '3.3.6',
    '3.3.5',
    '3.3.4',
    '3.3.3',
    '3.3.2',
    '3.3.1',
    '3.3.0',
    '3.2.8',
    '3.2.7',
    '3.2.6',
    '3.2.5',
    '3.2.4',
    '3.2.3',
    '3.2.2',
    '3.2.1',
    '3.2.0',
    '3.1.7',
    '3.1.6',
    '3.1.5',
    '3.1.4',
    '3.1.3',
    '3.1.2',
    '3.1.1',
    '3.1.0',
    '3.0.7',
    '3.0.6',
    '3.0.5',
    '3.0.4',
    '3.0.3',
    '3.0.2',
    '3.0.1',
    '3.0.0',
    '2.7.8',
    '2.7.6',
    '2.6.10',
    '2.5.9',
  ] as const,
  fullPath: 'ruby-lang.org' as const,
  aliases: [
    'ruby',
  ] as const,
}

export type RubylangorgPackage = typeof rubylangorgPackage
