/**
 * Generated from pkgx.dev data
 */
export const rustlangorgPackage = {
  programs: [
    "cargo-clippy",
    "cargo-fmt",
    "clippy-driver",
    "rust-analyzer",
    "rust-gdb",
    "rust-gdbgui",
    "rust-lldb",
    "rustc",
    "rustdoc",
    "rustfmt",
  ] as const,
  companions: [
    "rust-lang.org/cargo",
    "linux",
  ] as const,
  dependencies: [
    "zlib.net@1",
  ] as const,
  versions: [
    "1.87.0",
    "1.86.0",
    "1.85.1",
    "1.85.0",
    "1.84.1",
    "1.84.0",
    "1.83.0",
    "1.82.0",
    "1.81.0",
    "1.80.1",
    "1.80.0",
    "1.79.0",
    "1.78.0",
    "1.77.2",
    "1.77.1",
    "1.77.0",
    "1.76.0",
    "1.75.0",
    "1.74.1",
    "1.74.0",
    "1.73.0",
    "1.72.1",
    "1.72.0",
    "1.71.1",
    "1.71.0",
    "1.70.0",
    "1.69.0",
    "1.68.2",
    "1.68.1",
    "1.68.0",
    "1.67.1",
    "1.67.0",
    "1.65.0",
    "1.64.0",
  ] as const,
  aliases: [
    "rust",
  ] as const,
  name: "rust/lang.org" as const,
  domain: "rust/lang.org" as const,
  description: "Package information for rust/lang.org" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/rust/lang.org/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +rust/lang.org -- $SHELL -i" as const,
}

export type RustlangorgPackage = typeof rustlangorgPackage
