import type { PkgxPackage } from '../types'

/**
 * rustscriptorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const rustscriptorgPackage: PkgxPackage = {
  name: "rust-script",
  domain: "rust-script.org",
  description: "Run Rust files and expressions as scripts without any setup or compilation step.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/rust-script.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) rust-script",
  programs: ["rust-script"],
  companions: [
    "rust-lang.org",
    "rust-lang.org/cargo"
  ],
  dependencies: [],
  versions: [
    "0.35.0",
    "0.34.0"
  ]
}

export interface RustscriptorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "rust/scriptorg";
  domain: "rust/scriptorg";
  description: "Package information for rust/scriptorg";
}
