import type { PkgxPackage } from '../types'

/**
 * ryeastralshPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const ryeastralshPackage: PkgxPackage = {
  name: "rye",
  domain: "rye.astral.sh",
  description: "Experimental Package Management Solution for Python",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/rye.astral.sh/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) rye",
  programs: ["rye"],
  companions: [],
  dependencies: ["curl.se/ca-certs"],
  versions: [
    "0.44.0",
    "0.43.0",
    "0.42.0",
    "0.41.0",
    "0.40.0",
    "0.39.0",
    "0.38.0",
    "0.37.0",
    "0.36.0"
  ]
}

export interface RyeastralshPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "ryeastral.sh";
  domain: "ryeastral.sh";
  description: "Package information for ryeastral.sh";
}