import type { PkgxPackage } from '../types'

/**
 * saerasoftcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const saerasoftcomPackage: PkgxPackage = {
  name: "saerasoft.com",
  domain: "saerasoft.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx saerasoft.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface SaerasoftcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "saerasoft.com";
  domain: "saerasoft.com";
  description: "Package information for saerasoft.com";
}
