import type { PkgxPackage } from '../types'

/**
 * saerasoftcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const saerasoftcomPackage: PkgxPackage = {
  "name": "saerasoft.com",
  "domain": "saerasoft.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx saerasoft.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "saerasoft.com"
}
