import type { PkgxPackage } from '../types'

/**
 * sagiegurarigithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sagiegurarigithubioPackage: PkgxPackage = {
  "name": "sagiegurari.github.io",
  "domain": "sagiegurari.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx sagiegurari.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface SagiegurarigithubioPackage {
  name: "sagiegurari.github.io";
  domain: "sagiegurari.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx sagiegurari.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
