import type { sasslangcomPackage } from '../types'

/**
 * sasslangcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sasslangcomPackage: sasslangcomPackage = {
  "name": "sass-lang.com",
  "domain": "sass-lang.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx sass-lang.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "sass-lang.com"
}

export interface SasslangcomPackage {
  name: "sass-lang.com";
  domain: "sass-lang.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx sass-lang.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "sass-lang.com";
}
