import type { savannahnongnuorgPackage } from '../types'

/**
 * savannahnongnuorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const savannahnongnuorgPackage: savannahnongnuorgPackage = {
  "name": "savannah.nongnu.org",
  "domain": "savannah.nongnu.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx savannah.nongnu.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface savannahnongnuorgPackage {
  name: "savannah.nongnu.org";
  domain: "savannah.nongnu.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx savannah.nongnu.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
