import type { PkgxPackage } from '../types'

/**
 * savannahnongnuorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const savannahnongnuorgPackage: PkgxPackage = {
  name: "savannah.nongnu.org",
  domain: "savannah.nongnu.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx savannah.nongnu.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface SavannahnongnuorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "savannahnongnu.org";
  domain: "savannahnongnu.org";
  description: "Package information for savannahnongnu.org";
}
