import type { PkgxPackage } from '../types'

/**
 * scalewaycomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const scalewaycomPackage: PkgxPackage = {
  "name": "scw",
  "domain": "scaleway.com",
  "description": "Command Line Interface for Scaleway",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/scaleway.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) scw",
  "programs": [
    "scw"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "2.39.0",
    "2.38.0",
    "2.37.0",
    "2.36.0",
    "2.35.0",
    "2.34.0",
    "2.33.0",
    "2.32.1"
  ],
  "fullPath": "scaleway.com",
  "aliases": [
    "scw"
  ]
}
