import type { PkgxPackage } from '../types'

/**
 * scryerplPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const scryerplPackage: PkgxPackage = {
  "name": "Scryer Prolog",
  "domain": "scryer.pl",
  "description": "Modern ISO Prolog implementation written mostly in Rust",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/scryer.pl/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) scryer-prolog",
  "programs": [
    "scryer-prolog"
  ],
  "companions": [],
  "dependencies": [
    "openssl.org^1.1"
  ],
  "versions": [
    "0.9.4"
  ],
  "fullPath": "scryer.pl",
  "aliases": [
    "scryer prolog"
  ]
}
