import type { PkgxPackage } from '../types'

/**
 * sdkmanioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sdkmanioPackage: PkgxPackage = {
  name: "sdkman-init.sh",
  domain: "sdkman.io",
  description: "The SDKMAN! Command Line Interface",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/sdkman.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) sdkman-init.sh",
  programs: ["sdkman-init.sh"],
  companions: [],
  dependencies: [],
  versions: [
    "5.19.0",
    "5.18.2"
  ]
}

export interface SdkmanioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "sdkman.io";
  domain: "sdkman.io";
  description: "Package information for sdkman.io";
}