import type { PkgxPackage } from '../types'

/**
 * sfcgalorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sfcgalorgPackage: PkgxPackage = {
  "name": "sfcgal-config",
  "domain": "sfcgal.org",
  "description": "C++ wrapper library around CGAL",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/sfcgal.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) sfcgal-config",
  "programs": [
    "sfcgal-config"
  ],
  "companions": [],
  "dependencies": [
    "boost.org",
    "cgal.org",
    "gnu.org/gmp",
    "gnu.org/mpfr"
  ],
  "versions": [
    "2.1.0",
    "2.0.0",
    "1.5.2",
    "1.5.1",
    "1.5.0",
    "1.4.1"
  ],
  "fullPath": "sfcgal.org",
  "aliases": [
    "sfcgal-config"
  ]
}
