import type { PkgxPackage } from '../types'

/**
 * sfnetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sfnetPackage: PkgxPackage = {
  "name": "sf.net",
  "domain": "sf.net",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx sf.net",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "sf.net"
}
