import type { shellchecknetPackage } from '../types'

/**
 * shellchecknetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const shellchecknetPackage: PkgxPackage = {
  "name": "shellcheck",
  "domain": "shellcheck.net",
  "description": "ShellCheck, a static analysis tool for shell scripts",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/shellcheck.net/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) shellcheck",
  "programs": [
    "shellcheck"
  ],
  "companions": [],
  "dependencies": [
    "sourceware.org/libffi@3"
  ],
  "versions": [
    "0.9.0",
    "0.8.0",
    "0.10.0"
  ]
}

export interface ShellchecknetPackage {
  name: "shellcheck";
  domain: "shellcheck.net";
  description: "ShellCheck, a static analysis tool for shell scripts";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/shellcheck.net/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) shellcheck";
  programs: readonly [
    "shellcheck"
  ];
  companions: readonly [];
  dependencies: readonly [
    "sourceware.org/libffi@3"
  ];
  versions: readonly [
    "0.9.0",
    "0.8.0",
    "0.10.0"
  ];
}
