import type { PkgxPackage } from '../types'

/**
 * sigstoredevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sigstoredevPackage: PkgxPackage = {
  "name": "sigstore.dev",
  "domain": "sigstore.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx sigstore.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "sigstore.dev"
}
