import type { smartmontoolsorgPackage } from '../types'

/**
 * smartmontoolsorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const smartmontoolsorgPackage: smartmontoolsorgPackage = {
  "name": "smartmontools.org",
  "domain": "smartmontools.org",
  "description": "SMART hard drive monitoring",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/smartmontools.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +smartmontools.org -- $SHELL -i",
  "programs": [
    "smartctl",
    "smartd"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "7.5.0",
    "7.4.0",
    "7.3.0"
  ]
}

export interface smartmontoolsorgPackage {
  name: "smartmontools.org";
  domain: "smartmontools.org";
  description: "SMART hard drive monitoring";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/smartmontools.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +smartmontools.org -- $SHELL -i";
  programs: readonly [
    "smartctl",
    "smartd"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "7.5.0",
    "7.4.0",
    "7.3.0"
  ];
}
