import type { snapletdevPackage } from '../types'

/**
 * snapletdevPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const snapletdevPackage: snapletdevPackage = {
  "name": "snaplet.dev",
  "domain": "snaplet.dev",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx snaplet.dev",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface snapletdevPackage {
  name: "snaplet.dev";
  domain: "snaplet.dev";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx snaplet.dev";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
