import type { PkgxPackage } from '../types'

/**
 * soldeerxyzPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const soldeerxyzPackage: PkgxPackage = {
  name: "soldeer",
  domain: "soldeer.xyz",
  description: "Solidity Package Manager written in rust and integrated into Foundry (forge soldeer ...)",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/soldeer.xyz/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) soldeer",
  programs: ["soldeer"],
  companions: [],
  dependencies: [],
  versions: [
    "0.5.4",
    "0.5.3",
    "0.5.2"
  ]
}

export interface SoldeerxyzPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "soldeerxyz";
  domain: "soldeerxyz";
  description: "Package information for soldeerxyz";
}
