import type { PkgxPackage } from '../types'

/**
 * sonarqubeorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sonarqubeorgPackage: PkgxPackage = {
  name: "sonarqube.org",
  domain: "sonarqube.org",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx sonarqube.org",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface SonarqubeorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "sonarqube.org";
  domain: "sonarqube.org";
  description: "Package information for sonarqube.org";
}