import type { PkgxPackage } from '../types'

/**
 * sourceforgenetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sourceforgenetPackage: PkgxPackage = {
  name: "sourceforge.net",
  domain: "sourceforge.net",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx sourceforge.net",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface SourceforgenetPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "sourceforge.net";
  domain: "sourceforge.net";
  description: "Package information for sourceforge.net";
}