import type { sourceforgenetPackage } from '../types'

/**
 * sourceforgenetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sourceforgenetPackage: sourceforgenetPackage = {
  "name": "sourceforge.net",
  "domain": "sourceforge.net",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx sourceforge.net",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface sourceforgenetPackage {
  name: "sourceforge.net";
  domain: "sourceforge.net";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx sourceforge.net";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
