import type { PkgxPackage } from '../types'

/**
 * soxrsourceforgenetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const soxrsourceforgenetPackage: PkgxPackage = {
  "name": "soxr.sourceforge.net",
  "domain": "soxr.sourceforge.net",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/soxr.sourceforge.net/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +soxr.sourceforge.net -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [
    "0.1.3"
  ],
  "fullPath": "soxr.sourceforge.net"
}
