import type { spawnlinkPackage } from '../types'

/**
 * spawnlinkPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const spawnlinkPackage: spawnlinkPackage = {
  "name": "spawn.link",
  "domain": "spawn.link",
  "description": "a featureful union filesystem",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/spawn.link/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +spawn.link -- $SHELL -i",
  "programs": [
    "mergerfs",
    "mergerfs-fusermount",
    "mount.mergerfs"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "2.40.2",
    "2.40.1",
    "2.40.0",
    "2.39.0",
    "2.38.0",
    "2.37.1",
    "2.37.0",
    "2.36.0",
    "2.35.1"
  ]
}

export interface spawnlinkPackage {
  name: "spawn.link";
  domain: "spawn.link";
  description: "a featureful union filesystem";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/spawn.link/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +spawn.link -- $SHELL -i";
  programs: readonly [
    "mergerfs",
    "mergerfs-fusermount",
    "mount.mergerfs"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "2.40.2",
    "2.40.1",
    "2.40.0",
    "2.39.0",
    "2.38.0",
    "2.37.1",
    "2.37.0",
    "2.36.0",
    "2.35.1"
  ];
}
