export const sqlfluffcomPackage = {
  name: 'sqlfluff' as const,
  domain: 'sqlfluff.com' as const,
  description: 'A modular SQL linter and auto-formatter with support for multiple dialects and templated code.' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/sqlfluff.com/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) sqlfluff' as const,
  programs: [
    'sqlfluff',
  ] as const,
  companions: [] as const,
  dependencies: [
    'python.org>=3.7<3.12',
  ] as const,
  versions: [
    '3.4.0',
    '3.3.1',
    '3.3.0',
    '3.2.5',
    '3.2.4',
    '3.2.3',
    '3.2.2',
    '3.2.1',
    '3.2.0',
    '3.1.1',
    '3.1.0',
    '3.0.7',
    '3.0.6',
    '3.0.5',
    '3.0.4',
    '3.0.3',
    '3.0.2',
    '3.0.1',
    '3.0.0',
    '2.3.5',
    '2.3.4',
    '2.3.3',
    '2.3.2',
  ] as const,
  fullPath: 'sqlfluff.com' as const,
}

export type SqlfluffcomPackage = typeof sqlfluffcomPackage
