import type { sqliteorgPackage } from '../types'

/**
 * sqliteorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const sqliteorgPackage: sqliteorgPackage = {
  "name": "sqlite3",
  "domain": "sqlite.org",
  "description": "Official Git mirror of the SQLite source tree",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/sqlite.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) sqlite3",
  "programs": [
    "sqlite3"
  ],
  "companions": [],
  "dependencies": [
    "zlib.net@1",
    "gnu.org/readline@8"
  ],
  "versions": [
    "3.49.2",
    "3.49.1",
    "3.49.0",
    "3.48.0",
    "3.47.2",
    "3.47.1",
    "3.47.0",
    "3.46.1",
    "3.46.0",
    "3.45.3",
    "3.45.2",
    "3.45.1",
    "3.45.0",
    "3.44.4",
    "3.44.3",
    "3.44.2",
    "3.44.1",
    "3.44.0",
    "3.43.2",
    "3.43.1",
    "3.43.0",
    "3.42.0",
    "3.40.0",
    "3.39.4"
  ]
}

export interface sqliteorgPackage {
  name: "sqlite3";
  domain: "sqlite.org";
  description: "Official Git mirror of the SQLite source tree";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/sqlite.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) sqlite3";
  programs: readonly [
    "sqlite3"
  ];
  companions: readonly [];
  dependencies: readonly [
    "zlib.net@1",
    "gnu.org/readline@8"
  ];
  versions: readonly [
    "3.49.2",
    "3.49.1",
    "3.49.0",
    "3.48.0",
    "3.47.2",
    "3.47.1",
    "3.47.0",
    "3.46.1",
    "3.46.0",
    "3.45.3",
    "3.45.2",
    "3.45.1",
    "3.45.0",
    "3.44.4",
    "3.44.3",
    "3.44.2",
    "3.44.1",
    "3.44.0",
    "3.43.2",
    "3.43.1",
    "3.43.0",
    "3.42.0",
    "3.40.0",
    "3.39.4"
  ];
}
