export const squawkhqcomPackage = {
  name: 'squawk' as const,
  domain: 'squawkhq.com' as const,
  description: '🐘 linter for PostgreSQL, focused on migrations' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/squawkhq.com/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) squawk' as const,
  programs: [
    'squawk',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '2.8.0',
    '2.7.0',
    '2.6.0',
    '2.5.0',
    '2.4.0',
    '2.3.0',
    '2.2.0',
    '2.1.0',
    '2.0.0',
    '1.6.1',
    '1.6.0',
    '1.5.5',
    '1.5.4',
    '1.5.3',
    '1.5.2',
    '1.5.1',
    '1.5.0',
    '1.4.0',
    '1.2.0',
    '1.1.2',
    '1.1.1',
    '1.1.0',
    '1.0.0',
    '0.29.0',
    '0.28.0',
    '0.27.0',
    '0.26.0',
    '0.25.0',
    '0.24.2',
    '0.24.1',
    '0.24.0',
  ] as const,
  fullPath: 'squawkhq.com' as const,
  aliases: [] as const,
}

export type SquawkhqcomPackage = typeof squawkhqcomPackage
