import type { PkgxPackage } from '../types'

/**
 * srtallianceorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const srtallianceorgPackage: PkgxPackage = {
  name: "srt",
  domain: "srtalliance.org",
  description: "Secure, Reliable, Transport",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/srtalliance.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +srtalliance.org -- $SHELL -i",
  programs: [
    "srt-ffplay",
    "srt-file-transmit",
    "srt-live-transmit",
    "srt-tunnel"
  ],
  companions: [],
  dependencies: ["openssl.org"],
  versions: [
    "1.5.4",
    "1.5.3",
    "1.5.2"
  ]
}

export interface SrtallianceorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "srtalliance.org";
  domain: "srtalliance.org";
  description: "Package information for srtalliance.org";
}
