export const starshiprsPackage = {
  name: "starship" as const,
  domain: "starship.rs" as const,
  description: "☄🌌️  The minimal, blazing-fast, and infinitely customizable prompt for any shell!" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/starship.rs/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) starship" as const,
  programs: [
    "starship",
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    "1.23.0",
    "1.22.1",
    "1.22.0",
    "1.21.1",
    "1.21.0",
    "1.20.1",
    "1.20.0",
    "1.19.0",
    "1.18.2",
    "1.18.1",
    "1.18.0",
    "1.17.1",
    "1.17.0",
    "1.16.0",
    "1.15.0",
    "1.14.2",
    "1.14.1",
    "1.14.0",
    "1.13.1",
    "1.13.0",
    "1.12.0",
  ] as const,
  fullPath: "starship.rs" as const,
}

export type StarshiprsPackage = typeof starshiprsPackage
