import type { stedolangithubioPackage } from '../types'

/**
 * stedolangithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const stedolangithubioPackage: stedolangithubioPackage = {
  "name": "stedolan.github.io",
  "domain": "stedolan.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx stedolan.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface stedolangithubioPackage {
  name: "stedolan.github.io";
  domain: "stedolan.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx stedolan.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
