import type { supabasecomPackage } from '../types'

/**
 * supabasecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const supabasecomPackage: supabasecomPackage = {
  "name": "supabase.com",
  "domain": "supabase.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx supabase.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface supabasecomPackage {
  name: "supabase.com";
  domain: "supabase.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx supabase.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
