import type { PkgxPackage } from '../types'

/**
 * svenstarogithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const svenstarogithubioPackage: PkgxPackage = {
  "name": "svenstaro.github.io",
  "domain": "svenstaro.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx svenstaro.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "svenstaro.github.io"
}

export interface SvenstarogithubioPackage {
  name: "svenstaro.github.io";
  domain: "svenstaro.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx svenstaro.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "svenstaro.github.io";
}
