import type { PkgxPackage } from '../types'

/**
 * swaggerioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const swaggerioPackage: PkgxPackage = {
  "name": "swagger.io",
  "domain": "swagger.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx swagger.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "swagger.io"
}

export interface SwaggerioPackage {
  name: "swagger.io";
  domain: "swagger.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx swagger.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "swagger.io";
}
