export const syncthingnetPackage = {
  name: "syncthing" as const,
  domain: "syncthing.net" as const,
  description: "Open source continuous file synchronization application" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/syncthing.net/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) syncthing" as const,
  programs: [
    "syncthing",
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    "1.29.6",
    "1.29.5",
    "1.29.4",
    "1.29.3",
    "1.29.2",
    "1.29.1",
    "1.29.0",
    "1.28.1",
    "1.28.0",
    "1.27.12",
    "1.27.11",
    "1.27.10",
    "1.27.9",
    "1.27.8",
    "1.27.7",
    "1.27.6",
    "1.27.5",
    "1.27.4",
  ] as const,
  fullPath: "syncthing.net" as const,
}

export type SyncthingnetPackage = typeof syncthingnetPackage
