import type { taku910githubioPackage } from '../types'

/**
 * taku910githubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const taku910githubioPackage: taku910githubioPackage = {
  "name": "taku910.github.io",
  "domain": "taku910.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx taku910.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface taku910githubioPackage {
  name: "taku910.github.io";
  domain: "taku910.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx taku910.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
