export const talosdevPackage = {
  name: 'talosctl' as const,
  domain: 'talos.dev' as const,
  description: 'CLI for out-of-band management of Kubernetes nodes created by Talos' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/talos.dev/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) talosctl' as const,
  programs: [
    'talosctl',
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    '1.10.3',
    '1.10.2',
    '1.10.1',
    '1.10.0',
    '1.9.6',
    '1.9.5',
    '1.9.4',
    '1.9.3',
    '1.9.2',
    '1.9.1',
    '1.9.0',
    '1.8.4',
    '1.8.3',
    '1.8.2',
    '1.8.1',
    '1.8.0',
    '1.7.7',
    '1.7.6',
    '1.7.5',
    '1.7.4',
    '1.7.3',
    '1.7.2',
    '1.7.1',
    '1.7.0',
    '1.6.8',
    '1.6.7',
    '1.6.6',
  ] as const,
  fullPath: 'talos.dev' as const,
  aliases: [
    'talosctl',
  ] as const,
}

export type TalosdevPackage = typeof talosdevPackage
