import type { PkgxPackage } from '../types'

/**
 * tcltkPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const tcltkPackage: PkgxPackage = {
  "name": "tcl.tk",
  "domain": "tcl.tk",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx tcl.tk",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface TcltkPackage {
  name: "tcl.tk";
  domain: "tcl.tk";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx tcl.tk";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
