import type { PkgxPackage } from '../types'

/**
 * tcpdumporgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const tcpdumporgPackage: PkgxPackage = {
  name: "pcap-config",
  domain: "tcpdump.org",
  description: "the LIBpcap interface to various kernel packet capture mechanism",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/tcpdump.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) pcap-config",
  programs: ["pcap-config"],
  companions: [],
  dependencies: [],
  versions: [
    "1.10.5",
    "1.10.4"
  ]
}

export interface TcpdumporgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "tcpdump.org";
  domain: "tcpdump.org";
  description: "Package information for tcpdump.org";
}