import type { PkgxPackage } from '../types'

/**
 * templguidePackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const templguidePackage: PkgxPackage = {
  name: "templ",
  domain: "templ.guide",
  description: "A language for writing HTML user interfaces in Go.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/templ.guide/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) templ",
  programs: ["templ"],
  companions: [],
  dependencies: [],
  versions: [
    "0.3.865",
    "0.3.857",
    "0.3.856",
    "0.3.850",
    "0.3.833",
    "0.3.819",
    "0.2.793",
    "0.2.778",
    "0.2.771",
    "0.2.747",
    "0.2.742",
    "0.2.731",
    "0.2.707",
    "0.2.697",
    "0.2.680",
    "0.2.663",
    "0.2.648",
    "0.2.646",
    "0.2.639",
    "0.2.598",
    "0.2.543",
    "0.2.513",
    "0.2.501",
    "0.2.476"
  ]
}

export interface TemplguidePackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "templguide";
  domain: "templguide";
  description: "Package information for templguide";
}