import type { theoraorgPackage } from '../types'

/**
 * theoraorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const theoraorgPackage: theoraorgPackage = {
  "name": "theora.org",
  "domain": "theora.org",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/theora.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +theora.org -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [
    "xiph.org/ogg",
    "xiph.org/vorbis"
  ],
  "versions": [
    "1.2.0",
    "1.1.1"
  ]
}

export interface theoraorgPackage {
  name: "theora.org";
  domain: "theora.org";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/theora.org/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +theora.org -- $SHELL -i";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [
    "xiph.org/ogg",
    "xiph.org/vorbis"
  ];
  versions: readonly [
    "1.2.0",
    "1.1.1"
  ];
}
