import type { PkgxPackage } from '../types'

/**
 * theoraorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const theoraorgPackage: PkgxPackage = {
  "name": "theora.org",
  "domain": "theora.org",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/theora.org/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +theora.org -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [
    "xiph.org/ogg",
    "xiph.org/vorbis"
  ],
  "versions": [
    "1.2.0",
    "1.1.1"
  ],
  "fullPath": "theora.org"
}
