import type { PkgxPackage } from '../types'

/**
 * thoughtworksgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const thoughtworksgithubioPackage: PkgxPackage = {
  "name": "thoughtworks.github.io",
  "domain": "thoughtworks.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx thoughtworks.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "thoughtworks.github.io"
}
