import type { thoughtworksgithubioPackage } from '../types'

/**
 * thoughtworksgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const thoughtworksgithubioPackage: thoughtworksgithubioPackage = {
  "name": "thoughtworks.github.io",
  "domain": "thoughtworks.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx thoughtworks.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface thoughtworksgithubioPackage {
  name: "thoughtworks.github.io";
  domain: "thoughtworks.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx thoughtworks.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
