import type { tinybirdcoPackage } from '../types'

/**
 * tinybirdcoPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const tinybirdcoPackage: tinybirdcoPackage = {
  "name": "tinybird.co",
  "domain": "tinybird.co",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/tinybird.co/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +tinybird.co -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [
    "pkgx.sh^1"
  ],
  "versions": [
    "5.20.0"
  ]
}

export interface tinybirdcoPackage {
  name: "tinybird.co";
  domain: "tinybird.co";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/tinybird.co/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +tinybird.co -- $SHELL -i";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [
    "pkgx.sh^1"
  ];
  versions: readonly [
    "5.20.0"
  ];
}
