import type { PkgxPackage } from '../types'

/**
 * tinybirdcoPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const tinybirdcoPackage: PkgxPackage = {
  name: "tb",
  domain: "tinybird.co",
  description: "",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/tinybird.co/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) tb",
  programs: ["tb"],
  companions: [],
  dependencies: ["pkgx.sh^1"],
  versions: ["5.20.0"]
}

export interface TinybirdcoPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "tinybirdco";
  domain: "tinybirdco";
  description: "Package information for tinybirdco";
}