import type { PkgxPackage } from '../types'

/**
 * tmateioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const tmateioPackage: PkgxPackage = {
  "name": "tmate",
  "domain": "tmate.io",
  "description": "Instant Terminal Sharing",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/tmate.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) tmate",
  "programs": [
    "tmate"
  ],
  "companions": [],
  "dependencies": [
    "libevent.org^2.0",
    "invisible-island.net/ncurses@6",
    "msgpack.org@6",
    "libssh.org@0"
  ],
  "versions": [
    "2.4.0"
  ],
  "fullPath": "tmate.io"
}
