import type { toxwikiPackage } from '../types'

/**
 * toxwikiPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const toxwikiPackage: toxwikiPackage = {
  "name": "tox",
  "domain": "tox.wiki",
  "description": "Command line driven CI frontend and development task automation tool.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/tox.wiki/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) tox",
  "programs": [
    "tox"
  ],
  "companions": [],
  "dependencies": [
    "pkgx.sh^1"
  ],
  "versions": [
    "4.26.0",
    "4.25.0",
    "4.24.2",
    "4.24.1",
    "4.24.0",
    "4.23.2",
    "4.23.1",
    "4.23.0",
    "4.22.0",
    "4.21.2",
    "4.21.1",
    "4.21.0",
    "4.20.0",
    "4.19.0",
    "4.18.1"
  ]
}

export interface toxwikiPackage {
  name: "tox";
  domain: "tox.wiki";
  description: "Command line driven CI frontend and development task automation tool.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/tox.wiki/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) tox";
  programs: readonly [
    "tox"
  ];
  companions: readonly [];
  dependencies: readonly [
    "pkgx.sh^1"
  ];
  versions: readonly [
    "4.26.0",
    "4.25.0",
    "4.24.2",
    "4.24.1",
    "4.24.0",
    "4.23.2",
    "4.23.1",
    "4.23.0",
    "4.22.0",
    "4.21.2",
    "4.21.1",
    "4.21.0",
    "4.20.0",
    "4.19.0",
    "4.18.1"
  ];
}
