import type { trufflesecuritycomPackage } from '../types'

/**
 * trufflesecuritycomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const trufflesecuritycomPackage: trufflesecuritycomPackage = {
  "name": "trufflesecurity.com",
  "domain": "trufflesecurity.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx trufflesecurity.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface trufflesecuritycomPackage {
  name: "trufflesecurity.com";
  domain: "trufflesecurity.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx trufflesecurity.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
