import type { PkgxPackage } from '../types'

/**
 * tsl0922githubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const tsl0922githubioPackage: PkgxPackage = {
  "name": "tsl0922.github.io",
  "domain": "tsl0922.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx tsl0922.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "tsl0922.github.io"
}
