import type { tuistioPackage } from '../types'

/**
 * tuistioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const tuistioPackage: tuistioPackage = {
  "name": "tuist.io",
  "domain": "tuist.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx tuist.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface tuistioPackage {
  name: "tuist.io";
  domain: "tuist.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx tuist.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
