import type { PkgxPackage } from '../types'

/**
 * tukaaniorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const tukaaniorgPackage: PkgxPackage = {
  "name": "tukaani.org",
  "domain": "tukaani.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx tukaani.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "tukaani.org"
}
