import type { PkgxPackage } from '../types'

/**
 * unboundnetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const unboundnetPackage: PkgxPackage = {
  "name": "unbound",
  "domain": "unbound.net",
  "description": "Unbound is a validating, recursive, and caching DNS resolver.",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/unbound.net/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +unbound.net -- $SHELL -i",
  "programs": [
    "unbound",
    "unbound-anchor",
    "unbound-checkconf",
    "unbound-control",
    "unbound-control-setup",
    "unbound-host"
  ],
  "companions": [],
  "dependencies": [
    "openssl.org^1"
  ],
  "versions": [
    "1.23.0",
    "1.22.0",
    "1.21.1",
    "1.21.0",
    "1.20.0",
    "1.19.3",
    "1.19.2",
    "1.19.1",
    "1.19.0",
    "1.18.0",
    "1.17.1"
  ]
}

export interface UnboundnetPackage {
  name: "unbound";
  domain: "unbound.net";
  description: "Unbound is a validating, recursive, and caching DNS resolver.";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/unbound.net/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +unbound.net -- $SHELL -i";
  programs: readonly [
    "unbound",
    "unbound-anchor",
    "unbound-checkconf",
    "unbound-control",
    "unbound-control-setup",
    "unbound-host"
  ];
  companions: readonly [];
  dependencies: readonly [
    "openssl.org^1"
  ];
  versions: readonly [
    "1.23.0",
    "1.22.0",
    "1.21.1",
    "1.21.0",
    "1.20.0",
    "1.19.3",
    "1.19.2",
    "1.19.1",
    "1.19.0",
    "1.18.0",
    "1.17.1"
  ];
}
