import type { PkgxPackage } from '../types'

/**
 * unicodeorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const unicodeorgPackage: PkgxPackage = {
  name: "unicode.org",
  domain: "unicode.org",
  description: "The home of the ICU project source code.",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/unicode.org/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) +unicode.org -- $SHELL -i",
  programs: [
    "derb",
    "genbrk",
    "gencfu",
    "gencnval",
    "gendict",
    "genrb",
    "icu-config",
    "icuexportdata",
    "icuinfo",
    "makeconv",
    "pkgdata",
    "uconv"
  ],
  companions: [],
  dependencies: [],
  versions: [
    "77.1.0",
    "76.1.0",
    "75.1.0",
    "74.2.0",
    "74.1.0",
    "73.2.0",
    "71.1.0"
  ]
}

export interface UnicodeorgPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "unicode.org";
  domain: "unicode.org";
  description: "Package information for unicode.org";
}