import type { PkgxPackage } from '../types'

/**
 * upxgithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const upxgithubioPackage: PkgxPackage = {
  "name": "upx",
  "domain": "upx.github.io",
  "description": "UPX - the Ultimate Packer for eXecutables",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/upx.github.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) upx",
  "programs": [
    "upx"
  ],
  "companions": [],
  "dependencies": [
    "zlib.net"
  ],
  "versions": [
    "5.0.1",
    "5.0.0",
    "4.2.4"
  ]
}

export interface UpxgithubioPackage {
  name: "upx";
  domain: "upx.github.io";
  description: "UPX - the Ultimate Packer for eXecutables";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/upx.github.io/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) upx";
  programs: readonly [
    "upx"
  ];
  companions: readonly [];
  dependencies: readonly [
    "zlib.net"
  ];
  versions: readonly [
    "5.0.1",
    "5.0.0",
    "4.2.4"
  ];
}
