import type { vektragithubioPackage } from '../types'

/**
 * vektragithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const vektragithubioPackage: vektragithubioPackage = {
  "name": "vektra.github.io",
  "domain": "vektra.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx vektra.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface vektragithubioPackage {
  name: "vektra.github.io";
  domain: "vektra.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx vektra.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
