import type { PkgxPackage } from '../types'

/**
 * vektragithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const vektragithubioPackage: PkgxPackage = {
  name: "vektra.github.io",
  domain: "vektra.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx vektra.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface VektragithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "vektragithub.io";
  domain: "vektragithub.io";
  description: "Package information for vektragithub.io";
}