import type { PkgxPackage } from '../types'

/**
 * veleroioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const veleroioPackage: PkgxPackage = {
  name: "velero",
  domain: "velero.io",
  description: "Backup and migrate Kubernetes applications and their persistent volumes",
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/velero.io/package.yml",
  homepageUrl: "",
  githubUrl: "https://github.com/pkgxdev/pantry/",
  installCommand: "sh <(curl https://pkgx.sh) velero",
  programs: ["velero"],
  companions: [],
  dependencies: [],
  versions: ["1.16.1"]
}

export interface VeleroioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "velero.io";
  domain: "velero.io";
  description: "Package information for velero.io";
}