import type { veracodecomPackage } from '../types'

/**
 * veracodecomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const veracodecomPackage: veracodecomPackage = {
  "name": "veracode.com",
  "domain": "veracode.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx veracode.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface veracodecomPackage {
  name: "veracode.com";
  domain: "veracode.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx veracode.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
