import type { PkgxPackage } from '../types'

/**
 * vercelcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const vercelcomPackage: PkgxPackage = {
  name: "vercel.com",
  domain: "vercel.com",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx vercel.com",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface VercelcomPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "vercel.com";
  domain: "vercel.com";
  description: "Package information for vercel.com";
}
