import type { PkgxPackage } from '../types'

/**
 * versitycomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const versitycomPackage: PkgxPackage = {
  "name": "versity.com",
  "domain": "versity.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx versity.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "versity.com"
}

export interface VersitycomPackage {
  name: "versity.com";
  domain: "versity.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx versity.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "versity.com";
}
