import type { videolanorgPackage } from '../types'

/**
 * videolanorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const videolanorgPackage: PkgxPackage = {
  "name": "videolan.org",
  "domain": "videolan.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx videolan.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface VideolanorgPackage {
  name: "videolan.org";
  domain: "videolan.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx videolan.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
