import type { PkgxPackage } from '../types'

/**
 * waterlanhomexs4allnlPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const waterlanhomexs4allnlPackage: PkgxPackage = {
  "name": "waterlan.home.xs4all.nl",
  "domain": "waterlan.home.xs4all.nl",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx waterlan.home.xs4all.nl",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface Waterlanhomexs4allnlPackage {
  name: "waterlan.home.xs4all.nl";
  domain: "waterlan.home.xs4all.nl";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx waterlan.home.xs4all.nl";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
