import type { wezfurlongorgPackage } from '../types'

/**
 * wezfurlongorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const wezfurlongorgPackage: wezfurlongorgPackage = {
  "name": "wezfurlong.org",
  "domain": "wezfurlong.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx wezfurlong.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface wezfurlongorgPackage {
  name: "wezfurlong.org";
  domain: "wezfurlong.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx wezfurlong.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
