import type { PkgxPackage } from '../types'

/**
 * wilfredmeukPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const wilfredmeukPackage: PkgxPackage = {
  name: "wilfred.me.uk",
  domain: "wilfred.me.uk",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx wilfred.me.uk",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface WilfredmeukPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "wilfredmeuk";
  domain: "wilfredmeuk";
  description: "Package information for wilfredmeuk";
}
