import type { wixcomPackage } from '../types'

/**
 * wixcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const wixcomPackage: PkgxPackage = {
  "name": "wix.com",
  "domain": "wix.com",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx wix.com",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface WixcomPackage {
  name: "wix.com";
  domain: "wix.com";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx wix.com";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
