import type { PkgxPackage } from '../types'

/**
 * wkentarogithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const wkentarogithubioPackage: PkgxPackage = {
  name: "wkentaro.github.io",
  domain: "wkentaro.github.io",
  description: "",
  packageYmlUrl: "",
  homepageUrl: "",
  githubUrl: "",
  installCommand: "pkgx wkentaro.github.io",
  programs: [],
  companions: [],
  dependencies: [],
  versions: []
}

export interface WkentarogithubioPackage {
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  name: "wkentarogithub.io";
  domain: "wkentarogithub.io";
  description: "Package information for wkentarogithub.io";
}
