import type { PkgxPackage } from '../types'

/**
 * wpewebkitorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const wpewebkitorgPackage: PkgxPackage = {
  "name": "wpewebkit.org",
  "domain": "wpewebkit.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx wpewebkit.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface WpewebkitorgPackage {
  name: "wpewebkit.org";
  domain: "wpewebkit.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx wpewebkit.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
