export const wundergraphcomPackage = {
  name: "wunderctl" as const,
  domain: "wundergraph.com" as const,
  description: "WunderGraph is a Backend for Frontend Framework to optimize frontend, fullstack and backend developer workflows through API Composition." as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/wundergraph.com/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) wunderctl" as const,
  programs: [
    "wunderctl",
  ] as const,
  companions: [] as const,
  dependencies: [] as const,
  versions: [
    "0.181.0",
    "0.180.2",
    "0.180.1",
    "0.180.0",
    "0.179.1",
    "0.179.0",
    "0.178.0",
    "0.177.0",
    "0.176.3",
    "0.176.2",
    "0.176.1",
    "0.176.0",
    "0.175.0",
    "0.174.0",
    "0.173.0",
    "0.172.0",
    "0.171.0",
    "0.170.0",
    "0.169.3",
    "0.169.2",
  ] as const,
  fullPath: "wundergraph.com" as const,
  aliases: [
    "wunderctl",
  ] as const,
}

export type WundergraphcomPackage = typeof wundergraphcomPackage
