import type { xercesapacheorgPackage } from '../types'

/**
 * xercesapacheorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const xercesapacheorgPackage: PkgxPackage = {
  "name": "xerces.apache.org",
  "domain": "xerces.apache.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx xerces.apache.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface XercesapacheorgPackage {
  name: "xerces.apache.org";
  domain: "xerces.apache.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx xerces.apache.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
