import type { xorgPackage } from '../types'

/**
 * xorgPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const xorgPackage: PkgxPackage = {
  "name": "x.org",
  "domain": "x.org",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx x.org",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface XorgPackage {
  name: "x.org";
  domain: "x.org";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx x.org";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
