export const xpraorgPackage = {
  name: 'xpra' as const,
  domain: 'xpra.org' as const,
  description: 'Persistent remote applications for X11; screen sharing for X11, MacOS and MSWindows.' as const,
  packageYmlUrl: 'https://github.com/pkgxdev/pantry/tree/main/projects/xpra.org/package.yml' as const,
  homepageUrl: '' as const,
  githubUrl: 'https://github.com/pkgxdev/pantry/' as const,
  installCommand: 'sh <(curl https://pkgx.sh) xpra' as const,
  programs: [
    'xpra',
  ] as const,
  companions: [] as const,
  dependencies: [
    'pkgx.sh^1',
    'python.org~3.11',
    'cython.org',
    'tukaani.org/xz',
    'cairographics.org',
    'cairographics.org/pycairo@1.26.1',
    'freedesktop.org/pkg-config~0.29',
    'gnome.org/PyGObject',
    'gnome.org/glib',
    'x.org/x11',
    'x.org/protocol',
    'x.org/exts',
    'x.org/xkbfile',
    'x.org/xdamage',
    'x.org/xrandr',
    'x.org/xcomposite',
    'x.org/xtst',
    'x.org/libxres',
    'x.org/xfixes',
    'videolan.org/x264',
    'webmproject.org/libvpx',
    'github.com/AOMediaCodec/libavif',
    'github.com/Cyan4973/xxHash',
    'gtk.org/gtk3',
    'gnome.org/gobject-introspection',
    'harfbuzz.org',
    'gnome.org/gdk-pixbuf',
    'gnome.org/atk',
    'gnome.org/pango',
  ] as const,
  versions: [
    '6.3.0',
    '6.2.5',
    '6.2.4',
    '6.2.3',
    '6.2.2',
    '6.2.1',
    '6.2.0',
    '6.1.3',
    '6.1.2',
  ] as const,
  fullPath: 'xpra.org' as const,
}

export type XpraorgPackage = typeof xpraorgPackage
