import type { xvidcomPackage } from '../types'

/**
 * xvidcomPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const xvidcomPackage: xvidcomPackage = {
  "name": "xvid.com",
  "domain": "xvid.com",
  "description": "",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/xvid.com/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) +xvid.com -- $SHELL -i",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [
    "1.3.7"
  ]
}

export interface xvidcomPackage {
  name: "xvid.com";
  domain: "xvid.com";
  description: "";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/xvid.com/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) +xvid.com -- $SHELL -i";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "1.3.7"
  ];
}
