export const yarnpkgcomPackage = {
  name: "yarn" as const,
  domain: "yarnpkg.com" as const,
  description: "📦🐈 Active development trunk for Yarn ⚒" as const,
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/yarnpkg.com/package.yml" as const,
  homepageUrl: "" as const,
  githubUrl: "https://github.com/pkgxdev/pantry/" as const,
  installCommand: "sh <(curl https://pkgx.sh) +yarnpkg.com -- $SHELL -i" as const,
  programs: [
    "yarn",
    "yarnpkg",
  ] as const,
  companions: [] as const,
  dependencies: [
    "nodejs.org",
  ] as const,
  versions: [
    "4.9.1",
    "4.9.0",
    "4.8.1",
    "4.8.0",
    "4.7.0",
    "4.6.0",
    "4.5.3",
    "4.5.2",
    "4.5.1",
    "4.5.0",
    "4.4.1",
    "4.4.0",
    "4.3.1",
    "4.3.0",
    "4.2.2",
    "4.2.1",
    "4.2.0",
    "4.1.1",
    "4.1.0",
    "4.0.2",
    "4.0.1",
    "4.0.0",
    "3.8.7",
    "3.8.6",
    "3.8.5",
    "3.8.4",
    "3.8.3",
    "3.8.2",
    "3.8.1",
    "3.8.0",
    "3.7.0",
    "3.6.4",
    "3.6.3",
    "3.6.2",
    "3.6.1",
    "3.6.0",
    "3.5.1",
    "3.5.0",
    "3.4.1",
  ] as const,
  fullPath: "yarnpkg.com" as const,
}

export type YarnpkgcomPackage = typeof yarnpkgcomPackage
