import type { yasmtortallnetPackage } from '../types'

/**
 * yasmtortallnetPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const yasmtortallnetPackage: yasmtortallnetPackage = {
  "name": "yasm",
  "domain": "yasm.tortall.net",
  "description": "Yasm Assembler mainline development tree",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/yasm.tortall.net/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) yasm",
  "programs": [
    "yasm"
  ],
  "companions": [],
  "dependencies": [],
  "versions": [
    "1.3.0"
  ]
}

export interface yasmtortallnetPackage {
  name: "yasm";
  domain: "yasm.tortall.net";
  description: "Yasm Assembler mainline development tree";
  packageYmlUrl: "https://github.com/pkgxdev/pantry/tree/main/projects/yasm.tortall.net/package.yml";
  homepageUrl: "";
  githubUrl: "https://github.com/pkgxdev/pantry/";
  installCommand: "sh <(curl https://pkgx.sh) yasm";
  programs: readonly [
    "yasm"
  ];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [
    "1.3.0"
  ];
}
