import type { PkgxPackage } from '../types'

/**
 * yuigithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const yuigithubioPackage: PkgxPackage = {
  "name": "yui.github.io",
  "domain": "yui.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx yui.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": [],
  "fullPath": "yui.github.io"
}

export interface YuigithubioPackage {
  name: "yui.github.io";
  domain: "yui.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx yui.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
  fullPath: "yui.github.io";
}
