import type { yuigithubioPackage } from '../types'

/**
 * yuigithubioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const yuigithubioPackage: yuigithubioPackage = {
  "name": "yui.github.io",
  "domain": "yui.github.io",
  "description": "",
  "packageYmlUrl": "",
  "homepageUrl": "",
  "githubUrl": "",
  "installCommand": "pkgx yui.github.io",
  "programs": [],
  "companions": [],
  "dependencies": [],
  "versions": []
}

export interface yuigithubioPackage {
  name: "yui.github.io";
  domain: "yui.github.io";
  description: "";
  packageYmlUrl: "";
  homepageUrl: "";
  githubUrl: "";
  installCommand: "pkgx yui.github.io";
  programs: readonly [];
  companions: readonly [];
  dependencies: readonly [];
  versions: readonly [];
}
