import type { PkgxPackage } from '../types'

/**
 * zshsourceforgeioPackage information from pkgx.dev
 * Generated by pkgx-tools
 */
export const zshsourceforgeioPackage: PkgxPackage = {
  "name": "zsh",
  "domain": "zsh.sourceforge.io",
  "description": "UNIX shell (command interpreter)",
  "packageYmlUrl": "https://github.com/pkgxdev/pantry/tree/main/projects/zsh.sourceforge.io/package.yml",
  "homepageUrl": "",
  "githubUrl": "https://github.com/pkgxdev/pantry/",
  "installCommand": "sh <(curl https://pkgx.sh) zsh",
  "programs": [
    "zsh"
  ],
  "companions": [],
  "dependencies": [
    "invisible-island.net/ncurses",
    "pcre.org"
  ],
  "versions": [
    "5.9.0"
  ],
  "fullPath": "zsh.sourceforge.io"
}
